unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Student applications for admission into Verto Education</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Applicant_Email__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Email__c</fullName>
    <externalId>true</externalId>
    <label>Applicant Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admitted</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Decision Ready</fullName>
            </value>
            <value>
                <fullName>Deposit Received</fullName>
            </value>
            <value>
                <fullName>Engaged</fullName>
            </value>
            <value>
                <fullName>Family Admissions Call</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Marketing Nurture</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Requirements Gathering</fullName>
            </value>
            <value>
                <fullName>Student Declined Channel Partner</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>Send Student Acceptance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Citizen_Status__c.field-meta.xml
<CustomField>
    <fullName>Citizen_Status__c</fullName>
    <label>Citizen Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>U.S. Citizen or U.S. National</fullName>
            </value>
            <value>
                <fullName>U.S. Dual Citizen</fullName>
            </value>
            <value>
                <fullName>U.S. Permanent Resident</fullName>
            </value>
            <value>
                <fullName>U.S. Refugee or Asylee</fullName>
            </value>
            <value>
                <fullName>Other (non-U.S.)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Criminal_Conviction__c.field-meta.xml
<CustomField>
    <fullName>Criminal_Conviction__c</fullName>
    <description>Form Question: &quot;Do you have any criminal convictions in any country?&quot;</description>
    <inlineHelpText>Form Question: &quot;Do you have any criminal convictions in any country?&quot;</inlineHelpText>
    <label>Criminal Conviction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Disciplinary_Violation__c.field-meta.xml
<CustomField>
    <fullName>Disciplinary_Violation__c</fullName>
    <description>Form Question: &quot;Have you ever been involved in a disciplinary situation at any educational institution you have attended from the 9th grade (or the international equivalent) forward, whether related to academic misconduct or behavioral misconduct?&quot;</description>
    <inlineHelpText>Form Question: &quot;Have you ever been involved in a disciplinary situation at any educational institution you have attended from the 9th grade (or the international equivalent) forward, whether related to academic misconduct or behavioral misconduct?&quot;</inlineHelpText>
    <label>Disciplinary Violation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/First_Generation_College_Student__c.field-meta.xml
<CustomField>
    <fullName>First_Generation_College_Student__c</fullName>
    <description>Form Question: &quot;Do you define yourself as a first-generation college student? (A first-generation college student is defined as a student whose parent(s)/legal guardian(s) have not completed a bachelor’s degree.)&quot;</description>
    <inlineHelpText>Form Question: &quot;Do you define yourself as a first-generation college student? (A first-generation college student is defined as a student whose parent(s)/legal guardian(s) have not completed a bachelor’s degree.)&quot;</inlineHelpText>
    <label>First Generation College Student</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/GPA__c.field-meta.xml
<CustomField>
    <fullName>GPA__c</fullName>
    <label>GPA</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/GPA_Scale__c.field-meta.xml
<CustomField>
    <fullName>GPA_Scale__c</fullName>
    <label>GPA Scale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GPA_Scale</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/High_School_Counselor_Email__c.field-meta.xml
<CustomField>
    <fullName>High_School_Counselor_Email__c</fullName>
    <label>High School Counselor Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/High_School_Counselor_First_Name__c.field-meta.xml
<CustomField>
    <fullName>High_School_Counselor_First_Name__c</fullName>
    <label>High School Counselor First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/High_School_Counselor_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>High_School_Counselor_Last_Name__c</fullName>
    <label>High School Counselor Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/High_School_Counselor_Phone__c.field-meta.xml
<CustomField>
    <fullName>High_School_Counselor_Phone__c</fullName>
    <description>Field created to migrate data from the High School Counselor Phone field on the lead and opportunity (July 2021)</description>
    <label>High School Counselor Phone</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Hispanic_or_Latino_a_x__c.field-meta.xml
<CustomField>
    <fullName>Hispanic_or_Latino_a_x__c</fullName>
    <label>Hispanic or Latino/a/x</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>I prefer not to say</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Parent_Email__c.field-meta.xml
<CustomField>
    <fullName>Parent_Email__c</fullName>
    <label>Parent/Guardian Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Parent_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_First_Name__c</fullName>
    <label>Parent/Guardian First Name</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Parent_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Last_Name__c</fullName>
    <label>Parent/Guardian Last Name</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Parent_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Parent_Phone_Number__c</fullName>
    <label>Parent/Guardian Phone</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Parents_Guardians_Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>Parents_Guardians_Marital_Status__c</fullName>
    <description>Field created to migrate data from the &quot;Parents Marital Status&quot; field on the lead and opportunity (July 2021)</description>
    <label>Parents/Guardians Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Civil Union/ Domestic Partners</fullName>
            </value>
            <value>
                <fullName>Divorced</fullName>
            </value>
            <value>
                <fullName>Married</fullName>
            </value>
            <value>
                <fullName>Never Married</fullName>
            </value>
            <value>
                <fullName>Separated</fullName>
            </value>
            <value>
                <fullName>Widowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Post_Verto_Plans__c.field-meta.xml
<CustomField>
    <fullName>Post_Verto_Plans__c</fullName>
    <label>Post-Verto Plans</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Post_Verto_Plans</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Preferred_Name__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Name__c</fullName>
    <description>The first name that the applicant prefers to be called, e.g. a nickname</description>
    <label>Applicant Preferred First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Race_Ethnicity__c.field-meta.xml
<CustomField>
    <fullName>Race_Ethnicity__c</fullName>
    <label>Race/Ethnicity</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>American Indian or Alaska Native</fullName>
            </value>
            <value>
                <fullName>Asian</fullName>
            </value>
            <value>
                <fullName>Black or African American</fullName>
            </value>
            <value>
                <fullName>Hispanic or Latin American</fullName>
            </value>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>I prefer not to say</fullName>
            </value>
            <value>
                <fullName>Native Hawaiian or Other Pacific Islander</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Intersex</fullName>
            </value>
            <value>
                <fullName>I prefer not to say</fullName>
            </value>
            <value>
                <fullName>Prefer Not to Answer</fullName>
                <isActive>false</isActive>
                <label>Prefer Not to Answer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Year_of_High_School_Graduation__c.field-meta.xml
<CustomField>
    <fullName>Year_of_High_School_Graduation__c</fullName>
    <label>Year of High School Graduation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year_of_High_School_Graduation</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Campaign/recordTypes/Five9.recordType-meta.xml
<RecordType>
    <fullName>Five9</fullName>
    <active>true</active>
    <description>The default record type for Five9 contact center campaigns</description>
    <label>Five9</label>
</RecordType>

unpackaged/main/default/objects/Postal_Code__c/Postal_Code__c.object-meta.xml
<CustomObject>
    <label>Postal Code</label>
    <nameField>
        <label>Postal Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Postal Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/globalValueSets/GPA_Scale.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>4.0</fullName>
    </customValue>
    <customValue>
        <fullName>5.0</fullName>
    </customValue>
    <customValue>
        <fullName>6.0</fullName>
    </customValue>
    <customValue>
        <fullName>100</fullName>
    </customValue>
    <description>The numerical representation of the highest possible grade average a student can achieve at a school</description>
    <masterLabel>GPA Scale</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Post_Verto_Plans.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>I’m interested in learning more about Verto’s partner schools.</fullName>
    </customValue>
    <customValue>
        <fullName>Already committed to a College, University or Other Educational Institution.</fullName>
    </customValue>
    <customValue>
        <fullName>I have not begun planning my post-Verto education.</fullName>
    </customValue>
    <masterLabel>Post-Verto Plans</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Year_of_High_School_Graduation.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1965</fullName>
    </customValue>
    <customValue>
        <fullName>1969</fullName>
    </customValue>
    <customValue>
        <fullName>1973</fullName>
    </customValue>
    <customValue>
        <fullName>1974</fullName>
    </customValue>
    <customValue>
        <fullName>1975</fullName>
    </customValue>
    <customValue>
        <fullName>1977</fullName>
    </customValue>
    <customValue>
        <fullName>1979</fullName>
    </customValue>
    <customValue>
        <fullName>1980</fullName>
    </customValue>
    <customValue>
        <fullName>1981</fullName>
    </customValue>
    <customValue>
        <fullName>1982</fullName>
    </customValue>
    <customValue>
        <fullName>1983</fullName>
    </customValue>
    <customValue>
        <fullName>1984</fullName>
    </customValue>
    <customValue>
        <fullName>1985</fullName>
    </customValue>
    <customValue>
        <fullName>1986</fullName>
    </customValue>
    <customValue>
        <fullName>1987</fullName>
    </customValue>
    <customValue>
        <fullName>1988</fullName>
    </customValue>
    <customValue>
        <fullName>1989</fullName>
    </customValue>
    <customValue>
        <fullName>1990</fullName>
    </customValue>
    <customValue>
        <fullName>1991</fullName>
    </customValue>
    <customValue>
        <fullName>1992</fullName>
    </customValue>
    <customValue>
        <fullName>1993</fullName>
    </customValue>
    <customValue>
        <fullName>1994</fullName>
    </customValue>
    <customValue>
        <fullName>1995</fullName>
    </customValue>
    <customValue>
        <fullName>1996</fullName>
    </customValue>
    <customValue>
        <fullName>1997</fullName>
    </customValue>
    <customValue>
        <fullName>1998</fullName>
    </customValue>
    <customValue>
        <fullName>1999</fullName>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
    </customValue>
    <customValue>
        <fullName>2001</fullName>
    </customValue>
    <customValue>
        <fullName>2002</fullName>
    </customValue>
    <masterLabel>Year of High School Graduation</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ApplicationTriggerHandlerTests.cls
@IsTest
public with sharing class ApplicationTriggerHandlerTests {

    @TestSetup
    static void makeData(){
        //There's a flow relying on an instance of a campaign record, creating the campaign record to prevent the flow from failing temporarily.
        insert new Campaign(
            Name = 'Leads Five9 List',
            RecordTypeId = Schema.sObjectType.Campaign.getRecordTypeInfosByName().get('Five9').getRecordTypeId()
        );    
    }

    @IsTest
    static void testAfterInsert() {
        Test.startTest();
        insert getSampleApplication();
        Test.stopTest();
        System.assertEquals(
            1,
            [SELECT Id FROM Application__c].size(),
            'Expected one successful application inserted.'
        );
    }

    @IsTest
    static void testBulkAfterInsert() {
        List<Application__c> applicationsToInsert = new List<Application__c>();
        Test.startTest();
        for (Integer i = 0; i < 50; i++) {
            applicationsToInsert.add(getSampleApplication());
        }
        insert applicationsToInsert;
        System.assertEquals(
            50,
            [SELECT Id FROM Application__c].size(),
            'Expected 200 successful applications inserted.'
        );
    }

    private static Application__c getSampleApplication() {
        return new Application__c(
            Applicant_First_Name__c = 'Sample',
            Applicant_Last_Name__c = 'Applicant',
            Applicant_Email__c = 'SampleApplication@Test.org',
            Application_Status__c = 'In Review',
            Preferred_Name__c = 'Preferred Name',
            Applicant_Phone__c = '888-888-8888',
            Date_of_Birth__c = System.today().addYears(-18),
            Sex__c = 'Male',
            Race_Ethnicity__c = 'I prefer not to say',
            Hispanic_or_Latino_a_x__c = 'No',
            Citizen_Status__c = 'U.S. Citizen or U.S. National',
            First_Generation_College_Student__c = 'No',
            Post_Verto_Plans__c = 'I’m interested in learning more about Verto’s partner schools.',
            Street__c = '1111 Fake St',
            City__c = 'Faketown',
            State_Province__c = 'California',
            Postal_Code__c = '11111',
            GPA_Scale__c = '4.0',
            GPA__c = 4.0,
            Year_of_High_School_Graduation__c = String.valueOf(System.today().year()),
            High_School_Counselor_First_Name__c = 'Sample',
            High_School_Counselor_Last_Name__c = 'Counselor',
            High_School_Counselor_Email__c = 'SampleCounselor@Test.org',
            High_School_Counselor_Phone__c = '999-999-9999',
            Disciplinary_Violation__c = 'No',
            Criminal_Conviction__c = 'No',
            Parent_First_Name__c = 'Sample',
            Parent_Last_Name__c = 'Parent',
            Parent_Email__c = 'SampleParent@Test.org',
            Parent_Phone_Number__c = '777-777-7777',
            Parents_Guardians_Marital_Status__c = 'Separated',
            RecordTypeId = Schema.sObjectType.Application__c.getRecordTypeInfosByName().get('Traditional Enrollment').getRecordTypeId()
        );
    }
}