unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Student applications for admission into Verto Education</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Lead/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <defaultValue>false</defaultValue>
    <label>z_Application</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Associated_Application__c.field-meta.xml
<CustomField>
    <fullName>Associated_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/AutoConvertLeadsTest.cls
/*
* @author          Dhatrinath Kodali
* @version         1
* @date            14-08-2020
* @description     This class is a test class for AutoConvertLeads.
*/
@isTest
public class AutoConvertLeadsTest {
    @isTest
    static void testM(){
        Application__c refObject0 = new Application__c(Name='test app', Applicant_First_Name__c = 'Test', Applicant_Last_Name__c = 'Applicant');
        insert refObject0;

        Lead objLead = new Lead( FirstName = 'TestLeadConversion', LastName = '2', Company = 'Testing Sample Co', Application__c = FALSE,Email = 'test123@test.com', Associated_Application__c = refObject0.Id);  
        insert objLead;  
        
        AutoConvertLeads.LeadAssign(new List<Id>{objLead.Id});
    }
}