unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Student applications for admission into Verto Education</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Applicant_Email__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Email__c</fullName>
    <externalId>true</externalId>
    <label>Applicant Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/CIO_Integration_Setting__mdt/CIO_Integration_Setting__mdt.object-meta.xml
<CustomObject>
    <label>CIO Integration Setting</label>
    <pluralLabel>CIO Integration Settings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/CIO_Integration_Setting__mdt/fields/Endpoint_Extension__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_Extension__c</fullName>
    <inlineHelpText>Any additional endpoint directory information after the unique identifier.</inlineHelpText>
    <label>Endpoint Extension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CIO_Integration_Setting__mdt/fields/Endpoint_Method__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_Method__c</fullName>
    <label>Endpoint Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POST</fullName>
                <default>true</default>
                <label>POST</label>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CIO_Integration_Setting__mdt/fields/Fields_To_Query__c.field-meta.xml
<CustomField>
    <fullName>Fields_To_Query__c</fullName>
    <inlineHelpText>A comma separated list of fields that will be queried.</inlineHelpText>
    <label>Fields To Query</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/CIO_Integration_Setting__mdt/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <defaultValue>Null</defaultValue>
    <label>SObject</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
                <default>true</default>
                <label>Account</label>
            </value>
            <value>
                <fullName>Application__c</fullName>
            </value>
            <value>
                <fullName>Enrollment_Record__c</fullName>
            </value>
            <value>
                <fullName>Inquiry__c</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CIO_Integration_Setting__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Profile</fullName>
                <default>true</default>
                <label>Profile</label>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CIO_Integration_Setting__mdt/fields/Watch_Fields__c.field-meta.xml
<CustomField>
    <fullName>Watch_Fields__c</fullName>
    <inlineHelpText>A comma separated list of fields to watch for sending update events.</inlineHelpText>
    <label>Watch Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/Enrollment_Record__c.object-meta.xml
<CustomObject>
    <label>Enrollment Record</label>
    <nameField>
        <displayFormat>EN-{00000000}</displayFormat>
        <label>Enrollment Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Student_Account__c.field-meta.xml
<CustomField>
    <fullName>Student_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enrollment Records</relationshipLabel>
    <relationshipName>Enrollment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inquiry__c/Inquiry__c.object-meta.xml
<CustomObject>
    <label>Inquiry</label>
    <nameField>
        <displayFormat>Inquiry-{0000000000}</displayFormat>
        <label>Inquiry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Lead/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <defaultValue>false</defaultValue>
    <label>z_Application</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Enrollment_Record__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrollment Record</label>
    <referenceTo>Enrollment_Record__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/CioIntegrationServices.cls
public without sharing class CioIntegrationServices {
    

    public CioIntegrationServices() {
    }

    public static void syncRecords(
        CIO_Integration_Setting__mdt integrationSetting,
        Map<Id, SObject> records
    ) {
        System.enqueueJob( new CioIntegrationEvent(
            integrationSetting,
            records.keySet()
        ));
    }

    public static void syncRecords(
        CIO_Integration_Setting__mdt integrationSetting,
        Map<Id, SObject> oldRecords,
        Map<Id, SObject> newRecords
    ) {
        List<SObject> recordsToSync = new List<SObject>();
        if (integrationSetting.Watch_Fields__c != null) {
            for (SObject record :newRecords.values()) {
                //do logic filtering by watch fields.
                if (getIntegrationSyncRequired(
                    oldRecords.get(record.Id), 
                    record,
                    integrationSetting.Watch_Fields__c
                )) {
                    recordsToSync.add(record);
                }
            }
        } else {
            recordsToSync.addAll(newRecords.values());
        }
        if (!recordsToSync.isEmpty()) {
            syncRecords(
                integrationSetting, 
                new Map<Id, SObject>(recordsToSync)
            );
        }
    }

    public static Boolean getIntegrationSyncRequired(
        SObject oldValue,
        SObject newValue,
        String fieldsToWatch
    ) {
        Set<String> fieldsToWatchForChanges = getFieldsToWatch(fieldsToWatch);
        return !(
            new SObjectHelper()
                .setCurrentValues(newValue)
                .setOldValues(oldValue)
                .getChangedFields(fieldsToWatchForChanges)
                .isEmpty()
        );
    }
    
    private static Set<String> getFieldsToWatch(String fieldsToWatchString) {
        return new Set<String>(fieldsToWatchString.split(',')); 
    }

    public class CioIntegrationEvent implements Queueable, Database.AllowsCallouts {
        CIO_Integration_Setting__mdt integrationSetting;
        Set<Id> recordIds;

        public CioIntegrationEvent(
            CIO_Integration_Setting__mdt integrationSetting,
            Set<Id> recordIds
        ) {
            this.integrationSetting = integrationSetting;
            this.recordIds = recordIds;
        }

        public void execute(System.QueueableContext context) {
            if (this.recordIds.size() > 200) {
                throw new CioIntegrationServicesException('Cannot sync more than 200 records at a time.');
            }
            List<HttpRequest> requests = new List<HttpRequest>();
            for (SObject record :getQueryResults()) {
                HttpRequest request = new HttpRequest();
                String payload = getPayload(record);
                String email = getEmail(record);
                String endpoint = 'callout:Customer_IO_Production/' + email + (this.integrationSetting.Endpoint_Extension__c == null ? '' : this.integrationSetting.Endpoint_Extension__c);
                request.setEndpoint(endpoint);
                request.setMethod(this.integrationSetting.Endpoint_Method__c);
                request.setHeader('Content-Type', 'application/json;charset=UTF-8');
                request.setHeader('Content-Length', String.valueOf(payload.length()));
                request.setBody(payload);
                requests.add(request);
            }
            if (!requests.isEmpty()) {
                if (TriggerHandler.getIsTestRunning()) {
                    return;
                }
                HttpRequests.makeRequests(
                    requests,
                    new List<String>{'Content-Type', 'Content-Length'}
                );
            }
        }

        @TestVisible
        private List<SObject> getQueryResults() {
            Set<String> ids = new Set<String>();
            for (Id recordId :this.recordIds) {
                ids.add(String.valueOf(recordId));
            }
            //Unfortunately the getInstance method for Custom Metadata objects only retrieves the first 255 characters.
            //It is then required to query this value in order to retrieve the full value for the query.
            //Below string assignment broken up for ease of reading.
            String query = 
                'SELECT ' + 
                [SELECT Fields_To_Query__c FROM CIO_Integration_Setting__mdt WHERE MasterLabel = :this.integrationSetting.MasterLabel LIMIT 1].Fields_To_Query__c + 
                ' FROM ' + 
                this.integrationSetting.SObject__c + ' WHERE Id IN :ids';
            return Database.query(query);
        }

        @TestVisible
        private String getPayload(SObject record) {
            if (this.integrationSetting.Type__c == 'Profile') {
                return getCioProfileBody(record);
            } else {
                return getCioEventBody(record);
            }
        }

        private String getCioProfileBody(SObject record) {
            return JSON.serializePretty(
                new CioProfile().build(record),
                true   
            );
        }

        private String getCioEventBody(SObject record) {
            return JSON.serializePretty(
                new CioEvent().setName(this.integrationSetting.MasterLabel).build(record),
                true
            );            
        }

        @TestVisible
        private String getEmail(SObject record) {
            switch on this.integrationSetting.SObject__c {
                when 'Account' {
                    return (String)record.get('Email__c');
                }
                when 'Application__c' {
                    return (String)record.get('Applicant_Email__c');
                } when 'Enrollment_Record__c' {
                    Enrollment_Record__c enrollment = (Enrollment_Record__c) record;
                    return enrollment.Student_Account__r.Email__c;
                }
                when 'Inquiry__c' {
                    return (String)record.get('Email__c');
                }
                when 'Opportunity' {
                    Opportunity opp = (Opportunity) record;
                    return opp.Account.Email__c;
                }
                when 'Lead' {
                    return (String)record.get('Email');
                }
                when else {
                    return null;
                }
            }
        }
    }

    private class CioIntegrationServicesException extends Exception {

    }
}