unpackaged/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>Event object for tracking and monitoring any upcoming events.</description>
    <label>Event</label>
    <nameField>
        <displayFormat>EVT-{0000000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Event__c/fields/Counselor__c.field-meta.xml
<CustomField>
    <fullName>Counselor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The counselor who will be hosting this event.</description>
    <label>Counselor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Event__c/fields/High_School__c.field-meta.xml
<CustomField>
    <fullName>High_School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>High School</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This High School is not applicable. If there are two or more with the same name, please try another High School.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>contains</operation>
            <value>High School</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inquiry__c/Inquiry__c.object-meta.xml
<CustomObject>
    <label>Inquiry</label>
    <nameField>
        <displayFormat>Inquiry-{0000000000}</displayFormat>
        <label>Inquiry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inquiry__c/fields/Counselor__c.field-meta.xml
<CustomField>
    <fullName>Counselor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Counselor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Inquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inquiry__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Inquiries</relationshipLabel>
    <relationshipName>Inquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inquiry__c/fields/High_School__c.field-meta.xml
<CustomField>
    <fullName>High_School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>High School</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Inquiries (High School)</relationshipLabel>
    <relationshipName>High_School_Inquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Unhandled_Exception__c/Unhandled_Exception__c.object-meta.xml
<CustomObject>
    <label>Unhandled Exception</label>
    <nameField>
        <displayFormat>UE-{0000000}</displayFormat>
        <label>Unhandled Exception Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unhandled Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Unhandled_Exception__c/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <description>Type of unhandled exception.</description>
    <inlineHelpText>Type of unhandled exception.</inlineHelpText>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Unhandled_Exception__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>Line number of code that the exception was thrown.</description>
    <inlineHelpText>Line number of code that the exception was thrown.</inlineHelpText>
    <label>Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Unhandled_Exception__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Unhandled Exception Message.</description>
    <inlineHelpText>Unhandled Exception Message.</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Unhandled_Exception__c/fields/Object_Data__c.field-meta.xml
<CustomField>
    <fullName>Object_Data__c</fullName>
    <description>Text area field to store the attributes of the object that failed DML or created another uncaught exception.</description>
    <label>Object Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Unhandled_Exception__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>Stack trace for the event.</description>
    <inlineHelpText>Stack trace for the event.</inlineHelpText>
    <label>Stack Trace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/HighSchoolEventController.cls
/**
 * @description       : Controller class for High School Event Page
 * @author            : NickHolly
 * @last modified on  : 08-31-2021
 * @last modified by  : NickHolly
**/
public with sharing class HighSchoolEventController {

    public Inquiry__c studentInquiry {get; set;}
    public Boolean consent {get; set;}
    public Id highSchool {get; set;}
    @TestVisible
    private Id eventId {get; set;}
    @TestVisible
    private Id counselorId {get; set;}
    
    public HighSchoolEventController(ApexPages.StandardController controller) {
        resetVariables();
        Map<String, String> parameters = ApexPages.currentPage().getParameters();
        eventId = parameters.get('eid');
        counselorId = parameters.get('cid');
    }
     
    public PageReference submitInformation() {
        try {

            studentInquiry.Event__c = eventId;
            studentInquiry.Counselor__c = counselorId;
            studentInquiry.High_School__c = highSchool;
            //TODO: Add in support for setting the Counselor ID if only an Event ID is passed through, but also look into URL encoding the URL sent to the QR Api
            insert studentInquiry;
        } catch (Exception e) {
            Unhandled_Exception__c unhandledException = new Unhandled_Exception__c(
                Stack_Trace__c = e.getStackTraceString(),
                Line_Number__c = e.getLineNumber(),
                Message__c = e.getMessage(),
                Exception_Type__c = e.getTypeName(),
                Object_Data__c = JSON.serialize(studentInquiry)
            );
            insert unhandledException;
        }
        resetVariables();
        PageReference target = new PageReference('https://vertoeducation.org/apply/');
        target.setRedirect(true);
        return target;
    }

    public void cancelSubmission() {
        resetVariables();
    }
    
    private void resetVariables() {
        studentInquiry = new Inquiry__c(
            RecordTypeId = Schema.sObjectType.Inquiry__c.getRecordTypeInfosByName().get('Request for Information').getRecordTypeId()
        );
        consent = false;
        eventId = null;
        counselorId = null;
    }

    public List<SelectOption> getCountries() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('United States', 'United States'));
        for(Schema.PicklistEntry pickval :Inquiry__c.Country__c.getDescribe().getPicklistValues()) {
            if(pickval.value != 'United States') {
                options.add(new SelectOption(pickval.getValue(), pickval.getLabel()));
            }
        }
        return options;
    }

	public List<SelectOption> getYears() {
		List<SelectOption> options = new List<SelectOption>();
		options.add(new SelectOption('', ''));
		Integer startYear = System.today().addYears(-3).year();
		Integer endYear = System.today().addYears(5).year();
		for(Integer i = startYear; i < endYear; i++) {
			options.add(new SelectOption(String.valueOf(i), String.valueOf(i)));
		}
		return options;
	}

    /* public List<SelectOption> getHighSchools() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('',''));
        List<Account> highSchools = [SELECT Id, Name FROM Account WHERE RecordTypeId = :Schema.sObjectType.Account.getRecordTypeInfosByName().get('High School Account').getRecordTypeId() ORDER BY Name asc LIMIT 999];
        for(Account each :highSchools) {
            options.add(new SelectOption(each.Id, each.Name));
        }
        return options;
    } */
}