unpackaged/main/default/objects/Enrollment_Record__c/Enrollment_Record__c.object-meta.xml
<CustomObject>
    <label>Enrollment Record</label>
    <nameField>
        <displayFormat>EN-{00000000}</displayFormat>
        <label>Enrollment Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Enrollment Records</relationshipLabel>
    <relationshipName>Enrollment_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Enrollment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Program__c.Location__r.Id</field>
            <operation>notEqual</operation>
            <value>a1G3h000000i2EQ</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Enrollment Records</relationshipLabel>
    <relationshipName>Enrollment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Program_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Program_End_Date__c</fullName>
    <formula>Program__r.Program_End_Date__c</formula>
    <label>Program End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Program_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Program_Start_Date__c</fullName>
    <description>This field was created for use in Five9 auto-dial campaigns.</description>
    <formula>Program__r.Program_Start_Date__c</formula>
    <label>Program Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Student_Account__c.field-meta.xml
<CustomField>
    <fullName>Student_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enrollment Records</relationshipLabel>
    <relationshipName>Enrollment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Enrollment_Record__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrollment Record</label>
    <referenceTo>Enrollment_Record__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Program__c/fields/Program_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Program_End_Date__c</fullName>
    <description>Semester end date handled at the program level. Typically handled by Akilah or a Salesforce Admin.</description>
    <label>Program End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Program__c/fields/Program_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Program_Start_Date__c</fullName>
    <description>Semester start date, but handled per program. This is typically maintained by Akilah or another Salesforce Admin.</description>
    <label>Program Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Enrolling</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unhandled_Exception__c/Unhandled_Exception__c.object-meta.xml
<CustomObject>
    <label>Unhandled Exception</label>
    <nameField>
        <displayFormat>UE-{0000000}</displayFormat>
        <label>Unhandled Exception Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unhandled Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Unhandled_Exception__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Verto_Form_Submission__c/Verto_Form_Submission__c.object-meta.xml
<CustomObject>
    <description>Form submissions from guest site pages.</description>
    <label>Verto Form Submission</label>
    <nameField>
        <displayFormat>Verto Form-{0000000}</displayFormat>
        <label>Form Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verto Form Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Verto_Form_Submission__c/fields/Enrollment_Record__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrollment Record</label>
    <referenceTo>Enrollment_Record__c</referenceTo>
    <relationshipLabel>Verto Form Submissions</relationshipLabel>
    <relationshipName>Verto_Form_Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Verto_Form_Submission__c/fields/Legal_Document_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Legal_Document_Expiration_Date__c</fullName>
    <label>Legal Document Expiration Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Verto_Form_Submission__c/fields/Legal_Document_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Legal_Document_Issue_Date__c</fullName>
    <label>Legal Document Issue Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Verto_Form_Submission__c/fields/Legal_Document_Issuing_Country__c.field-meta.xml
<CustomField>
    <fullName>Legal_Document_Issuing_Country__c</fullName>
    <label>Legal Document Issuing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Verto_Form_Submission__c/fields/Legal_Document_Sex__c.field-meta.xml
<CustomField>
    <fullName>Legal_Document_Sex__c</fullName>
    <label>Legal Document Sex</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Verto_Form_Submission__c/fields/Legal_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Full_Name__c</fullName>
    <description>The full legal name submitted. Used when the name input is a single field instead of separate First and Last Name fields.</description>
    <label>Legal Full Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Verto_Form_Submission__c/fields/Passport_Number__c.field-meta.xml
<CustomField>
    <fullName>Passport_Number__c</fullName>
    <label>Passport Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Verto_Form_Submission__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <formula>IF(
    !ISBLANK(Enrollment_Record__c),
    Enrollment_Record__r.Program__r.Name,
    null
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Verto_Form_Submission__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
                <default>true</default>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Verto_Form_Submission__c/recordTypes/Passport.recordType-meta.xml
<RecordType>
    <fullName>Passport</fullName>
    <active>true</active>
    <label>Passport</label>
</RecordType>

unpackaged/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <customValue>
        <fullName>Costa Rica</fullName>
    </customValue>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/VertoPassportUploadControllerTests.cls
@isTest
public with sharing class VertoPassportUploadControllerTests {

    @TestSetup
    static void makeData(){
        User studentSuccessUser = new User(
            FirstName = 'Student Success',
            LastName = 'User',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard User - Verto' LIMIT 1].Id,
            UserName = 'StudentSuccess@VertoEducation.org',
            Email = 'StudentSuccess@VertoEducation.org',
            Alias = 'example',
            LocaleSidKey = 'en_US',
            TimeZoneSidKey = 'GMT',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US'
        );
        insert studentSuccessUser;
        User guestSiteUser = new User(
            FirstName = 'Public',
            LastName = 'Site',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Passport Upload Profile' LIMIT 1].Id,
            UserName = 'PublicSite@VertoEducation.org',
            Email = 'PublicSite@VertoEducation.org',
            Alias = 'example',
            LocaleSidKey = 'en_US',
            TimeZoneSidKey = 'GMT',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US'
        );
        insert guestSiteUser;
        Account sampleAccount = new Account(
            Name = 'Sample Account',
            First_Name__c = 'Sample',
            Last_Name__c = 'Account',
            RecordTypeId = Schema.sObjectType.Account.getRecordTypeInfosByName().get('Student Account').getRecordTypeId()
        );
        insert sampleAccount;
        Opportunity sampleOpportunity = new Opportunity(
            Name = 'Sample Opportunity',
            AccountId = sampleAccount.Id,
            CloseDate = System.today().addDays(30),
            StageName = 'Qualification'
        );
        insert sampleOpportunity;
        Program__c sampleProgram = new Program__c(
            Name = 'Sample Program',
            Status__c = 'Planning',
            Program_Start_Date__c = System.today(),
            Program_End_Date__c = System.today().addMonths(3)
        );
        insert sampleProgram;
        Enrollment_Record__c sampleEnrollmentRecord = new Enrollment_Record__c(
            Student_Account__c = sampleAccount.Id,
            Opportunity__c = sampleOpportunity.Id,
            Owner__c = studentSuccessUser.Id,
            Program__c = sampleProgram.Id
        );
        insert sampleEnrollmentRecord;
    }

    @IsTest
    static void testPageLoad() {
        Enrollment_Record__c sampleEnrollmentRecord = [SELECT Id, Student_Account__c, Program__c, Opportunity__c FROM Enrollment_Record__c LIMIT 1];
        Test.startTest();
        User siteUser = [SELECT Id FROM User WHERE UserName = 'PublicSite@VertoEducation.org' LIMIT 1];
        PermissionSetAssignment guestSiteUserPermissions = new PermissionSetAssignment(
            PermissionSetId = [SELECT Id FROM PermissionSet WHERE Name = 'Create_Verto_Form_Submission' LIMIT 1].Id,
            AssigneeId = siteUser.Id
        );
        insert guestSiteUserPermissions;
        System.runAs(siteUser){
            PageReference pageInfo = Page.VertoPassportUpload;
            Test.setCurrentPage(pageInfo);
            pageInfo.getParameters().put('aid', sampleEnrollmentRecord.Student_Account__c);
            pageInfo.getParameters().put('program', sampleEnrollmentRecord.Program__c);
            ApexPages.StandardController controller = new ApexPages.StandardController(new Verto_Form_Submission__c());
            VertoPassportUploadController page = new VertoPassportUploadController(controller);
            page.getCountries();
            page.getYesOrNo();
            page.getNewOrRenewing();
            page.getPrograms();
            page.getPassportSex();
            System.assertEquals(
                false,
                page.showThankYou,
                'Expected false, as no ThankYou parameter was included in the page URL'
            );
            System.assertEquals(
                2,
                ApexPages.currentPage().getParameters().size(),
                'There should only be two parameters passed to the page, Account ID and Program ID.'
            );
            //TODO Once encryption is added for url, update this assertion.
            System.assertEquals(
                sampleEnrollmentRecord.Student_Account__c,
                ApexPages.currentPage().getParameters().get('aid'),
                'Enrollment Record Student_Account__r.Id matches the AID value.'
            );
        }
        Test.stopTest();
        
    }

    @isTest
    static void testCancelSubmission() {
        Enrollment_Record__c sampleEnrollmentRecord = [SELECT Id, Student_Account__c, Program__c, Opportunity__c FROM Enrollment_Record__c LIMIT 1];
        Test.startTest();
        User siteUser = [SELECT Id FROM User WHERE UserName = 'PublicSite@VertoEducation.org' LIMIT 1];
        PermissionSetAssignment guestSiteUserPermissions = new PermissionSetAssignment(
            PermissionSetId = [SELECT Id FROM PermissionSet WHERE Name = 'Create_Verto_Form_Submission' LIMIT 1].Id,
            AssigneeId = siteUser.Id
        );
        insert guestSiteUserPermissions;
        System.runAs(siteUser){
            PageReference pageInfo = Page.VertoPassportUpload;
            Test.setCurrentPage(pageInfo);
            pageInfo.getParameters().put('aid', sampleEnrollmentRecord.Student_Account__c);
            pageInfo.getParameters().put('program', sampleEnrollmentRecord.Program__c);
            ApexPages.StandardController controller = new ApexPages.StandardController(new Verto_Form_Submission__c());
            VertoPassportUploadController page = new VertoPassportUploadController(controller);
            PageReference redirectedPage = page.cancelSubmission();
            System.assertEquals(
                0,
                redirectedPage.getParameters().size(),
                'Expected no parameters to be present in the redirected page.'
            );
            System.assertEquals(
                false,
                redirectedPage.getUrl().contains('ThankYou'),
                'Thank you page should not be displaying after method call. Thank you page is controlled by showThankYou variable value.'
            );

            System.assertEquals(
                false,
                page.showError,
                'Expected false, as no ThankYou parameter is to be included in PageReference from this method.'
            );
            System.assertEquals(
                false,
                page.showThankYou,
                'Expected false, as no ThankYou parameter is to be included in PageReference from this method.'
            );
        }
        System.assertEquals(
            0,
            [SELECT Id FROM Unhandled_Exception__c].size(),
            'No Unhandled Exception records should have been created, meaning the flow executed successfully.'
        );
        Test.stopTest();
    }

    @isTest
    static void testSubmitInformation() {
        Enrollment_Record__c sampleEnrollmentRecord = [SELECT Id, Student_Account__c, Program__c, Opportunity__c FROM Enrollment_Record__c LIMIT 1];
        Test.startTest();
        User siteUser = [SELECT Id FROM User WHERE UserName = 'PublicSite@VertoEducation.org' LIMIT 1];
        PermissionSetAssignment guestSiteUserPermissions = new PermissionSetAssignment(
            PermissionSetId = [SELECT Id FROM PermissionSet WHERE Name = 'Create_Verto_Form_Submission' LIMIT 1].Id,
            AssigneeId = siteUser.Id
        );
        insert guestSiteUserPermissions;
        System.runAs(siteUser){
            PageReference pageInfo = Page.VertoPassportUpload;
            Test.setCurrentPage(pageInfo);
            pageInfo.getParameters().put('aid', sampleEnrollmentRecord.Student_Account__c);
            pageInfo.getParameters().put('program', sampleEnrollmentRecord.Program__c);
            ApexPages.StandardController controller = new ApexPages.StandardController(new Verto_Form_Submission__c());
            VertoPassportUploadController page = new VertoPassportUploadController(controller);
            page.program = 'Costa Rica';
            page.validPassport = 'Yes';
            page.record = new Verto_Form_Submission__c(
                Legal_Full_Name__c = 'Jane Doe',
                Passport_Number__c = String.valueOf(Math.random() * 100000000).left(10),
                Legal_Document_Issuing_Country__c = 'United States',
                Legal_Document_Sex__c = 'Female',
                Legal_Document_Issue_Date__c = System.today().addYears(-1),
                Legal_Document_Expiration_Date__c = System.today().addYears(9)
            );
            PageReference redirectedPage = page.submitInformation();
            /* System.assertEquals(
                True,
                redirectedPage.getUrl().contains('ThankYou'),
                'Expected URL to contain \'Thank You\' parameter.'
            );
            System.assertEquals(
                'Passport',
                redirectedPage.getParameters().get('ref'),
                'Expected Thank You message displayed should be for the Passport submitted event.'
            ); */
        }
        Test.stopTest();
        System.assertEquals(
            0,
            [SELECT Id FROM Unhandled_Exception__c].size(),
            'No Unhandled Exception records should have been created, meaning the records and files were inserted successfully.'
        );
        System.assertEquals(
            sampleEnrollmentRecord.Id,
            [SELECT Enrollment_Record__c FROM Verto_Form_Submission__c LIMIT 1].Enrollment_Record__c,
            'Expected to Verto_Form_Submission__c.Enrollment_Record__c to match the ID of sample Enrollment_Record__c record'
        );

    }

    @IsTest
    static void testNotifyRecordOwner(){
        Enrollment_Record__c sampleEnrollmentRecord = [SELECT Id, Student_Account__c, Program__c, Opportunity__c FROM Enrollment_Record__c LIMIT 1];
        Test.startTest();
        User siteUser = [SELECT Id FROM User WHERE UserName = 'PublicSite@VertoEducation.org' LIMIT 1];
        PermissionSetAssignment guestSiteUserPermissions = new PermissionSetAssignment(
            PermissionSetId = [SELECT Id FROM PermissionSet WHERE Name = 'Create_Verto_Form_Submission' LIMIT 1].Id,
            AssigneeId = siteUser.Id
        );
        insert guestSiteUserPermissions;
        System.runAs(siteUser){
            PageReference pageInfo = Page.VertoPassportUpload;
            Test.setCurrentPage(pageInfo);
            pageInfo.getParameters().put('aid', sampleEnrollmentRecord.Student_Account__c);
            pageInfo.getParameters().put('program', sampleEnrollmentRecord.Program__c);
            ApexPages.StandardController controller = new ApexPages.StandardController(new Verto_Form_Submission__c());
            VertoPassportUploadController page = new VertoPassportUploadController(controller);
            PageReference redirectedPage = page.notifyRecordOwner();
            System.assertEquals(
                True,
                redirectedPage.getUrl().contains('ThankYou'),
                'Thank you page should be displaying after method call. Thank you page is controlled by showThankYou variable value.'
            );
            System.assertEquals(
                'Notify',
                redirectedPage.getParameters().get('ref'),
                'The Thank You message displayed should be for the Notify SOA event.'
            ); 
        }
        System.assertEquals(
            0,
            [SELECT Id FROM Unhandled_Exception__c].size(),
            'No Unhandled Exception records should have been created, meaning the flow executed successfully.'
        );
        Test.stopTest();
    }

    @IsTest
    static void testUnhandleExceptionLogging() {
        Enrollment_Record__c sampleEnrollmentRecord = [SELECT Id, Student_Account__c, Program__c, Opportunity__c FROM Enrollment_Record__c LIMIT 1];
        Test.startTest();
        User siteUser = [SELECT Id FROM User WHERE UserName = 'PublicSite@VertoEducation.org' LIMIT 1];
        PermissionSetAssignment guestSiteUserPermissions = new PermissionSetAssignment(
            PermissionSetId = [SELECT Id FROM PermissionSet WHERE Name = 'Create_Verto_Form_Submission' LIMIT 1].Id,
            AssigneeId = siteUser.Id
        );
        insert guestSiteUserPermissions;
        System.runAs(siteUser){
            PageReference pageInfo = Page.VertoPassportUpload;
            Test.setCurrentPage(pageInfo);
            pageInfo.getParameters().put('aid', 'Invalid Record Id');
            pageInfo.getParameters().put('program', sampleEnrollmentRecord.Program__c);
            ApexPages.StandardController controller = new ApexPages.StandardController(new Verto_Form_Submission__c());
            VertoPassportUploadController page = new VertoPassportUploadController(controller);
            page.notifyRecordOwner();
            page.program = 'Costa Rica';
            page.record = new Verto_Form_Submission__c(
                Legal_Full_Name__c = 'Jane Doe',
                Passport_Number__c = String.valueOf(Math.random() * 100000000),
                Legal_Document_Issuing_Country__c = 'United States',
                Legal_Document_Sex__c = 'Female',
                Legal_Document_Issue_Date__c = System.today().addYears(-1),
                Legal_Document_Expiration_Date__c = System.today().addYears(9)
            );
            page.submitInformation();
        }
        Test.stopTest();
        System.assertEquals(
            2,
            [SELECT Id FROM Unhandled_Exception__c].size(),
            'Three expected Unhandled Exceptions inserted.'
        );
    }
}