unpackaged/main/default/objects/Enrollment_Record__c/Enrollment_Record__c.object-meta.xml
<CustomObject>
    <label>Enrollment Record</label>
    <nameField>
        <displayFormat>EN-{00000000}</displayFormat>
        <label>Enrollment Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Enrollment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Program__c.Location__r.Id</field>
            <operation>notEqual</operation>
            <value>a1G3h000000i2EQ</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Enrollment Records</relationshipLabel>
    <relationshipName>Enrollment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Student_Account__c.field-meta.xml
<CustomField>
    <fullName>Student_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enrollment Records</relationshipLabel>
    <relationshipName>Enrollment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/VertoPassportUploadHelperWS.cls
public without sharing class VertoPassportUploadHelperWS {

    public static SObject insertRecord(SObject record) {
        if(record == null) {
            return null;
        }
        insert record;
        return record;
    }

    public static Enrollment_Record__c getEnrollmentRecord(
        Id accountId,
        Id programId    
    ) {
        if(
            String.valueOf(accountId.getSobjectType()) != String.valueOf(Account.getSObjectType()) || 
            String.valueOf(programId.getSobjectType()) != String.valueOf(Program__c.getSObjectType())
        ) {
           throw new IllegalArgumentException('Invalid parameters received.'); 
        }
        return [SELECT Id, Owner__c
        FROM Enrollment_Record__c
        WHERE Student_Account__c = :accountId
        AND Program__c = :programId
        LIMIT 1];
    }
}