unpackaged/main/default/objects/Transcript_Evaluation__c/Transcript_Evaluation__c.object-meta.xml
<CustomObject>
    <label>Transcript Evaluation</label>
    <nameField>
        <displayFormat>TE-{00000000}</displayFormat>
        <label>Transcript Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transcript Evaluations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Transcript_Evaluation__c/fields/Junior_Year_English_Grade__c.field-meta.xml
<CustomField>
    <fullName>Junior_Year_English_Grade__c</fullName>
    <label>Junior Year English Grade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B- or Higher</fullName>
            </value>
            <value>
                <fullName>C+ or Lower</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Transcript_Evaluation__c/fields/Math_Completed__c.field-meta.xml
<CustomField>
    <fullName>Math_Completed__c</fullName>
    <label>Math Completed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Algebra II</fullName>
            </value>
            <value>
                <fullName>Pre-Calculus</fullName>
            </value>
            <value>
                <fullName>Calculus</fullName>
            </value>
            <value>
                <fullName>Contemporary Math</fullName>
                <isActive>false</isActive>
                <label>Contemporary Math</label>
            </value>
            <value>
                <fullName>Geometry</fullName>
                <isActive>false</isActive>
                <label>Geometry</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Pre-Calculus I</fullName>
                <isActive>false</isActive>
                <label>Pre-Calculus I</label>
            </value>
            <value>
                <fullName>Pre-Calculus II</fullName>
                <isActive>false</isActive>
                <label>Pre-Calculus II</label>
            </value>
            <value>
                <fullName>Trigonometry</fullName>
                <isActive>false</isActive>
                <label>Trigonometry</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Transcript_Evaluation__c/fields/Spanish_Completed__c.field-meta.xml
<CustomField>
    <fullName>Spanish_Completed__c</fullName>
    <label>Spanish Completed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One Year</fullName>
            </value>
            <value>
                <fullName>Two Years</fullName>
            </value>
            <value>
                <fullName>Three Years</fullName>
            </value>
            <value>
                <fullName>Four Years</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CourseEligibility.cls
public with sharing class CourseEligibility {
    @AuraEnabled
    public Course course {get; set;}
    @AuraEnabled
    public List<String> prerequisiteGroupsSatisfied {get; set;}
    @AuraEnabled
    public Boolean isEligible {get; set;}
    @AuraEnabled
    public Boolean requiresCorequisite {get; set;}
    @AuraEnabled
    public Id corequisiteCourseId {get; set;}
    @AuraEnabled
    public String corequisiteCourseName {get; set;}
    
    

    public CourseEligibility() {
        this.prerequisiteGroupsSatisfied = new List<String>();
    }

    public CourseEligibility setCourse(Course course) {
        this.course = course;
        return this;
    }

    public CourseEligibility setIsEligible(Boolean isEligible) {
        this.isEligible = isEligible;
        return this;
    }

    public CourseEligibility evaluateEligibility(Transcript_Evaluation__c evaluation) {
        if (this.course == null) {
            throw new CourseEligibilityException('No course set to evaluate.');
        }
        this.evaluatePrerequisites(evaluation);
        this.evaluateCorequisites();
        this.isEligible = !this.prerequisiteGroupsSatisfied.isEmpty();
        return this;
    }

    private CourseEligibility evaluatePrerequisites(Transcript_Evaluation__c evaluation) {
        if (!this.course.hasPrerequisites) {
            this.isEligible = true;
            this.requiresCorequisite = false;
            return this;
        } else {
            Set<String> answeredQuestions = new Set<String>();
            answeredQuestions.add(evaluation.Math_Completed__c);
            answeredQuestions.add(evaluation.Spanish_Completed__c);
            answeredQuestions.add(evaluation.Junior_Year_English_Grade__c);
            answeredQuestions.remove(null);
            for (String groupLetter :this.course.prerequisites.keySet()) {
                List<Boolean> conditionEvaluationResults = new List<Boolean>();
                for (Course.Prerequisite prereq :this.course.prerequisites.get(groupLetter)) {
                    conditionEvaluationResults.add(
                        prereq.isConditionMet(answeredQuestions)
                    );
                }
                if (conditionEvaluationResults.contains(false)) {
                    continue;
                }
                this.prerequisiteGroupsSatisfied.add(groupLetter);
            }
        }
        return this;
    }

    private void evaluateCorequisites() {
        if (this.course.hasCorequisites) {
            Set<String> groupsNotRequiringCorequisite = new Set<String>(this.prerequisiteGroupsSatisfied);
            Map<String, Course.Corequisite> groupsRequiringCorequisite = new Map<String, Course.Corequisite>();
            for (Course.Corequisite corequisite :this.course.corequisites) {
                if (corequisite.strictRequirement) {
                    this.corequisiteCourseId = corequisite.corequisiteId;
                    this.corequisiteCourseName = corequisite.corequisiteName;
                    groupsNotRequiringCorequisite.clear();
                    break;
                }
                if (this.prerequisiteGroupsSatisfied.contains(corequisite.corequisiteGroup)) {
                    groupsNotRequiringCorequisite.remove(corequisite.corequisiteGroup);
                    groupsRequiringCorequisite.put(corequisite.corequisiteGroup, corequisite);
                }
            }
            this.requiresCorequisite = groupsNotRequiringCorequisite.isEmpty();
            if (groupsNotRequiringCorequisite.isEmpty()) {
                for (String prerequisiteGroup :this.prerequisiteGroupsSatisfied) {
                    if (groupsRequiringCorequisite.containsKey(prerequisiteGroup)) {
                        Course.Corequisite corequisite = groupsRequiringCorequisite.get(prerequisiteGroup);
                        this.corequisiteCourseId = corequisite.corequisiteId;
                        this.corequisiteCourseName = corequisite.corequisiteName;
                    }
                }
            }
        }
    }

    public class CourseEligibilityException extends Exception {

    }
}