unpackaged/main/default/objects/Inquiry__c/Inquiry__c.object-meta.xml
<CustomObject>
    <label>Inquiry</label>
    <nameField>
        <displayFormat>Inquiry-{0000000000}</displayFormat>
        <label>Inquiry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inquiry__c/fields/Parent_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_First_Name__c</fullName>
    <label>Parent First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inquiry__c/fields/Parent_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Last_Name__c</fullName>
    <label>Parent Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inquiry__c/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <label>Persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospective Student</fullName>
            </value>
            <value>
                <fullName>Prospective Parent</fullName>
            </value>
            <value>
                <fullName>High School Counselor</fullName>
            </value>
            <value>
                <fullName>Independent Educational Consultant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inquiry__c/fields/Year_of_Graduation__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Graduation__c</fullName>
    <label>Year of High School Graduation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year_of_High_School_Graduation</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Associated_Application__c.field-meta.xml
<CustomField>
    <fullName>Associated_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Parent_Email__c.field-meta.xml
<CustomField>
    <fullName>Parent_Email__c</fullName>
    <externalId>true</externalId>
    <label>Parent/Guardian Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Parent_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_First_Name__c</fullName>
    <label>Parent/Guardian First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Parent_Guardian_2_Email__c.field-meta.xml
<CustomField>
    <fullName>Parent_Guardian_2_Email__c</fullName>
    <label>Parent/Guardian 2 Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Parent_Guardian_2_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Guardian_2_First_Name__c</fullName>
    <label>Parent/Guardian 2 First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Parent_Guardian_2_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Guardian_2_Last_Name__c</fullName>
    <label>Parent/Guardian 2 Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Parent_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Last_Name__c</fullName>
    <label>Parent/Guardian Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <defaultValue>&quot;US High School Student&quot;</defaultValue>
    <label>Persona</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>US High School Student</fullName>
            </value>
            <value>
                <fullName>International High School Student</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>High School Guidance Counselor</fullName>
            </value>
            <value>
                <fullName>Independent Educational Consultant</fullName>
            </value>
            <value>
                <fullName>Prospective Student</fullName>
            </value>
            <value>
                <fullName>Prospective Parent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Year_of_Graduation__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Graduation__c</fullName>
    <label>Year of High School Graduation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/Calendly_Link__c.field-meta.xml
<CustomField>
    <fullName>Calendly_Link__c</fullName>
    <label>Calendly Link</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/globalValueSets/Year_of_High_School_Graduation.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1965</fullName>
    </customValue>
    <customValue>
        <fullName>1969</fullName>
    </customValue>
    <customValue>
        <fullName>1973</fullName>
    </customValue>
    <customValue>
        <fullName>1974</fullName>
    </customValue>
    <customValue>
        <fullName>1975</fullName>
    </customValue>
    <customValue>
        <fullName>1977</fullName>
    </customValue>
    <customValue>
        <fullName>1979</fullName>
    </customValue>
    <customValue>
        <fullName>1980</fullName>
    </customValue>
    <customValue>
        <fullName>1981</fullName>
    </customValue>
    <customValue>
        <fullName>1982</fullName>
    </customValue>
    <customValue>
        <fullName>1983</fullName>
    </customValue>
    <customValue>
        <fullName>1984</fullName>
    </customValue>
    <customValue>
        <fullName>1985</fullName>
    </customValue>
    <customValue>
        <fullName>1986</fullName>
    </customValue>
    <customValue>
        <fullName>1987</fullName>
    </customValue>
    <customValue>
        <fullName>1988</fullName>
    </customValue>
    <customValue>
        <fullName>1989</fullName>
    </customValue>
    <customValue>
        <fullName>1990</fullName>
    </customValue>
    <customValue>
        <fullName>1991</fullName>
    </customValue>
    <customValue>
        <fullName>1992</fullName>
    </customValue>
    <customValue>
        <fullName>1993</fullName>
    </customValue>
    <customValue>
        <fullName>1994</fullName>
    </customValue>
    <customValue>
        <fullName>1995</fullName>
    </customValue>
    <customValue>
        <fullName>1996</fullName>
    </customValue>
    <customValue>
        <fullName>1997</fullName>
    </customValue>
    <customValue>
        <fullName>1998</fullName>
    </customValue>
    <customValue>
        <fullName>1999</fullName>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
    </customValue>
    <customValue>
        <fullName>2001</fullName>
    </customValue>
    <customValue>
        <fullName>2002</fullName>
    </customValue>
    <masterLabel>Year of High School Graduation</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CioProfile.cls
public with sharing class CioProfile {

    private Address address;
    private String associatedApplication;
    private String collegeCounselor;
    private String collegeCounselorCalendly;
    private String collegeCounselorEmail;
    private String collegeCounselorPhone;
    private String country;
    private DateTime createdDate;
    private String currentProgram;
    private String currentSemester;
    private String email;
    private String enrollmentOwner;
    private String familyInterviewBookedDate;
    private String familyAdmissionsCallCalendly;
    private String familyAdmissionsCallDateTime;
    private String familyAdmissionsCallStatus;
    private String firstGenerationCollegeStudent;
    private String firstName;
    private Decimal gpa;
    private String gpaScale;
    private Date highSchoolTranscriptSubmittedOn;
    private String lastName;
    private String leadOwnerCalendly;
    private String leadOwnerEmail;
    private String leadOwnerName;
    private String leadOwnerPhone;
    private String leadRecordType;
    private String leadSource;
    private String leadStatus;
    private String opportunityOwnerCalendly;
    private String opportunityOwnerEmail;
    private String opportunityOwnerName;
    private String opportunityOwnerPhone;
    private String parentGuardianEmail;
    private String parentGuardianName;
    private String parentGuardian2Email;
    private String parentGuardian2Name;
    private String persona;
    private String phone;
    private String postVertoPlans;
    private String schoolOfRecord;
    private String stage;
    private String state;
    private Date writingSampleSubmittedOn;
    private String yearOfGraduation;
    private String zipCode;

    public CioProfile build(SObject record) {
        String sObjectType = String.valueOf(((Id)record.get('Id')).getSObjectType());
        switch on sObjectType {
            when 'Lead' {
                buildLeadProfile((Lead) record);
            }
            when 'Inquiry__c' {
                buildInquiryProfile((Inquiry__c) record);
            }
        }
        return this;
    }

    private void buildInquiryProfile(Inquiry__c inquiry) {
        this.createdDate = inquiry.CreatedDate;
        this.email = inquiry.Email__c;
        this.firstName = inquiry.First_Name__c;
        this.lastName = inquiry.Last_Name__c;
        this.persona = inquiry.Persona__c;
    }

    private void buildLeadProfile(Lead lead) {
        User leadOwner = lead.Owner;
        this.address = lead.address;
        this.associatedApplication = lead.Associated_Application__c;
        this.country = lead.Country;
        this.createdDate = lead.createdDate;
        this.email = lead.Email;
        this.firstName = lead.FirstName;
        this.lastName = lead.LastName;
        this.leadOwnerCalendly = leadOwner?.Calendly_Link__c;
        this.leadOwnerEmail = leadOwner?.Email;
        this.leadOwnerName = leadOwner?.Name;
        this.leadOwnerPhone = leadOwner?.Phone;
        this.leadRecordType = lead.RecordType.Name;
        this.leadSource = lead.LeadSource;
        this.leadStatus = lead.Status;
        this.parentGuardianEmail = lead.Parent_email__c;
        this.parentGuardianName = lead.Parent_First_Name__c + ' ' + lead.Parent_Last_Name__c;
        this.parentGuardian2Email = lead.Parent_Guardian_2_Email__c;
        this.parentGuardian2Name = lead.Parent_Guardian_2_First_Name__c + ' ' + lead.Parent_Guardian_2_Last_Name__c;
        this.persona = lead.Persona__c;
        this.state = lead.State;
        this.yearOfGraduation = lead.Year_of_Graduation__c;
    }


    private class CioProfileException extends Exception {

    }
}