unpackaged/main/default/objects/ContentVersion/fields/Guest_Site_fileupload__c.field-meta.xml
<CustomField>
    <fullName>Guest_Site_fileupload__c</fullName>
    <description>The ID of the record to attach the uploaded file to.</description>
    <label>Guest Site fileupload</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/Enrollment_Record__c.object-meta.xml
<CustomObject>
    <label>Enrollment Record</label>
    <nameField>
        <displayFormat>EN-{00000000}</displayFormat>
        <label>Enrollment Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Enrollment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Unhandled_Exception__c/Unhandled_Exception__c.object-meta.xml
<CustomObject>
    <label>Unhandled Exception</label>
    <nameField>
        <displayFormat>UE-{0000000}</displayFormat>
        <label>Unhandled Exception Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unhandled Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Unhandled_Exception__c/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <description>Type of unhandled exception.</description>
    <inlineHelpText>Type of unhandled exception.</inlineHelpText>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Unhandled_Exception__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>Line number of code that the exception was thrown.</description>
    <inlineHelpText>Line number of code that the exception was thrown.</inlineHelpText>
    <label>Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Unhandled_Exception__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Unhandled Exception Message.</description>
    <inlineHelpText>Unhandled Exception Message.</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Unhandled_Exception__c/fields/Object_Data__c.field-meta.xml
<CustomField>
    <fullName>Object_Data__c</fullName>
    <description>Text area field to store the attributes of the object that failed DML or created another uncaught exception.</description>
    <label>Object Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Unhandled_Exception__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>Stack trace for the event.</description>
    <inlineHelpText>Stack trace for the event.</inlineHelpText>
    <label>Stack Trace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Verto_Form_Submission__c/Verto_Form_Submission__c.object-meta.xml
<CustomObject>
    <description>Form submissions from guest site pages.</description>
    <label>Verto Form Submission</label>
    <nameField>
        <displayFormat>Verto Form-{0000000}</displayFormat>
        <label>Form Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verto Form Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Verto_Form_Submission__c/fields/Acknowledgement_Date__c.field-meta.xml
<CustomField>
    <fullName>Acknowledgement_Date__c</fullName>
    <label>Acknowledgement Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Verto_Form_Submission__c/fields/Acknowledgement_Type__c.field-meta.xml
<CustomField>
    <fullName>Acknowledgement_Type__c</fullName>
    <inlineHelpText>Specific details about what the submitter acknowledged.</inlineHelpText>
    <label>Acknowledgement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>It is my responsibility to have a valid travel document to travel by air to Hawaii.</fullName>
            </value>
            <value>
                <fullName>It is my responsibility to obtain legal documentation required for travel.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Verto_Form_Submission__c/fields/Enrollment_Record__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrollment Record</label>
    <referenceTo>Enrollment_Record__c</referenceTo>
    <relationshipLabel>Verto Form Submissions</relationshipLabel>
    <relationshipName>Verto_Form_Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Verto_Form_Submission__c/fields/Legal_Document_Issuing_Country__c.field-meta.xml
<CustomField>
    <fullName>Legal_Document_Issuing_Country__c</fullName>
    <label>Legal Document Issuing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Verto_Form_Submission__c/fields/Legal_Document_Sex__c.field-meta.xml
<CustomField>
    <fullName>Legal_Document_Sex__c</fullName>
    <label>Legal Document Sex</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Verto_Form_Submission__c/fields/New_or_Renewing_Passport__c.field-meta.xml
<CustomField>
    <fullName>New_or_Renewing_Passport__c</fullName>
    <label>New or Renewing Passport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Passport</fullName>
            </value>
            <value>
                <fullName>Renewing Passport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Verto_Form_Submission__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of Verto Form Submission. Used for differentiating small differences in larger overall archetypes. Such as a full legal document compared to just an application being submitted.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Verto_Form_Submission__c/recordTypes/Passport.recordType-meta.xml
<RecordType>
    <fullName>Passport</fullName>
    <active>true</active>
    <label>Passport</label>
</RecordType>

unpackaged/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <customValue>
        <fullName>Costa Rica</fullName>
    </customValue>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/VertoPassportUploadController.cls
/**
 * @description       : The Apex Controller for the VertoPassportUpload page. Facilitates the form submission and owner notification processes.
 * @author            : NickHolly
 * @last modified on  : 02-18-2022
 * @last modified by  : NickHolly
**/
public with sharing class VertoPassportUploadController {
    
    public Verto_Form_Submission__c record {get;set;}
    /* private Id recordId {get;set;}
    private Id recordOwner {get;set;} */
    private Enrollment_Record__c enrollmentRecord {get;set;}
    public transient String fileName {get;set;}
    public transient Blob fileData {get;set;}
    public transient String fileContentType {get;set;}
    public transient String validPassport {get;set;}
    public transient String program {get;set;}
    public Boolean showThankYou {get;set;}
    public Boolean showError {get;set;}
    public String ref {get;set;}

    public VertoPassportUploadController(ApexPages.StandardController controller) {
        Map<String, String> parameters = ApexPages.currentPage().getParameters();
        if(parameters.containsKey('aid') && parameters.containsKey('program')) {
            String aid = String.escapeSingleQuotes(parameters.get('aid')).escapeHtml4();
            String program = String.escapeSingleQuotes(parameters.get('program')).escapeHtml4();
            try {
                System.debug('aid: ' + aid + ' program: ' + program);
                this.enrollmentRecord =  VertoPassportUploadHelperWS.getEnrollmentRecord(
                    Id.valueOf(aid),
                    Id.valueOf(program)
                );
                System.debug(enrollmentRecord);
            } catch (Exception e) {
                showError = true;
            }
        }
        showThankYou = parameters.containsKey('ThankYou');
        if (parameters.get('status') == 'error' || parameters.containsKey('Error')) {
            showError = true;
        } else {
            showError = false;
        }
        if(parameters.containsKey('ref')) {
            ref = parameters.get('ref');
        }
        record = new Verto_Form_Submission__c(
            RecordTypeId = Schema.sObjectType.Verto_Form_Submission__c.getRecordTypeInfosByName().get('Passport').getRecordTypeId()
        );
    }


    public PageReference cancelSubmission() {
        return Page.VertoPassportUpload.setRedirect(true);
    }

    /**
    * @description Attempts to insert the Verto_Form_Submission__c record into the database. Returns a PageReference that will render either a Thank You or Error page after execution.
    * @author NickHolly | 10-15-2021 
    * @return PageReference A PageReference with parameters set to render the Thank You or Error component, depending on result of the actions.
    **/
    @SuppressWarnings('PMD.ApexCRUDViolation')
    public PageReference submitInformation() {
        PageReference sitePage = Page.VertoPassportUpload;
        try {
            //Fill in the information that won't be collected from the form, if available.
            if(enrollmentRecord?.Id != null & enrollmentRecord?.Owner__c != null) {
                record.Enrollment_Record__c = enrollmentRecord.Id;
                record.OwnerId = enrollmentRecord?.Owner__c;
            }
            record.Acknowledgement_Date__c = System.today();
            record.Acknowledgement_Type__c = (program == 'Hawaii') ? 'It is my responsibility to have a valid travel document to travel by air to Hawaii.' : 'It is my responsibility to obtain legal documentation required for travel.';
            if(validPassport == 'Yes') {
                record.Type__c = 'Passport';
                sitePage.getParameters().put('ref','Passport');
            } else {
                record.Type__c = 'Application';
                sitePage.getParameters().put('ref','PassportApplication');
            }
            if(Schema.SObjectType.Verto_Form_Submission__c.isCreateable()) {
                record = (Verto_Form_Submission__c)VertoPassportUploadHelperWS.insertRecord(record);
            }
            if(fileData != null) {
                ContentVersion file = new ContentVersion(
                    VersionData = fileData,
                    Title = validPassport == 'Yes' ? 'Student Passport' : 'Student Passport Application Proof',
                    Guest_Site_fileupload__c = record.Id,
                    PathOnClient = fileName
                );
                if(Schema.SObjectType.ContentVersion.isCreateable()){
                    insert file;
                }
            }
            sitePage.getParameters().put('ThankYou','');
            sitePage.getParameters().put('ref', validPassport == 'Yes' ? 'Passport' : 'PassportApplication');
        } catch (Exception e) {
            Unhandled_Exception__c unhandledException = new Unhandled_Exception__c(
                Stack_Trace__c = e.getStackTraceString(),
                Line_Number__c = e.getLineNumber(),
                Message__c = e.getMessage(),
                Exception_Type__c = e.getTypeName(),
                Object_Data__c = JSON.serialize(record)
            );
            insert unhandledException;
            sitePage.getParameters().put('status','error');
        }
        sitePage.setRedirect(true);
        return sitePage;
    }

    /**
    * @description Invokes a Flow running within a System context to notify the Owner of the Enrollment Record.
    * @author NickHolly | 10-15-2021 
    * @return PageReference A PageReference with parameters set to render the Thank You or Error component, depending on result of the actions.
    **/
    public PageReference notifyRecordOwner() {
        PageReference page = Page.VertoPassportUpload;
        try {
            Map<String, Id> recordIds = new Map<String, Id>{'RecordId' => enrollmentRecord.Id};
            Flow.Interview.Passport_Upload_Notify_SOA notificationFlow = new Flow.Interview.Passport_Upload_Notify_SOA(recordIds);
            notificationFlow.start();
            page.getParameters().put('ThankYou','');
            page.getParameters().put('ref','Notify');
        } catch (Exception e) {
            Unhandled_Exception__c unhandledException = new Unhandled_Exception__c(
                Stack_Trace__c = e.getStackTraceString(),
                Line_Number__c = e.getLineNumber(),
                Message__c = e.getMessage(),
                Exception_Type__c = e.getTypeName(),
                Object_Data__c = JSON.serialize(record) + '\n Record Id:' + enrollmentRecord?.Id
            );
            insert unhandledException;
            page.getParameters().put('status','error');
        }
        page.setRedirect(true);
        return page;
    }

    /**
    * @description Getter for the yesOrNo variable.
    * @author NickHolly | 10-15-2021 
    * @return List<SelectOption> 
    **/
    public List<SelectOption> getYesOrNo() {
        return new List<SelectOption>{
            new SelectOption('',''), 
            new SelectOption('Yes','Yes'), 
            new SelectOption('No','No')
        };
    }

    /**
    * @description Getter for the countries variable.
    * @author NickHolly | 10-15-2021 
    * @return List<SelectOption> List values of valid Countries. Populated from the global country picklist.
    **/
    public List<SelectOption> getCountries() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('',''));
        options.add(new SelectOption('United States', 'United States'));
        for(Schema.PicklistEntry pickval :Verto_Form_Submission__c.Legal_Document_Issuing_Country__c.getDescribe().getPicklistValues()) {
            if(pickval.value != 'United States') {
                options.add(new SelectOption(pickval.getValue(), pickval.getLabel()));
            }
        }
        return options;
    }

    /**
    * @description Getter for the newOrRecurring variable.
    * @author NickHolly | 10-15-2021 
    * @return List<SelectOption> List values of Passport Application options. Populated from the Verto_Form_Submission__c.New_or_Renewing_Passport__c picklist field.
    **/
    public List<SelectOption> getNewOrRenewing() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('',''));
        for(Schema.PicklistEntry pickval :Verto_Form_Submission__c.New_or_Renewing_Passport__c.getDescribe().getPicklistValues()) {
            options.add(new SelectOption(pickval.getValue(), pickval.getLabel()));
        }
        return options;
    }

    /**
    * @description Getter for program variable.
    * @author NickHolly | 10-15-2021 
    * @return List<SelectOption> List values of valid Programs. Currently hardcoded.
    **/
    public List<SelectOption> getPrograms() {
        return new List<SelectOption>{
            new SelectOption('',''),
            new SelectOption('Buenos Aires','Buenos Aires'),
            new SelectOption('Costa Rica','Costa Rica'),
            new SelectOption('Dublin','Dublin'),
            new SelectOption('Florence','Florence'),
            /* new SelectOption('Hawaii','Hawaii'), */
            new SelectOption('London','London'),
            new SelectOption('Prague','Prague'),
            new SelectOption('Seville','Seville')
        };
    }
    
    /**
    * @description Getter for passportSex variable.
    * @author NickHolly | 10-15-2021 
    * @return List<SelectOption>  List values or Passport Sex options. Populated from the Verto_Form_Submission__c.Legal_Document_Sex__c picklist field.
    **/
    public List<SelectOption> getPassportSex() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('',''));
        for(Schema.PicklistEntry pickval :Verto_Form_Submission__c.Legal_Document_Sex__c.getDescribe().getPicklistValues()) {
            if(pickval.getValue() != 'Other') {
                options.add(new SelectOption(pickval.getValue(), pickval.getLabel()));
            }
        }
        return options;
    }
}