unpackaged/main/default/objects/Account/fields/Counseling__c.field-meta.xml
<CustomField>
    <fullName>Counseling__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Counseling</label>
    <referenceTo>Counseling__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/University.recordType-meta.xml
<RecordType>
    <fullName>University</fullName>
    <active>true</active>
    <description>The default record type for all Universities and Colleges</description>
    <label>University</label>
</RecordType>

unpackaged/main/default/objects/College_Application__c/College_Application__c.object-meta.xml
<CustomObject>
    <label>College Application</label>
    <nameField>
        <label>College Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>College Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/College_Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Student Action Needed</fullName>
            </value>
            <value>
                <fullName>Review Complete</fullName>
            </value>
            <value>
                <fullName>Sent to University</fullName>
            </value>
            <value>
                <fullName>Student Applied Pre-Verto</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/College_Application__c/fields/Counseling__c.field-meta.xml
<CustomField>
    <fullName>Counseling__c</fullName>
    <label>Counseling</label>
    <referenceTo>Counseling__c</referenceTo>
    <relationshipLabel>College Applications</relationshipLabel>
    <relationshipName>College_Applications</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/College_Application__c/fields/University__c.field-meta.xml
<CustomField>
    <fullName>University__c</fullName>
    <label>University</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You can only use this field to associate University Accounts</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>University</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>College Applications</relationshipLabel>
    <relationshipName>College_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/University.recordType-meta.xml
<RecordType>
    <fullName>University</fullName>
    <active>true</active>
    <description>Default Record Type for University Contacts</description>
    <label>University</label>
</RecordType>

unpackaged/main/default/objects/Counseling__c/Counseling__c.object-meta.xml
<CustomObject>
    <label>Counseling</label>
    <nameField>
        <label>Counseling Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counseling</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/CollegeAppTriggerHandler.cls
public without sharing class CollegeAppTriggerHandler {

    public static void doAfterInsert(List<College_Application__c> collegeApps) {
        shareWithPartner(collegeApps);
    }

    public static void doAfterUpdate(List<College_Application__c> collegeApps, Map<Id, College_Application__c> oldcollegeApps) {
        List<College_Application__c> recordsToShare = new List<College_Application__c>();
        for (College_Application__c application :collegeApps) {
            if (application.Application_Status__c == 'Sent To University' && application.Application_Status__c != oldcollegeApps.get(application.Id).Application_Status__c) {
                recordsToShare.add(application);
            }
        }
        shareWithPartner(recordsToShare);
    }
    
    public static void shareWithPartner(List<College_Application__c> collegeApps) {
        
        List<Counseling__Share> counselingShares = new List<Counseling__Share>();
        List<AccountShare> accountShares = new List<AccountShare>();
        Set<Id> universityIds = new Set<Id>();
        Map<Id, List<User>> universityUsers = new Map<Id, List<User>>();
        
        for (College_Application__c foundCollegeApps : collegeApps) {
            universityIds.add(foundCollegeApps.University__c);     
        }

        Map<Id, Contact> universityContacts = new Map<Id, Contact>([
            SELECT Id, AccountId
            FROM Contact
            WHERE AccountId IN :universityIds
            AND Account.isPartner = true
        ]);

        for (User contactUser :[SELECT Id, ContactId FROM User WHERE ContactId IN :universityContacts.keySet() AND IsActive = true]) {
            if (universityUsers.containsKey(universityContacts.get(contactUser.ContactId).AccountId)) {
                universityUsers.get(universityContacts.get(contactUser.ContactId).AccountId).add(contactUser);
            } else {
                universityUsers.put(universityContacts.get(contactUser.ContactId).AccountId, new List<User>{contactUser});
            }
        }

        for(College_Application__c collegeApp : collegeApps){
            
            // College Application has to be submit to university
            if(collegeApp.Application_Status__c != 'Sent To University'){
                continue;
            }
            String counselingToShare = collegeApp.Counseling__c;
            String universityToShareTo = collegeApp.University__c;
            
            
            // check if account has users
            if(!universityUsers.containsKey(collegeApp.University__c)){
                continue;
            }
            
            for (User foundUniversityUser : universityUsers.get(collegeApp.University__c)) {

                counselingShares.add(new Counseling__Share(
                    ParentId = counselingToShare, 
                    AccessLevel = 'Edit',
                    UserOrGroupId = foundUniversityUser.Id
                ));
                    
                accountShares.add(new AccountShare(
                    AccountId = universityToShareTo,
                    AccountAccessLevel = 'Edit',
                    OpportunityAccessLevel = 'Edit',
                    UserOrGroupId = foundUniversityUser.Id
                ));

            }
        }
              

        if (!counselingShares.isEmpty()) {
            List<Database.SaveResult> results = Database.insert(counselingShares, false);
            for (Database.SaveResult result : results) {
                if (!result.isSuccess()) {
                    System.debug(result.getErrors());
                }
            }
        }
        if (!accountShares.isEmpty()) {
            List<Database.SaveResult> results = Database.insert(accountShares, false);
            for (Database.SaveResult result : results) {
                if (!result.isSuccess()) {
                    System.debug(result.getErrors());
                }
            }
        }
        
        
    }
}