unpackaged/main/default/objects/Account/fields/Counseling__c.field-meta.xml
<CustomField>
    <fullName>Counseling__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Counseling</label>
    <referenceTo>Counseling__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <label>Persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>US High School Student</fullName>
            </value>
            <value>
                <fullName>International High School Student</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>High School Guidance Counselor</fullName>
            </value>
            <value>
                <fullName>Independent Educational Consultant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/University.recordType-meta.xml
<RecordType>
    <fullName>University</fullName>
    <active>true</active>
    <description>The default record type for all Universities and Colleges</description>
    <label>University</label>
</RecordType>

unpackaged/main/default/objects/College_Application__c/College_Application__c.object-meta.xml
<CustomObject>
    <label>College Application</label>
    <nameField>
        <label>College Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>College Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/College_Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Student Action Needed</fullName>
            </value>
            <value>
                <fullName>Review Complete</fullName>
            </value>
            <value>
                <fullName>Sent to University</fullName>
            </value>
            <value>
                <fullName>Student Applied Pre-Verto</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/College_Application__c/fields/Counseling__c.field-meta.xml
<CustomField>
    <fullName>Counseling__c</fullName>
    <label>Counseling</label>
    <referenceTo>Counseling__c</referenceTo>
    <relationshipLabel>College Applications</relationshipLabel>
    <relationshipName>College_Applications</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/College_Application__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>College Applications</relationshipLabel>
    <relationshipName>College_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/College_Application__c/fields/University__c.field-meta.xml
<CustomField>
    <fullName>University__c</fullName>
    <label>University</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You can only use this field to associate University Accounts</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>University</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>College Applications</relationshipLabel>
    <relationshipName>College_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>x_First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <label>Persona</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>US High School Student</fullName>
            </value>
            <value>
                <fullName>International High School Student</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>High School Guidance Counselor</fullName>
            </value>
            <value>
                <fullName>Independent Educational Consultant</fullName>
            </value>
            <value>
                <fullName>Verto University Partner</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Program Director</fullName>
            </value>
            <value>
                <fullName>SLC</fullName>
            </value>
            <value>
                <fullName>ASC</fullName>
            </value>
            <value>
                <fullName>Faculty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SF_ID18_User__c.field-meta.xml
<CustomField>
    <fullName>SF_ID18_User__c</fullName>
    <label>SF_ID18_User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/University.recordType-meta.xml
<RecordType>
    <fullName>University</fullName>
    <active>true</active>
    <description>Default Record Type for University Contacts</description>
    <label>University</label>
</RecordType>

unpackaged/main/default/objects/Counseling__c/Counseling__c.object-meta.xml
<CustomObject>
    <label>Counseling</label>
    <nameField>
        <label>Counseling Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counseling</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Opportunity/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <label>x_Persona</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>US High School Student</fullName>
            </value>
            <value>
                <fullName>International High School Student</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <label>Phone Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/SF_ID18_User__c.field-meta.xml
<CustomField>
    <fullName>SF_ID18_User__c</fullName>
    <formula>CASESAFEID(Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SF_ID18_User</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CollegeAppTriggerHandlerTestClass.cls
@isTest(SeeAllData=false)
public class CollegeAppTriggerHandlerTestClass{

    @isTest
    static void CollegeAppTriggerHandler(){
        Account acc = new Account();
        acc.recordtypeid = System.Label.RT_Account_Partner;
        acc.First_Name__c = 'firstNametestData';
        acc.Last_Name__c = 'lastName';
        acc.Name = 'name';
        
        insert acc;
        Account accId = [select id from account where First_Name__c = 'firstNametestData' limit 1];
        
        Opportunity opp = new Opportunity();
        opp.recordtypeid = System.Label.RT_Opp_TraditionalEnrollment;
        //This can be set using: opp.RecordTypeId = Schema.sObjectType.Opportunity.getRecordTypeInfosByName().get('Channel Enrollment').getRecordTypeId();
        opp.name = 'oppNametestData';
        opp.accountid = accId.id;
        opp.stagename = 'Qualified';
        opp.closedate = date.today();
        opp.phone_number__c = 'phonetestnumber';

        
        insert opp;
        
        Opportunity oppId = [select id from opportunity where phone_number__c = 'phonetestnumber' limit 1];
        
        Account accUni = new Account();
        accUni.recordtypeid = System.Label.RT_Account_Partner;
        accUni.First_Name__c = 'firstNametestDataUni';
        accUni.Last_Name__c = 'lastName';
        accUni.name = 'name';
        
        insert accUni;
        Account accIdUni = [select id from account where First_Name__c = 'firstNametestDataUni' limit 1];
        
        Contact uniContact = new Contact();
        uniContact.recordtypeid = System.Label.RT_Contact_University;
        uniContact.lastname = 'lastNametestDataUniContact';
        uniContact.accountid = accIdUni.id;
        uniContact.persona__c = 'Verto University Partner';
        
        insert uniContact;
        Contact partnerContact = [select id from contact where lastname = 'lastNametestDataUniContact' limit 1];
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Partner Community User - Verto'];
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='123stan123darduser@123testorg.com');
        u.contactId = partnerContact.id;
        insert u;
        
        User partnerUser = [select id from user where UserName = '123stan123darduser@123testorg.com' limit 1];
        partnerContact.SF_ID18_User__c = partnerUser.id;
        update partnerContact;
        
        Counseling__c sampleCounselingRecord = new Counseling__c();
        insert sampleCounselingRecord;

        College_Application__c cApp = new College_Application__c();
        cApp.opportunity__c = oppId.id;
        cApp.university__c = accIdUni.id;
        cApp.Counseling__c = sampleCounselingRecord.Id;
        /* cApp.Application_Status__c = 'Sent To University'; */
        
        insert cApp;

        cApp.Application_Status__c = 'Sent To University';
        update cApp;
        
    }
}