unpackaged/main/default/objects/Account/fields/Interest_Level__c.field-meta.xml
<CustomField>
    <fullName>Interest_Level__c</fullName>
    <label>z_Interest Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/University.recordType-meta.xml
<RecordType>
    <fullName>University</fullName>
    <active>true</active>
    <description>The default record type for all Universities and Colleges</description>
    <label>University</label>
</RecordType>

unpackaged/main/default/objects/Enrollment_Record__c/Enrollment_Record__c.object-meta.xml
<CustomObject>
    <label>Enrollment Record</label>
    <nameField>
        <displayFormat>EN-{00000000}</displayFormat>
        <label>Enrollment Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Interest_Level__c.field-meta.xml
<CustomField>
    <fullName>Interest_Level__c</fullName>
    <label>Interest Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Enrollment Records</relationshipLabel>
    <relationshipName>Enrollment_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Program__c.Location__r.Id</field>
            <operation>notEqual</operation>
            <value>a1G3h000000i2EQ</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Enrollment Records</relationshipLabel>
    <relationshipName>Enrollment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Program_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Program_End_Date__c</fullName>
    <formula>Program__r.Program_End_Date__c</formula>
    <label>Program End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Program_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Program_Start_Date__c</fullName>
    <description>This field was created for use in Five9 auto-dial campaigns.</description>
    <formula>Program__r.Program_Start_Date__c</formula>
    <label>Program Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Enrollment_Record__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrollment Record</label>
    <referenceTo>Enrollment_Record__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Program__c/fields/Program_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Program_End_Date__c</fullName>
    <description>Semester end date handled at the program level. Typically handled by Akilah or a Salesforce Admin.</description>
    <label>Program End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Program__c/fields/Program_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Program_Start_Date__c</fullName>
    <description>Semester start date, but handled per program. This is typically maintained by Akilah or another Salesforce Admin.</description>
    <label>Program Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Override_Workflow__c.field-meta.xml
<CustomField>
    <fullName>Override_Workflow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Override Workflow</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/Five9LSP_enrollment_record_Trigger_Test.cls
/*
 * This is the test class for "Five9LSP_enrollment_record_Trigger" apex class.
 * Created on:11-02-2022
 */
@isTest
public class Five9LSP_enrollment_record_Trigger_Test {
    
    @testSetup static void testSetupData() {
        
        Profile p 	= [SELECT Id FROM Profile WHERE Name='Standard User'];
        User u 		= new User(
            					Alias = 'standt', 
            					Email='standarduser@testorg.com', 
                               	EmailEncodingKey='UTF-8', 
            					LastName='Testing', 
            					LanguageLocaleKey='en_US', 
                               	LocaleSidKey='en_US', 
            					ProfileId = p.Id, 
                               	TimeZoneSidKey='America/Los_Angeles', 
            					UserName='standarduser@testorg.com'+System.now().millisecond(),
                               	Override_Workflow__c = true
        					);
        insert u;  
        
    }//end:testSetupData()    
	
    @isTest
    public static void testInsert(){
               
        User usr = [SELECT Id FROM User WHERE email = 'standarduser@testorg.com'];

    	System.runAs(usr) { 
            
         	Id recordTypeId = [SELECT Id FROM RecordType
    							WHERE DeveloperName = 'University' AND sObjectType = 'Account'].Id;  
            // Create a test account
            Account testAcct = new Account (
                							Name = 'Test Account'+System.now().millisecond(),
                                            RecordTypeId = recordTypeId, website='Test.com'
            								);
            insert testAcct;
            
            Program__c testProg = new Program__c(
                									Name='London - Fall 2022'+System.now().millisecond(),
                                                    Program_Start_Date__c = System.today().addDays(-5),
                                                    Program_End_Date__c = System.today().addDays(10)
            									);
            insert testProg;
            
            // Creates first opportunity
            Opportunity testOppt = new Opportunity(
                									Name ='New mAWS Deal'+System.now().millisecond(),
                                               		AccountID = testAcct.Id,
                                               		StageName = 'Customer Won',
                                               		Amount = 3000,
                                               		CloseDate = System.today()
            									);
            
            insert testOppt;
                       
            Enrollment_Record__c testEnroll = new Enrollment_Record__c(
                                                                       Opportunity__c = testOppt.Id,
            														   Program__c = testProg.Id            
            														);
            insert testEnroll;
        }

    }//end:testInsert()
    
    @isTest
    public static void testUpdate(){
        
        User usr = [SELECT Id FROM User WHERE email = 'standarduser@testorg.com'];

    	System.runAs(usr) {
            
           Id recordTypeId = [SELECT Id FROM RecordType
    							WHERE DeveloperName = 'University' AND sObjectType = 'Account'].Id;   
                                
            // Create a test account
            Account testAcct = new Account (
                							Name = 'Test Account'+System.now().millisecond(),
                                            RecordTypeId = recordTypeId, website='Test.com'
            								);
            insert testAcct;
            
            Program__c testProg = new Program__c(
                									Name='London - Fall 2022'+System.now().millisecond(),
                                                    Program_Start_Date__c = System.today().addDays(-5),
                                                    Program_End_Date__c = System.today().addDays(10)
            									);
            insert testProg;
            
            // Creates first opportunity
            Opportunity testOppt = new Opportunity(
                									Name ='New mAWS Deal'+System.now().millisecond(),
                                               		AccountID = testAcct.Id,
                                               		StageName = 'Customer Won',
                                               		Amount = 3000,
                                               		CloseDate = System.today()
            									);
            
            insert testOppt;            
                       
            Enrollment_Record__c testEnroll = new Enrollment_Record__c(
                                                                       Opportunity__c = testOppt.Id,
            														   Program__c = testProg.Id);
            insert testEnroll;
            
            if(!String.isEmpty(testEnroll.Id)){
                
                testEnroll.Interest_Level__c = '1';
                update testEnroll;
                
                delete testEnroll;
            }
            
        }
    }//end: testUpdate()
}