unpackaged/main/default/objects/Account/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <label>Persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>US High School Student</fullName>
            </value>
            <value>
                <fullName>International High School Student</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>High School Guidance Counselor</fullName>
            </value>
            <value>
                <fullName>Independent Educational Consultant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Student applications for admission into Verto Education</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a Student Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Student Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <label>Persona</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>US High School Student</fullName>
            </value>
            <value>
                <fullName>International High School Student</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>High School Guidance Counselor</fullName>
            </value>
            <value>
                <fullName>Independent Educational Consultant</fullName>
            </value>
            <value>
                <fullName>Verto University Partner</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Program Director</fullName>
            </value>
            <value>
                <fullName>SLC</fullName>
            </value>
            <value>
                <fullName>ASC</fullName>
            </value>
            <value>
                <fullName>Faculty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Health_Form__c/Health_Form__c.object-meta.xml
<CustomObject>
    <label>Health Form</label>
    <nameField>
        <label>Health Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Health Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Health_Form__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Health Forms</relationshipLabel>
    <relationshipName>Health_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/StaffPortalStudentProfileController.cls
public with sharing class StaffPortalStudentProfileController {

    @AuraEnabled(cacheable=true)
    public static Id getMostRecentHealthFormId(String recordId) {
        if (recordId == null) {
            throw new IllegalArgumentException('Null inputs are not accepted.');
        }
        Id accountId = Id.valueOf(recordId);
        if (String.valueOf(accountId.getSobjectType()) != Account.getSObjectType().getDescribe().getName()) {
            throw new IllegalArgumentException('Invalid type of argument received.');
        }
        try {
            return [
                SELECT Id
                FROM Health_Form__c
                WHERE Account__c = :accountId
                WITH SECURITY_ENFORCED
                ORDER BY CreatedDate DESC
                LIMIT 1
            ]?.Id;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Contact> getParentContactIds(String recordId) {
        if (recordId == null) {
            throw new IllegalArgumentException('Null inputs are not accepted.');
        }
        Id accountId = Id.valueOf(recordId);
        if (String.valueOf(accountId.getSobjectType()) != Account.sObjectType.getDescribe().getName()) {
            throw new IllegalArgumentException('Invalid type of argument received.');
        }
        try {
            return [
                SELECT Id, Name
                FROM Contact
                WHERE AccountId = :accountId
                AND Persona__c = 'Parent'
                WITH SECURITY_ENFORCED
            ];
        } catch (QueryException e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static Id getMostRecentApplicationId(String recordId) {
        if (recordId == null) {
            throw new IllegalArgumentException('Null inputs are not accepted.');
        }
        Id accountId = Id.valueOf(recordId);
        if (String.valueOf(accountId.getSobjectType()) != Account.getSObjectType().getDescribe().getName()) {
            throw new IllegalArgumentException('Invalid type of argument received.');
        }
        try {
            return [
                SELECT Id
                FROM Application__c
                WHERE Account__c = :accountId
                WITH SECURITY_ENFORCED
                ORDER BY CreatedDate DESC
                LIMIt 1
            ]?.Id;
        } catch (QueryException e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}