unpackaged/main/default/objects/Account/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <label>Persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>US High School Student</fullName>
            </value>
            <value>
                <fullName>International High School Student</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>High School Guidance Counselor</fullName>
            </value>
            <value>
                <fullName>Independent Educational Consultant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/Enrollment_Record__c.object-meta.xml
<CustomObject>
    <label>Enrollment Record</label>
    <nameField>
        <displayFormat>EN-{00000000}</displayFormat>
        <label>Enrollment Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Enrollment_Status__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Status__c</fullName>
    <label>Enrollment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enrolled</fullName>
                <default>true</default>
                <label>Enrolled</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Graduated</fullName>
            </value>
            <value>
                <fullName>Pending Withdrawal</fullName>
            </value>
            <value>
                <fullName>Withdrew</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Dismissed</fullName>
            </value>
            <value>
                <fullName>Verto Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Enrollment Records</relationshipLabel>
    <relationshipName>Enrollment_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Enrollment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Program__c.Location__r.Id</field>
            <operation>notEqual</operation>
            <value>a1G3h000000i2EQ</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Enrollment Records</relationshipLabel>
    <relationshipName>Enrollment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Program_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Program_End_Date__c</fullName>
    <formula>Program__r.Program_End_Date__c</formula>
    <label>Program End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Program_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Program_Start_Date__c</fullName>
    <description>This field was created for use in Five9 auto-dial campaigns.</description>
    <formula>Program__r.Program_Start_Date__c</formula>
    <label>Program Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Student_Account__c.field-meta.xml
<CustomField>
    <fullName>Student_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enrollment Records</relationshipLabel>
    <relationshipName>Enrollment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Location__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Potential/Planning</fullName>
                <default>true</default>
                <label>Potential/Planning</label>
            </value>
            <value>
                <fullName>Actively Enrolling</fullName>
            </value>
            <value>
                <fullName>Not Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Enrollment_Record__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrollment Record</label>
    <referenceTo>Enrollment_Record__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Enrollment_Status__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Status__c</fullName>
    <formula>TEXT(Enrollment_Record__r.Enrollment_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Enrollment Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <label>x_Persona</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>US High School Student</fullName>
            </value>
            <value>
                <fullName>International High School Student</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Tuition_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Tuition_Due_Date__c</fullName>
    <label>Tuition Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Program__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Program__c/fields/Program_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Program_End_Date__c</fullName>
    <description>Semester end date handled at the program level. Typically handled by Akilah or a Salesforce Admin.</description>
    <label>Program End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Program__c/fields/Program_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Program_Start_Date__c</fullName>
    <description>Semester start date, but handled per program. This is typically maintained by Akilah or another Salesforce Admin.</description>
    <label>Program Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Program__c/fields/Semester__c.field-meta.xml
<CustomField>
    <fullName>Semester__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Semester</label>
    <referenceTo>Semester__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Enrolling</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Semester__c/Semester__c.object-meta.xml
<CustomObject>
    <label>Semester</label>
    <nameField>
        <label>Semester Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Semesters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Semester__c/fields/Deposit_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Due_Date__c</fullName>
    <label>Deposit Due Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Semester__c/fields/Semester_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Semester_End_Date__c</fullName>
    <label>Semester End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Semester__c/fields/Semester_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Semester_Start_Date__c</fullName>
    <label>Semester Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Semester__c/fields/Tuition_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Tuition_Due_Date__c</fullName>
    <label>Tuition Due Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/EnrollmentRecordTriggerHandlerTests.cls
@IsTest
public with sharing class EnrollmentRecordTriggerHandlerTests {
    @TestSetup
    static void makeData(){
        insert new Location__c(
            Name = 'Example Location',
            Status__c = 'Actively Enrolling'
        );
        insert new Semester__c(
            Name = 'Sample Semester ' + String.valueOf(System.today().year()),
            Delivery_Method__c = 'Abroad',
            Semester_Start_Date__c = System.today().addDays(10),
            Semester_End_Date__c = System.today().addDays(10).addMonths(3),
            Deposit_Due_Date__c = System.today().addDays(10).addMonths(3),
            Tuition_Due_Date__c = System.today().addDays(-10).addMonths(3)
        );
        insert new Program__c(
            Name = 'Sample Program',
            Program_Start_Date__c = System.today().addDays(10),
            Program_End_Date__c = System.today().addDays(10).addMonths(3),
            Semester__c = [SELECT Id FROM Semester__c LIMIT 1].Id,
            Location__c = [SELECT Id FROM Location__c LIMIT 1].Id
        );
        insert new Account(
            Name = 'Sample Student',
            First_Name__c = 'Sample',
            Last_Name__c = 'Student',
            Phone = '888-888-8888',
            Email__c = 'SampleStudent@Test.org',
            Persona__c = 'US High School Student',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Student Account').getRecordTypeId()
        );
        User limitsUser = new User(
            FirstName = 'Limit',
            LastName = 'User',
            Alias = 'LUser',
            Email = 'LimitUser@Test.org',
            UserName = 'LimitUser@Test.org',
            EmailEncodingKey = 'UTF-8',
            isActive = true,
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1].Id,
            TimeZoneSidKey = 'America/Los_Angeles'
        );
        insert limitsUser;
        System.runAs(limitsUser) {
            insert new PermissionSetAssignment(
                AssigneeId = limitsUser.Id,
                PermissionSetGroupId = [SELECT Id FROM PermissionSetGroup WHERE MasterLabel = 'Digital Product Team' LIMIT 1].Id
            );
        }
    }

    @IsTest
    static void testAfterInsert() {
        User contextUser = [SELECT Id FROM User WHERE UserName = 'LimitUser@Test.org' LIMIT 1];
        System.runAs(contextUser) {
            insertSampleOpportunities(1);
        }
        Test.startTest();
        Enrollment_Record__c sampleEnrollment = getSampleFirstSemester();
        insert sampleEnrollment;
        Test.stopTest();
        System.assertEquals(
            1,
            [SELECT Id FROM Enrollment_Record__c].size(),
            'Expected one successful enrollment record inserted.'
        );
    }
 
    @IsTest
    static void testBulkAfterInsert() {
        User contextUser = [SELECT Id FROM User WHERE UserName = 'LimitUser@Test.org' LIMIT 1];
        List<Enrollment_Record__c> enrollmentRecordsToInsert = new List<Enrollment_Record__c>();
        System.runAs(contextUser) {
            Id studentId = [SELECT Id FROM Account WHERE Name = 'Sample Student' LIMIT 1].Id;
            Id programId = [SELECT Id FROM Program__c LIMIT 1].Id;
            List<Opportunity> parentOpportunities = insertSampleOpportunities(50);
            for (Integer i = 0; i < 50; i++) {
                enrollmentRecordsToInsert.add(getSampleFirstSemester(
                    studentId,
                    parentOpportunities[i].Id,
                    programId
                ));
            }
        }
        Test.startTest();
        insert enrollmentRecordsToInsert;
        Test.stopTest();
        System.assertEquals(
            50,
            [SELECT Id FROM Enrollment_Record__c].size(),
            'Expected 50 successful enrollment records inserted.'
        );
    }

    @IsTest
    static void testBeforeUpdate() {
        insertSampleOpportunities(1);
        Enrollment_Record__c sampleEnrollment = getSampleFirstSemester();
        insert sampleEnrollment;
        Test.startTest();
        sampleEnrollment.Enrollment_Status__c = 'Enrolled';
        update sampleEnrollment;
        Test.stopTest();
        System.assertEquals(
            1,
            [SELECT Id FROM Enrollment_Record__c WHERE Enrollment_Status__c = 'Enrolled'].size(),
            'Expected one successful enrollment record updated.'
        );
    }

    @IsTest
    static void testBulkBeforeUpdate() {
        User contextUser = [SELECT Id FROM User WHERE UserName = 'LimitUser@Test.org' LIMIT 1];
        List<Enrollment_Record__c> enrollmentRecordsToInsert = new List<Enrollment_Record__c>();
        System.runAs(contextUser) {
            Id studentId = [SELECT Id FROM Account WHERE Name = 'Sample Student' LIMIT 1].Id;
            Id programId = [SELECT Id FROM Program__c LIMIT 1].Id;
            List<Opportunity> parentOpportunities = insertSampleOpportunities(50);
            for (Integer i = 0; i < 50; i++) {
                enrollmentRecordsToInsert.add(getSampleFirstSemester(
                    studentId,
                    parentOpportunities[i].Id,
                    programId
                ));
            }
            insert enrollmentRecordsToInsert;
        }
        Test.startTest();
        List<Enrollment_Record__c> enrollmentRecordsToUpdate = [SELECT Id, Enrollment_Status__c FROM ENrollment_Record__c LIMIT 200];
        for (Enrollment_Record__c each : enrollmentRecordsToUpdate) {
            each.Enrollment_Status__c = 'Enrolled';
        }
        update enrollmentRecordsToUpdate;
        Test.stopTest();
        System.assertEquals(
            50,
            [SELECT Id FROM Enrollment_Record__c WHERE Enrollment_Status__c = 'Enrolled'].size(),
            'Expected 50 successful enrollment records updated.'
        );
    }

    private static List<Opportunity> insertSampleOpportunities(Integer count) {
        List<Opportunity> opportunitiesToInsert = new List<Opportunity>();
        Id accountId = [SELECT Id FROM Account WHERE Name = 'Sample Student' LIMIT 1].Id;
        for (Integer i = 0; i < count; i++) {
            opportunitiesToInsert.add(new Opportunity(
                Name = 'Sample Oppportunity',
                AccountId = accountId,
                StageName = 'Qualified',
                CloseDate = System.today(),
                RecordTypeId = Schema.sObjectType.Opportunity.getRecordTypeInfosByName().get('Traditional Enrollment').getRecordTypeId()
            ));
        }
        TriggerHandler.suppressHandler('OpportunityTriggerHandler');
        insert opportunitiesToInsert;
        TriggerHandler.clearSuppressedHandlers();
        return opportunitiesToInsert;
    }

    private static Enrollment_Record__c getSampleFirstSemester() {
        return new Enrollment_Record__c(
            Student_Account__c = [SELECT Id FROM Account WHERE Name = 'Sample Student' LIMIT 1].Id,
            Opportunity__c = [SELECT Id FROM Opportunity LIMIT 1].Id,
            Program__c = [SELECT Id FROM Program__c LIMIT 1].Id,
            Owner__c = System.Label.User_GeneralSalesforceAdmin,
            RecordTypeId = Schema.sObjectType.Enrollment_Record__c.getRecordTypeInfosByName().get('First Semester').getRecordTypeId()
        );
    }

    private static Enrollment_Record__c getSampleFirstSemester(
        Id studentId,
        Id opportunityId,
        Id programId
    ) {
        return new Enrollment_Record__c(
            Student_Account__c = studentId,
            Opportunity__c = opportunityId,
            Program__c = programId,
            Owner__c = System.Label.User_GeneralSalesforceAdmin,
            RecordTypeId = Schema.sObjectType.Enrollment_Record__c.getRecordTypeInfosByName().get('First Semester').getRecordTypeId()
        );
    }
}