unpackaged/main/default/objects/Account/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <label>Persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>US High School Student</fullName>
            </value>
            <value>
                <fullName>International High School Student</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>High School Guidance Counselor</fullName>
            </value>
            <value>
                <fullName>Independent Educational Consultant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>x_First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <label>Persona</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>US High School Student</fullName>
            </value>
            <value>
                <fullName>International High School Student</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>High School Guidance Counselor</fullName>
            </value>
            <value>
                <fullName>Independent Educational Consultant</fullName>
            </value>
            <value>
                <fullName>Verto University Partner</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Program Director</fullName>
            </value>
            <value>
                <fullName>SLC</fullName>
            </value>
            <value>
                <fullName>ASC</fullName>
            </value>
            <value>
                <fullName>Faculty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <label>Student</label>
</RecordType>

unpackaged/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Course__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Active_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/Course_Prerequisite__c.object-meta.xml
<CustomObject>
    <label>Course Prerequisite</label>
    <nameField>
        <displayFormat>PreReq-{0000000}</displayFormat>
        <label>Prerequisite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Prerequisites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Question__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Algebra II</fullName>
            </value>
            <value>
                <fullName>Geometry</fullName>
            </value>
            <value>
                <fullName>Trigonometry</fullName>
            </value>
            <value>
                <fullName>Pre-Calculus</fullName>
            </value>
            <value>
                <fullName>Calculus</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>One Year</fullName>
            </value>
            <value>
                <fullName>Two Years</fullName>
            </value>
            <value>
                <fullName>Three Years</fullName>
            </value>
            <value>
                <fullName>Four Years</fullName>
            </value>
            <value>
                <fullName>B- or Higher</fullName>
            </value>
            <value>
                <fullName>C+ or Lower</fullName>
            </value>
            <value>
                <fullName>Contemporary Math</fullName>
                <isActive>false</isActive>
                <label>Contemporary Math</label>
            </value>
            <value>
                <fullName>Pre-Calculus I</fullName>
                <isActive>false</isActive>
                <label>Pre-Calculus I</label>
            </value>
            <value>
                <fullName>Pre-Calculus II</fullName>
                <isActive>false</isActive>
                <label>Pre-Calculus II</label>
            </value>
            <value>
                <fullName>test</fullName>
                <isActive>false</isActive>
                <label>test</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Prerequisites</relationshipLabel>
    <relationshipName>Course_Prerequisites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <inlineHelpText>Prerequisites of the same group are all required. Prerequisites of different groups are optional.</inlineHelpText>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>A</label>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>What is the students highest level of math completed with a C or greater?</fullName>
            </value>
            <value>
                <fullName>How many years of High School Spanish has the student completed with a C or greater?</fullName>
            </value>
            <value>
                <fullName>What was the students Junior year English grade?</fullName>
            </value>
            <value>
                <fullName>What is the student&#39;s highest level of math completed with a C or greater?</fullName>
                <isActive>false</isActive>
                <label>What is the student&#39;s highest level of math completed with a C or greater?</label>
            </value>
            <value>
                <fullName>What was the student&#39;s Junior year English grade?</fullName>
                <isActive>false</isActive>
                <label>What was the student&#39;s Junior year English grade?</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Course_Subject</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prerequisite</fullName>
                <default>true</default>
                <label>Prerequisite</label>
            </value>
            <value>
                <fullName>Corequisite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/Enrollment_Record__c.object-meta.xml
<CustomObject>
    <label>Enrollment Record</label>
    <nameField>
        <displayFormat>EN-{00000000}</displayFormat>
        <label>Enrollment Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Enrollment Records</relationshipLabel>
    <relationshipName>Enrollment_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Enrollment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Program__c.Location__r.Id</field>
            <operation>notEqual</operation>
            <value>a1G3h000000i2EQ</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Enrollment Records</relationshipLabel>
    <relationshipName>Enrollment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Student_Account__c.field-meta.xml
<CustomField>
    <fullName>Student_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enrollment Records</relationshipLabel>
    <relationshipName>Enrollment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Location__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Potential/Planning</fullName>
                <default>true</default>
                <label>Potential/Planning</label>
            </value>
            <value>
                <fullName>Actively Enrolling</fullName>
            </value>
            <value>
                <fullName>Not Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Enrollment_Record__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrollment Record</label>
    <referenceTo>Enrollment_Record__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <label>x_Persona</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>US High School Student</fullName>
            </value>
            <value>
                <fullName>International High School Student</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Enrolling</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Active_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <description>The status of whether this record is active, inactive, or other.</description>
    <masterLabel>Active Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Course_Subject.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Anthropology</fullName>
    </customValue>
    <customValue>
        <fullName>Art</fullName>
    </customValue>
    <customValue>
        <fullName>Biology</fullName>
    </customValue>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <customValue>
        <fullName>Chemistry</fullName>
    </customValue>
    <customValue>
        <fullName>Communications</fullName>
    </customValue>
    <customValue>
        <fullName>Computer Science</fullName>
    </customValue>
    <customValue>
        <fullName>Economics</fullName>
    </customValue>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>Geography</fullName>
    </customValue>
    <customValue>
        <fullName>Government/Politics</fullName>
    </customValue>
    <customValue>
        <fullName>History</fullName>
    </customValue>
    <customValue>
        <fullName>Mathematics</fullName>
    </customValue>
    <customValue>
        <fullName>Music</fullName>
    </customValue>
    <customValue>
        <fullName>Philosophy</fullName>
    </customValue>
    <customValue>
        <fullName>Project Management</fullName>
    </customValue>
    <customValue>
        <fullName>Psychology</fullName>
    </customValue>
    <customValue>
        <fullName>Religion</fullName>
    </customValue>
    <customValue>
        <fullName>Science</fullName>
    </customValue>
    <customValue>
        <fullName>Sociology</fullName>
    </customValue>
    <customValue>
        <fullName>Spanish</fullName>
    </customValue>
    <customValue>
        <fullName>Theater</fullName>
    </customValue>
    <masterLabel>Course Subject</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/TestDataFactory.cls
@IsTest
public with sharing class TestDataFactory {
    
    public static void insertMockCommunityUser() {
        Id communityProfileId = [
            SELECT Id
            FROM Profile
            WHERE Name = 'Student Portal User'
            LIMIT 1
        ].Id;
        Account communityUserAccount = new Account(
            Name = 'Community User',
            First_Name__c = 'Community',
            Last_Name__c = 'User',
            Email__c = 'CommunityUser@Test.org',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Student Account').getRecordTypeId()
        );
        insert communityUserAccount;
        Contact communityUserContact = new Contact(
            AccountId = communityUserAccount.Id,
            FirstName = 'Community',
            LastName = 'User',
            Email = 'CommunityUser@Test.org',
            Persona__c = 'US High School Student',
            RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Student').getRecordTypeId()
        );
        insert communityUserContact;
        insert new User(
            FirstName = 'Commmunity',
            LastName = 'User',
            Email = 'CommunityUser@Test.org',
            ContactId = communityUserContact.Id,
            ProfileId = communityProfileId,
            Username = 'CommunityUser@Test.org',
            Alias = 'CommUser',
            CommunityNickname = 'Community User',
            TimeZoneSidKey = 'America/Chicago',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US'
        );
    }

    /* public static void insertMockPartnerUser() {

    } */

    public static void insertOpportunityAndEnrollmentForAccount(Account account) {
        if ([SELECT Id FROM Program__c].isEmpty()) {
            insertMockPrograms();
        }
        Opportunity firstSemesterOpportunity = new Opportunity(
            Name = account.Name + ' - ' + System.today().addMonths(-3),
            AccountId = account.Id,
            StageName = 'Qualified',
            CloseDate = System.today().addMonths(-3),
            RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Traditional Enrollment').getRecordTypeId()
        );
        insert firstSemesterOpportunity;
        insert new Enrollment_Record__c(
            Student_Account__c = account.Id,
            Opportunity__c = firstSemesterOpportunity.Id,
            Program__c = [SELECT Id FROM Program__c LIMIT 1].Id,
            Owner__c = System.Label.User_GeneralSalesforceAdmin,
            RecordTypeId = Schema.sObjectType.Enrollment_Record__c.getRecordTypeInfosByName().get('First Semester').getRecordTypeId()
        );
    }

    public static void insertMockCoursesWithPrerequisites() {
        Course__c sampleCourse = new Course__c(
            Name = 'Sample Course',
            Description__c = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
            Subject__c = 'Mathematics',
            Status__c = 'Active'
        );
        Course__c sampleCorequisiteCourse = new Course__c(
            Name = 'Sample Corequisite Course',
            Subject__c = 'Mathematics',
            Status__c = 'Active'
        );
        insert new List<Course__c>{sampleCourse, sampleCorequisiteCourse};
        List<Course_Prerequisite__c> prerequisites = new List<Course_Prerequisite__c>();
        prerequisites.add( new Course_Prerequisite__c(
            Course__c = sampleCourse.Id,
            Question__c = 'What is the students highest level of math completed with a C or greater?',
            Condition__c = 'Algebra II',
            Group__c = 'A',
            Type__c = 'Prerequisite'
        ));
        prerequisites.add( new Course_Prerequisite__c(
            Course__c = sampleCourse.Id,
            Question__c = 'What is the students highest level of math completed with a C or greater?',
            Condition__c = 'Geometry',
            Group__c = 'B',
            Type__c = 'Prerequisite'
        ));
        prerequisites.add( new Course_Prerequisite__c(
            Course__c = sampleCourse.Id,
            Type__c = 'Corequisite',
            Corequisite_Course__c = sampleCorequisiteCourse.Id
        ));
        insert prerequisites;
    }

    public static void insertMockPrograms() {
        Semester__c semester = new Semester__c(
            Name = 'Fall ' + System.today().year(),
            Delivery_Method__c = 'Abroad',
            Semester_Start_Date__c = System.today().addDays(10),
            Semester_End_Date__c = System.today().addDays(10).addMonths(3),
            Deposit_Due_Date__c = System.today().addDays(10).addMonths(3),
            Tuition_Due_Date__c = System.today().addDays(-10).addMonths(3)
        );
        insert semester;
        List<Location__c> locations = new List<Location__c>();
        locations.add(new Location__c(
            Name = 'England',
            Status__c = 'Actively Enrolling'
        ));
        locations.add(new Location__c(
            Name = 'Costa Rica',
            Status__c = 'Actively Enrolling'
        ));
        locations.add(new Location__c(
        	Name = 'Buenos Aires',
            Status__c = 'Actively Enrolling'
        ));
        insert locations;
        List<Program__c> programs = new List<Program__c>();
        for (Location__c location :locations) {
            programs.add(new Program__c(
                Name = location.Name + ' - ' + semester.Name,
                Semester__c = semester.Id,
                Location__c = location.Id,
                Status__c = 'Active',
                Program_Start_Date__c = System.today(),
                Program_End_Date__c = System.today().addMonths(3)
            ));
        }
        insert programs;
    }

}