unpackaged/main/default/objects/Account/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <label>Persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>US High School Student</fullName>
            </value>
            <value>
                <fullName>International High School Student</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>High School Guidance Counselor</fullName>
            </value>
            <value>
                <fullName>Independent Educational Consultant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CIO_Integration_Setting__mdt/CIO_Integration_Setting__mdt.object-meta.xml
<CustomObject>
    <label>CIO Integration Setting</label>
    <pluralLabel>CIO Integration Settings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Opportunity/fields/Current_Program__c.field-meta.xml
<CustomField>
    <fullName>Current_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Represents what program the student is currently in. After closed won, this field can only be edited via automation when the corresponding field is updated on the enrollment record.</description>
    <label>Current Program</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Program__c.Location__r.Name</field>
            <operation>notEqual</operation>
            <value>UNDECIDED</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Opportunities (Current Program)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Enrollment_Agreement_Signed_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Agreement_Signed_Date_Time__c</fullName>
    <label>Enrollment Agreement Signed Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Family_Interview_Booked_Date__c.field-meta.xml
<CustomField>
    <fullName>Family_Interview_Booked_Date__c</fullName>
    <inlineHelpText>The date that the Family Admissions Call is booked. This is not the date that the call takes place on.</inlineHelpText>
    <label>Family Admissions Call Booked Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <label>x_Persona</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>US High School Student</fullName>
            </value>
            <value>
                <fullName>International High School Student</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CioIntegrationServicesTests.cls
@IsTest
public with sharing class CioIntegrationServicesTests {

    @TestSetup
    static void makeData(){
        insert new Account(
            Name = 'Sample Student',
            First_Name__c = 'Sample',
            Last_Name__c = 'Student',
            Phone = '888-888-8888',
            Email__c = 'SampleStudent@Test.org',
            Persona__c = 'US High School Student',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Student Account').getRecordTypeId()
        );
        insert new Opportunity(
            Name = 'Sample Oppportunity',
            AccountId = [SELECT Id FROM Account WHERE Name = 'Sample Student' LIMIT 1].Id,
            StageName = 'Qualified',
            CloseDate = System.today(),
            RecordTypeId = Schema.sObjectType.Opportunity.getRecordTypeInfosByName().get('Traditional Enrollment').getRecordTypeId()
        );
    }
    
    @IsTest
    static void testSyncRecords() {
        Boolean exceptionThrown = false;
        String exceptionMessage;
        Test.startTest();
        Opportunity oldOpp = [
            SELECT Id, StageName, Current_Program__c, Family_Interview_Booked_Date__c,
            Deposit_Date__c, Enrollment_Agreement_Signed_Date_Time__c, OwnerId
            FROM Opportunity 
            LIMIT 1
        ];
        Opportunity newOpp = oldOpp.clone(true, true, true);
        newOpp.StageName = 'Family Admissions Calls';
        try {
            CioIntegrationServices.syncRecords(
                getSampleIntegrationSetting(),
                new Map<Id, SObject>(new List<Opportunity>{oldOpp}),
                new Map<Id, SObject>(new List<Opportunity>{newOpp})
            );
        } catch (Exception e) {
            exceptionMessage = e.getMessage();
            exceptionThrown = true;
        }
        Test.stopTest();
        System.assertEquals(
            null,
            exceptionMessage,
            'Expected no exception message.'
        );
        System.assertEquals(
            false,
            exceptionThrown,
            'Expected no exceptions to be thrown.'
        );
    }


    @IsTest
    static void testGetIntegrationSyncRequired() {
        Test.startTest();
        Boolean integrationSyncRequired;
        Opportunity oldOpp = [
            SELECT Id, StageName, Current_Program__c, Family_Interview_Booked_Date__c,
            Deposit_Date__c, Enrollment_Agreement_Signed_Date_Time__c 
            FROM Opportunity 
            LIMIT 1
        ];
        Opportunity newOpp = oldOpp.clone(true, true, true);
        newOpp.StageName = 'Family Admissions Calls';
        integrationSyncRequired = CioIntegrationServices.getIntegrationSyncRequired(
            (SObject)oldOpp,
            (SObject)newOpp,
            'Current_Program__c,StageName'
        );
        System.assertEquals(
            true,
            integrationSyncRequired,
            'Expected integration sync required to be true.'
        );
    }

    @IsTest
    static void testGetFieldsToWatch() {
        
    }

    @IsTest
    static void testGetQueryResults() {

    }

    @IsTest
    static void testGetPayload() {

    }

    @IsTest
    static void testGetEmail() {

    }

    private static CIO_Integration_Setting__mdt getSampleIntegrationSetting() {
        return CIO_Integration_Setting__mdt.getInstance('Opportunity_Update');
    }

    private class HttpMock implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {
            HttpResponse response = new HttpResponse();
            response.setStatusCode(200);
            response.setHeader('Content-Type', 'application/json');
            response.setBody('Hello World.');
            return response;
        }
    }
}