unpackaged/main/default/objects/Account/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <label>Persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>US High School Student</fullName>
            </value>
            <value>
                <fullName>International High School Student</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>High School Guidance Counselor</fullName>
            </value>
            <value>
                <fullName>Independent Educational Consultant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/University.recordType-meta.xml
<RecordType>
    <fullName>University</fullName>
    <active>true</active>
    <description>The default record type for all Universities and Colleges</description>
    <label>University</label>
</RecordType>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Student applications for admission into Verto Education</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a Student Account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Student Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Applicant_Email__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Email__c</fullName>
    <externalId>true</externalId>
    <label>Applicant Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admitted</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Decision Ready</fullName>
            </value>
            <value>
                <fullName>Deposit Received</fullName>
            </value>
            <value>
                <fullName>Engaged</fullName>
            </value>
            <value>
                <fullName>Family Admissions Call</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Marketing Nurture</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Requirements Gathering</fullName>
            </value>
            <value>
                <fullName>Student Declined Channel Partner</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>Send Student Acceptance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/University__c.field-meta.xml
<CustomField>
    <fullName>University__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The university/college that the channel enrollment or bridge application was sourced from</description>
    <inlineHelpText>The university/college that the channel enrollment or bridge application was sourced from</inlineHelpText>
    <label>University</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications (Channel Enrollment University)</relationshipLabel>
    <relationshipName>Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>x_First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <label>Persona</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>US High School Student</fullName>
            </value>
            <value>
                <fullName>International High School Student</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>High School Guidance Counselor</fullName>
            </value>
            <value>
                <fullName>Independent Educational Consultant</fullName>
            </value>
            <value>
                <fullName>Verto University Partner</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Program Director</fullName>
            </value>
            <value>
                <fullName>SLC</fullName>
            </value>
            <value>
                <fullName>ASC</fullName>
            </value>
            <value>
                <fullName>Faculty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SF_ID18_User__c.field-meta.xml
<CustomField>
    <fullName>SF_ID18_User__c</fullName>
    <label>SF_ID18_User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/University.recordType-meta.xml
<RecordType>
    <fullName>University</fullName>
    <active>true</active>
    <description>Default Record Type for University Contacts</description>
    <label>University</label>
</RecordType>

unpackaged/main/default/objects/Postal_Code__c/Postal_Code__c.object-meta.xml
<CustomObject>
    <label>Postal Code</label>
    <nameField>
        <label>Postal Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Postal Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/User/fields/SF_ID18_User__c.field-meta.xml
<CustomField>
    <fullName>SF_ID18_User__c</fullName>
    <formula>CASESAFEID(Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SF_ID18_User</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/channelAppTriggerHandlerTestClass.cls
@isTest(SeeAllData=false)
public class channelAppTriggerHandlerTestClass{

    @isTest
    static void ChannelAppTriggerHandler(){
        Account acc = new Account();
        acc.recordtypeid = '0123h0000015Nm4AAE';
        acc.First_Name__c = 'firstNametestData';
        acc.Last_Name__c = 'lastName';
        acc.Name = 'name';
        
        insert acc;
        Account accId = [select id from account where First_Name__c = 'firstNametestData' limit 1];
        
        
        Account accUni = new Account();
        accUni.recordtypeid = System.Label.RT_Account_Partner;
        accUni.First_Name__c = 'firstNametestDataUni';
        accUni.Last_Name__c = 'lastName';
        accUni.name = 'name';
        
        insert accUni;
        Account accIdUni = [select id from account where First_Name__c = 'firstNametestDataUni' limit 1];
        
        Contact uniContact = new Contact();
        uniContact.recordtypeid = System.Label.RT_Contact_University;
        uniContact.lastname = 'lastNametestDataUniContact';
        uniContact.accountid = accIdUni.id;
        uniContact.persona__c = 'Verto University Partner';
        
        insert uniContact;
        Contact partnerContact = [select id from contact where lastname = 'lastNametestDataUniContact' limit 1];
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Partner Community User - Verto'];
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='123stan123darduser@123testorg.com');
        u.contactId = partnerContact.id;
        insert u;
        
        User partnerUser = [select id from user where UserName = '123stan123darduser@123testorg.com' limit 1];
        partnerContact.SF_ID18_User__c = partnerUser.id;
        update partnerContact;
        
        Application__c channelApp = new Application__c();
        channelApp.recordtypeid = '0123h000000VHZCAA4';
        channelApp.name = 'appNametestData';
        channelApp.Account__c= accId.id;
        channelApp.University__c = accIdUni.id;
        channelApp.Applicant_Phone__c = 'phonetestnumber';
        channelApp.Applicant_First_Name__c = 'first';
        channelApp.Applicant_Last_Name__c = 'last';
        channelApp.Applicant_Email__c = 'email@gmail.com';
        channelApp.Application_Status__c = 'Deposit Received';
        channelApp.Street__c = 'street';
        channelApp.City__c = 'city';
        channelApp.State_Province__c = 'Virginia';
        channelApp.Country__c = 'United States';
        channelApp.Postal_Code__c = '112';

        insert channelApp;

        channelApp.Applicant_Phone__c = 'newPhone';
        update channelApp;
        
    }
}