unpackaged/main/default/objects/Account/fields/School_of_Record__c.field-meta.xml
<CustomField>
    <fullName>School_of_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <label>School of Record</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/Enrollment_Record__c.object-meta.xml
<CustomObject>
    <label>Enrollment Record</label>
    <nameField>
        <displayFormat>EN-{00000000}</displayFormat>
        <label>Enrollment Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Course_Interest_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Course_Interest_Submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Triggers the Course Registration Confirmation Email Alert flow</description>
    <label>Course Interest Submitted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Course_Registration_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Course_Registration_Close_Date__c</fullName>
    <inlineHelpText>The last day the student can register for courses. Usually determined by when an evaluation was completed or the program&#39;s registration open date.</inlineHelpText>
    <label>Course Registration Close Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Enrollment_Status__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Status__c</fullName>
    <label>Enrollment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enrolled</fullName>
                <default>true</default>
                <label>Enrolled</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Graduated</fullName>
            </value>
            <value>
                <fullName>Pending Withdrawal</fullName>
            </value>
            <value>
                <fullName>Withdrew</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Dismissed</fullName>
            </value>
            <value>
                <fullName>Verto Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Enrollment Records</relationshipLabel>
    <relationshipName>Enrollment_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Program__c.Location__r.Id</field>
            <operation>notEqual</operation>
            <value>a1G3h000000i2EQ</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Enrollment Records</relationshipLabel>
    <relationshipName>Enrollment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/School_of_Record__c.field-meta.xml
<CustomField>
    <fullName>School_of_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School of Record</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.School_of_Record__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>School of Record Enrolled Students</relationshipLabel>
    <relationshipName>Enrollment_Records1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Student_Account__c.field-meta.xml
<CustomField>
    <fullName>Student_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enrollment Records</relationshipLabel>
    <relationshipName>Enrollment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Enrollment_Record__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrollment Record</label>
    <referenceTo>Enrollment_Record__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Enrollment_Status__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Status__c</fullName>
    <formula>TEXT(Enrollment_Record__r.Enrollment_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Enrollment Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/StudentInformation.cls
public without sharing class StudentInformation {
    @AuraEnabled
    public Id academicProviderId {get;set;}
    @AuraEnabled
    public String academicProviderName {get;set;}
    @AuraEnabled
    public String accountId {get;set;}
    @AuraEnabled
    public Boolean channelStudent {get;set;}
    @AuraEnabled
    public Id channelSchoolId {get;set;}
    @AuraEnabled
    public String channelSchoolName {get;set;}
    @AuraEnabled
    public Id currentProgramId {get;set;}
    @AuraEnabled
    public String currentProgramName {get;set;}
    public Enrollment_Record__c enrollment;


    @AuraEnabled(cacheable=true)
    public static StudentInformation getStudentInfosForRunningUser() {
        return new StudentInformation()
            .getAllStudentInfosByAccountId(
                getRunningUserAccountId()
            );
    }

    public StudentInformation getAllStudentInfosByAccountId(Id accountId) {
        this.accountId = accountId;
        this.getCurrentEnrollmentRecord();
        return this;
    }
    
    @TestVisible
    private void getCurrentEnrollmentRecord() {
        if (this.accountId == null) {
            throw new StudentInformationException('Account Id is required');
        }
        //In future iteration, omit this constant and replace with dynamic query once program architecture can support it.
        final String semester = '%Fall 2022';
        List<Enrollment_Record__c> enrollments = [
            SELECT Id, Program__c, Program__r.Name, 
                School_of_Record__c, School_of_Record__r.Name,
                Course_Interest_Submitted__c, Course_Registration_Close_Date__c,
                Opportunity__r.RecordType.Name
            FROM Enrollment_Record__c
            WHERE Program__r.Name LIKE :semester
            AND Student_Account__c = :this.accountId
            AND Enrollment_Status__c = 'Enrolled'
            ORDER BY CreatedDate DESC
        ];
        if (!enrollments.isEmpty()) {
            this.enrollment = enrollments[0];
        }
        this.setStudentInfosFromCurrentEnrollmentRecord();
    }
    private void setStudentInfosFromCurrentEnrollmentRecord() {
        if (this.enrollment == null) {
            return;
        }
        this.academicProviderId = this.enrollment.School_of_Record__c;
        this.academicProviderName = this.enrollment.School_of_Record__r.Name;
        this.channelStudent = this.enrollment.Opportunity__r.RecordType.Name.contains('Channel');
        this.currentProgramId = this.enrollment.Program__c;
        this.currentProgramName = this.enrollment.Program__r.Name;
    }

    private static Id getRunningUserAccountId() {
        return [
            SELECT Contact.AccountId
            FROM User
            WHERE Id = :UserInfo.getUserId()
            LIMIT 1
        ].Contact.AccountId;
    }

    public class StudentInformationException extends Exception {}

}