unpackaged/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Course__c/fields/Course_Prerequisites__c.field-meta.xml
<CustomField>
    <fullName>Course_Prerequisites__c</fullName>
    <label>Course Prerequisites</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rhetoric &amp; Research I</fullName>
            </value>
            <value>
                <fullName>Spanish I</fullName>
            </value>
            <value>
                <fullName>Spanish II</fullName>
            </value>
            <value>
                <fullName>Pre-Calculus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Course__c/fields/hasPrerequisites__c.field-meta.xml
<CustomField>
    <fullName>hasPrerequisites__c</fullName>
    <formula>Number_Of_Prerequisites__c != 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>hasPrerequisites</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/Course_Prerequisite__c.object-meta.xml
<CustomObject>
    <label>Course Prerequisite</label>
    <nameField>
        <displayFormat>PreReq-{0000000}</displayFormat>
        <label>Prerequisite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Prerequisites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Question__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Algebra II</fullName>
            </value>
            <value>
                <fullName>Geometry</fullName>
            </value>
            <value>
                <fullName>Trigonometry</fullName>
            </value>
            <value>
                <fullName>Pre-Calculus</fullName>
            </value>
            <value>
                <fullName>Calculus</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>One Year</fullName>
            </value>
            <value>
                <fullName>Two Years</fullName>
            </value>
            <value>
                <fullName>Three Years</fullName>
            </value>
            <value>
                <fullName>Four Years</fullName>
            </value>
            <value>
                <fullName>B- or Higher</fullName>
            </value>
            <value>
                <fullName>C+ or Lower</fullName>
            </value>
            <value>
                <fullName>Contemporary Math</fullName>
                <isActive>false</isActive>
                <label>Contemporary Math</label>
            </value>
            <value>
                <fullName>Pre-Calculus I</fullName>
                <isActive>false</isActive>
                <label>Pre-Calculus I</label>
            </value>
            <value>
                <fullName>Pre-Calculus II</fullName>
                <isActive>false</isActive>
                <label>Pre-Calculus II</label>
            </value>
            <value>
                <fullName>test</fullName>
                <isActive>false</isActive>
                <label>test</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Corequisite_Course__c.field-meta.xml
<CustomField>
    <fullName>Corequisite_Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corequisite Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Prerequisites (Corequisite Course)</relationshipLabel>
    <relationshipName>Course_Corequisites</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Prerequisites</relationshipLabel>
    <relationshipName>Course_Prerequisites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <inlineHelpText>Prerequisites of the same group are all required. Prerequisites of different groups are optional.</inlineHelpText>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>A</label>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Course_Subject</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prerequisite</fullName>
                <default>true</default>
                <label>Prerequisite</label>
            </value>
            <value>
                <fullName>Corequisite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Course_Subject.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Anthropology</fullName>
    </customValue>
    <customValue>
        <fullName>Art</fullName>
    </customValue>
    <customValue>
        <fullName>Biology</fullName>
    </customValue>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <customValue>
        <fullName>Chemistry</fullName>
    </customValue>
    <customValue>
        <fullName>Communications</fullName>
    </customValue>
    <customValue>
        <fullName>Computer Science</fullName>
    </customValue>
    <customValue>
        <fullName>Economics</fullName>
    </customValue>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>Geography</fullName>
    </customValue>
    <customValue>
        <fullName>Government/Politics</fullName>
    </customValue>
    <customValue>
        <fullName>History</fullName>
    </customValue>
    <customValue>
        <fullName>Mathematics</fullName>
    </customValue>
    <customValue>
        <fullName>Music</fullName>
    </customValue>
    <customValue>
        <fullName>Philosophy</fullName>
    </customValue>
    <customValue>
        <fullName>Project Management</fullName>
    </customValue>
    <customValue>
        <fullName>Psychology</fullName>
    </customValue>
    <customValue>
        <fullName>Religion</fullName>
    </customValue>
    <customValue>
        <fullName>Science</fullName>
    </customValue>
    <customValue>
        <fullName>Sociology</fullName>
    </customValue>
    <customValue>
        <fullName>Spanish</fullName>
    </customValue>
    <customValue>
        <fullName>Theater</fullName>
    </customValue>
    <masterLabel>Course Subject</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/Course.cls
public with sharing class Course {
    @AuraEnabled
    public Id id {get; set;}
    @AuraEnabled
    public String name {get; set;}
    @AuraEnabled
    public String description {get; set;}
    @AuraEnabled
    public Integer creditHours {get; set;}
    @AuraEnabled 
    public String subject {get; set;}
    @AuraEnabled
    public String prerequisiteDescription {get; set;}
    @AuraEnabled
    public String corequisiteDescription {get; set;}
    public Boolean hasPrerequisites;
    public Boolean hasCorequisites;
    public Map<String, List<Prerequisite>> prerequisites;
    public Set<String> corequisiteGroups;
    public List<Corequisite> corequisites;

    public String highestGroupLetter;

    public Course() {
        this.prerequisites = new Map<String, List<Prerequisite>>();
        this.corequisites = new List<Corequisite>();
    }
    
    public Course(
        Course__c vertoCourse
    ) {
        this.id = vertoCourse.Id;
        this.name = vertoCourse.Name;
        this.description = vertoCourse.Description__c;
        this.subject = vertoCourse.Subject__c;
        this.hasPrerequisites = vertoCourse.hasPrerequisites__c;
        this.prerequisites = new Map<String, List<Prerequisite>>();
        this.corequisites = new List<Corequisite>();
        this.constructPrequisiteMatrix(vertoCourse.Course_Prerequisites__r);
    }



    private void constructPrequisiteMatrix(List<Course_Prerequisite__c> prerequisites) {
        Set<String> corequisiteGroups = new Set<String>();
        List<Prerequisite> temp;
        Map<String, Prerequisite[]> prerequisiteMatrix = new Map<String, Prerequisite[]>();
        //iterate over prerequisites to put them in a matrix for evaluating AND/OR logic effectively.
        for (Course_Prerequisite__c prerequisite :prerequisites) {
            if (prerequisite.Type__c == 'Corequisite') {
                this.corequisites.add(new Corequisite(prerequisite));
                continue;
            } 
            temp = prerequisiteMatrix.get(prerequisite.Group__c);
            if (temp == null) {
                prerequisiteMatrix.put(prerequisite.Group__c, temp = new List<Prerequisite>());
            } 
            temp.add(new Prerequisite(
                prerequisite
            ));
        }
        this.hasCorequisites = !this.corequisites.isEmpty();      
        this.corequisiteGroups = corequisiteGroups;
        this.prerequisites = prerequisiteMatrix;
    }


    public class Prerequisite {
        private Id prerequisiteId;
        private String condition;
        private String prereqGroup;

        /* An Explanation of Prerequisite Groups:
         * Because prerequesite requirements are complex rules, these rules are segmented into a series of conditions of AND/OR logic.
         * Some courses can have prerequesite requirements that are satieted by many conditions being met (AND statements) or conversely,
         * a course can have many different requirements that allow for eligibility as long as any of the requirements are met (OR statements).
         * Additionally, these can become further complex, combining a mix of the two aforementioned types (AND and/or OR statements).
         * To define this in the database schema and for evaluation rules, there is a field called Group__c on the Course_Prerequisite__c object
         * that is used to allow these rules to be set effectively. The logic for how groups are to be handled is as follows:
         * 
         *  1. ANY conditions that share the same group identifier are considered to be corequiried.
         *      Every condition must be met for the group to be considered satieted.
         *  2. If ANY group is satieted, the course is considered eligible for enrollment.
         *      Zero to many groups can be satieted, some with additional requirements.
         * 
         * The instructions of the Course class is to facilitate the evaluation of the course for eligibility of enrollment by creating a matrix of the conditions
         * with conditions being organized into their respective grouping as arrays, with their Group identifier as the key of the map. 
         * Each array is then evaluated for all true values of condition(s) being met. If at least one array is all true values, the course
         * is deemed eligible for enrollment. Whether or not the only groups that were satieted have any additional requirements or corequisites may
         * be also passed along to whatever resource requested eligibility for enrollment. 
        */


        public Prerequisite(Course_Prerequisite__c prerequisite) {
            this.condition = prerequisite.Condition__c;
        }

        public Boolean isConditionMet(Set<String> answers) {
            if (
                this.condition == null
            ) {
                return true;
            }
            return answers?.contains(this.condition);
        }
    }

    public class Corequisite {
        public Id courseId;
        public Id corequisiteId;
        public String corequisiteName;
        public Boolean strictRequirement;
        public String corequisiteGroup;
        

        public Corequisite(Course_Prerequisite__c corequisite) {
            this.courseId = corequisite.Course__c;
            this.corequisiteId = corequisite.Corequisite_Course__c;
            this.corequisiteName = corequisite.Corequisite_Course__r.Name;
            this.strictRequirement = (corequisite.Group__c == null && corequisite.Condition__c == null);
            if (!this.strictRequirement) {
                corequisiteGroup = corequisite.Group__c;
            }
        }

        public Course_Prerequisite__c establishStrictRequirement() {
            if (this.corequisiteGroup != null) {
                throw new IllegalArgumentException('Corequisite must not be part of a group.');
            }
            return new Course_Prerequisite__c(
                Course__c = this.corequisiteId,
                Corequisite_Course__c = this.courseId
            );
        }
    }

    
}