unpackaged/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Course__c/fields/Course_Prerequisites__c.field-meta.xml
<CustomField>
    <fullName>Course_Prerequisites__c</fullName>
    <label>Course Prerequisites</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rhetoric &amp; Research I</fullName>
            </value>
            <value>
                <fullName>Spanish I</fullName>
            </value>
            <value>
                <fullName>Spanish II</fullName>
            </value>
            <value>
                <fullName>Pre-Calculus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Course__c/fields/hasPrerequisites__c.field-meta.xml
<CustomField>
    <fullName>hasPrerequisites__c</fullName>
    <formula>Number_Of_Prerequisites__c != 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>hasPrerequisites</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/Course_Prerequisite__c.object-meta.xml
<CustomObject>
    <label>Course Prerequisite</label>
    <nameField>
        <displayFormat>PreReq-{0000000}</displayFormat>
        <label>Prerequisite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Prerequisites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Question__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Algebra II</fullName>
            </value>
            <value>
                <fullName>Geometry</fullName>
            </value>
            <value>
                <fullName>Trigonometry</fullName>
            </value>
            <value>
                <fullName>Pre-Calculus</fullName>
            </value>
            <value>
                <fullName>Calculus</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>One Year</fullName>
            </value>
            <value>
                <fullName>Two Years</fullName>
            </value>
            <value>
                <fullName>Three Years</fullName>
            </value>
            <value>
                <fullName>Four Years</fullName>
            </value>
            <value>
                <fullName>B- or Higher</fullName>
            </value>
            <value>
                <fullName>C+ or Lower</fullName>
            </value>
            <value>
                <fullName>Contemporary Math</fullName>
                <isActive>false</isActive>
                <label>Contemporary Math</label>
            </value>
            <value>
                <fullName>Pre-Calculus I</fullName>
                <isActive>false</isActive>
                <label>Pre-Calculus I</label>
            </value>
            <value>
                <fullName>Pre-Calculus II</fullName>
                <isActive>false</isActive>
                <label>Pre-Calculus II</label>
            </value>
            <value>
                <fullName>test</fullName>
                <isActive>false</isActive>
                <label>test</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Corequisite_Course__c.field-meta.xml
<CustomField>
    <fullName>Corequisite_Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corequisite Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Prerequisites (Corequisite Course)</relationshipLabel>
    <relationshipName>Course_Corequisites</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Prerequisites</relationshipLabel>
    <relationshipName>Course_Prerequisites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <inlineHelpText>Prerequisites of the same group are all required. Prerequisites of different groups are optional.</inlineHelpText>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>A</label>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>What is the students highest level of math completed with a C or greater?</fullName>
            </value>
            <value>
                <fullName>How many years of High School Spanish has the student completed with a C or greater?</fullName>
            </value>
            <value>
                <fullName>What was the students Junior year English grade?</fullName>
            </value>
            <value>
                <fullName>What is the student&#39;s highest level of math completed with a C or greater?</fullName>
                <isActive>false</isActive>
                <label>What is the student&#39;s highest level of math completed with a C or greater?</label>
            </value>
            <value>
                <fullName>What was the student&#39;s Junior year English grade?</fullName>
                <isActive>false</isActive>
                <label>What was the student&#39;s Junior year English grade?</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Course_Subject</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prerequisite</fullName>
                <default>true</default>
                <label>Prerequisite</label>
            </value>
            <value>
                <fullName>Corequisite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Course_Subject.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Anthropology</fullName>
    </customValue>
    <customValue>
        <fullName>Art</fullName>
    </customValue>
    <customValue>
        <fullName>Biology</fullName>
    </customValue>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <customValue>
        <fullName>Chemistry</fullName>
    </customValue>
    <customValue>
        <fullName>Communications</fullName>
    </customValue>
    <customValue>
        <fullName>Computer Science</fullName>
    </customValue>
    <customValue>
        <fullName>Economics</fullName>
    </customValue>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>Geography</fullName>
    </customValue>
    <customValue>
        <fullName>Government/Politics</fullName>
    </customValue>
    <customValue>
        <fullName>History</fullName>
    </customValue>
    <customValue>
        <fullName>Mathematics</fullName>
    </customValue>
    <customValue>
        <fullName>Music</fullName>
    </customValue>
    <customValue>
        <fullName>Philosophy</fullName>
    </customValue>
    <customValue>
        <fullName>Project Management</fullName>
    </customValue>
    <customValue>
        <fullName>Psychology</fullName>
    </customValue>
    <customValue>
        <fullName>Religion</fullName>
    </customValue>
    <customValue>
        <fullName>Science</fullName>
    </customValue>
    <customValue>
        <fullName>Sociology</fullName>
    </customValue>
    <customValue>
        <fullName>Spanish</fullName>
    </customValue>
    <customValue>
        <fullName>Theater</fullName>
    </customValue>
    <masterLabel>Course Subject</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CourseTests.cls
@IsTest
public with sharing class CourseTests {

    @TestSetup
    static void makeData(){
        TestDataFactory.insertMockCoursesWithPrerequisites();
    }

    @IsTest
    static void testDefaultConstructor() {
        Test.startTest();
        Course course = new Course();
        Test.stopTest();
        System.assertEquals(
            null,
            course.name,
            'Expected name property to be null.'
        );
        System.assertEquals(
            new Map<String, List<Course.Prerequisite>>(),
            course.prerequisites,
            'Expected prerequisites property to be uninitialized.'
        );
    }

    @IsTest
    static void testConstructorWithoutPrerequisitesIncluded() {
        Course__c sampleCourse = [
            SELECT Id, Name, Description__c, Subject__c, hasPrerequisites__c 
            FROM Course__c 
            LIMIT 1
        ];
        Test.startTest();
        Course course = new Course(sampleCourse);
        Course nullCourse = new Course();
        Test.stopTest();
        System.assertEquals(
            sampleCourse.name,
            course.name,
            'Expected name property to match the course record\'s name'
        );
        System.assertEquals(
            new Map<String, List<Course.Prerequisite>>(),
            course.prerequisites,
            'Expected prerequisites property to be uninitialized.'
        );
    }

    @IsTest
    static void testConstructorWithPrerequisitesIncluded() {
        Course__c sampleCourse = [
            SELECT Id, Name, Description__c, Subject__c, hasPrerequisites__c,
            (
                SELECT Id, Course__c, Question__c, Condition__c, 
                Group__c, Type__c, Corequisite_Course__c
                FROM Course_Prerequisites__r
                WHERE Type__c = 'Prerequisite'
            )
            FROM Course__c 
            LIMIT 1
        ];
        Test.startTest();
        Course course = new Course(sampleCourse);
        Test.stopTest();
        System.assertEquals(
            sampleCourse.name,
            course.name,
            'Expected name property to match the course record\'s name'
        );
        System.assertNotEquals(
            new Map<String, List<Course.Prerequisite>>(),
            course.prerequisites,
            'Expected prerequisites property to be initialized with the prerequisites.'
        );
        System.assertEquals(
            new List<Course.Corequisite>(),
            course.corequisites,
            'Expected corequisite property to be unitialized.'
        );
    }

    @IsTest
    static void testConstructorWithCorequisitesIncluded() {
        Course__c sampleCourse = [
            SELECT Id, Name, Description__c, Subject__c, hasPrerequisites__c,
            (
                SELECT Id, Course__c, Condition__c, Group__c,
                Type__c, Corequisite_Course__c, Corequisite_Course__r.Name
                FROM Course_Prerequisites__r
                WHERE Type__c = 'Corequisite'
            )
            FROM Course__c 
            LIMIT 1
        ];
        Test.startTest();
        Course course = new Course(sampleCourse);
        Test.stopTest();
        System.assertEquals(
            sampleCourse.name,
            course.name,
            'Expected name property to match the course record\'s name'
        );
        System.assertEquals(
            new Map<String, List<Course.Prerequisite>>(),
            course.prerequisites,
            'Expected prerequisites property to be unitialized.'
        );
        System.assertNotEquals(
            new List<Course.Corequisite>(),
            course.corequisites,
            'Expected corequisite property to be initialized with the corequisites.'
        );
    }

    @IsTest
    static void testConditionlessPrerequisiteBeingMet() {
        Course_Prerequisite__c coursePrereq = [
            SELECT Id, Course__c, Question__c, Condition__c, 
            Group__c, Type__c, Corequisite_Course__c
            FROM Course_Prerequisite__c
            WHERE Type__c = 'Prerequisite'
            AND Condition__c != null
            LIMIT 1
        ];
        coursePrereq.Condition__c = null;
        Test.startTest();
        Course.Prerequisite prerequisite = new Course.Prerequisite(coursePrereq);
        Boolean expectedPass = prerequisite.isConditionMet(new Set<String>{});
        System.assertEquals(
            true,
            expectedPass,
            'Expected the returned result from isConditionMet to be true.'
        );
    }

    @IsTest
    static void testPrerequisiteConditionMet() {
        Course_Prerequisite__c coursePrereq = [
            SELECT Id, Course__c, Question__c, Condition__c, 
            Group__c, Type__c, Corequisite_Course__c
            FROM Course_Prerequisite__c
            WHERE Type__c = 'Prerequisite'
            AND Condition__c != null
            LIMIT 1
        ];
        Test.startTest();
        Course.Prerequisite prerequisite = new Course.Prerequisite(coursePrereq);
        Boolean expectedPass = prerequisite.isConditionMet(new Set<String>{coursePrereq.Condition__c});
        Boolean expectedFail = prerequisite.isConditionMet(new Set<String>{'Hello World'});
        Test.stopTest();
        System.assertEquals(
            true,
            expectedPass,
            'Expected the returned result from isConditionMet to be true.'
        );
        System.assertEquals(
            false,
            expectedFail,
            'Expected the returned result from isConditionMet to be false'
        );
    }

    @IsTest
    static void testCorequisiteEstablishStrictRequirement() {
        Course_Prerequisite__c courseCorequisite = [
            SELECT Id, Course__c, Condition__c, Group__c,
            Type__c, Corequisite_Course__c, Corequisite_Course__r.Name
            FROM Course_Prerequisite__c
            WHERE Type__c = 'Corequisite'
            LIMIT 1
        ];
        courseCorequisite.Group__c = null;
        Test.startTest();
        Course_Prerequisite__c mirroredCorequisite = new Course.Corequisite(courseCorequisite).establishStrictRequirement();
        Test.stopTest();
        System.assertEquals(
            mirroredCorequisite.Course__c,
            courseCorequisite.Corequisite_Course__c,
            'Expected Course Id and Corequisite Course Id to be switched for the mirroredCorequisite'
        );
    }
   
}