unpackaged/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Course__c/fields/Course_Prerequisites__c.field-meta.xml
<CustomField>
    <fullName>Course_Prerequisites__c</fullName>
    <label>Course Prerequisites</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rhetoric &amp; Research I</fullName>
            </value>
            <value>
                <fullName>Spanish I</fullName>
            </value>
            <value>
                <fullName>Spanish II</fullName>
            </value>
            <value>
                <fullName>Pre-Calculus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Course__c/fields/Highest_Prerequisite_Group__c.field-meta.xml
<CustomField>
    <fullName>Highest_Prerequisite_Group__c</fullName>
    <label>Highest Prerequisite Group</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/Course_Prerequisite__c.object-meta.xml
<CustomObject>
    <label>Course Prerequisite</label>
    <nameField>
        <displayFormat>PreReq-{0000000}</displayFormat>
        <label>Prerequisite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Prerequisites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Prerequisites</relationshipLabel>
    <relationshipName>Course_Prerequisites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <inlineHelpText>Prerequisites of the same group are all required. Prerequisites of different groups are optional.</inlineHelpText>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>A</label>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prerequisite</fullName>
                <default>true</default>
                <label>Prerequisite</label>
            </value>
            <value>
                <fullName>Corequisite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CoursePrerequisitesTriggerHandler.cls
public with sharing class CoursePrerequisitesTriggerHandler {
    public CoursePrerequisitesTriggerHandler() {

    }
    public static void handleBeforeInsert(List<Course_Prerequisite__c> prerequisites) {
        List<Id> courseIdsToUpdate = new List<Id>();
        List<Course_Prerequisite__c> corequisites = new List<Course_Prerequisite__c>();
        for (Course_Prerequisite__c prerequisite : prerequisites) {
            if (prerequisite.Type__c == 'Corequisite') {
                corequisites.add(prerequisite);
            }
            courseIdsToUpdate.add(prerequisite.Course__c);
        }
        if (!corequisites.isEmpty()) {
            insertRequiredCorequisites(corequisites);
        }
        if (!courseIdsToUpdate.isEmpty()) {
            updateCoursePrerequisiteGroups(courseIdsToUpdate);
        }
    }

    private static void insertRequiredCorequisites(List<Course_Prerequisite__c> corequisites) {
        List<Course_Prerequisite__c> mirroredCorequisites = new List<Course_Prerequisite__c>();
        for (Course_Prerequisite__c prereq :corequisites) {
            if (prereq.Type__c == 'Corequisite' && prereq.Group__c == null) {
                Course.Corequisite corequisite = new Course.Corequisite(prereq);
                mirroredCorequisites.add(corequisite.establishStrictRequirement());
            }
        }
        if (!mirroredCorequisites.isEmpty()) {
            List<Database.SaveResult> results = Database.insert(mirroredCorequisites, false);
            for (Database.SaveResult result : results) {
                if (result.success) {
                    continue;
                }
                //handle unhandled exception
            }
        }
    }

    private static void updateCoursePrerequisiteGroups(List<Id> courseIds) {
        List<Course__c> coursesToUpdate = new List<Course__c>();
        for (Course__c course :[
            SELECT Id, Highest_Prerequisite_Group__c,
            (SELECT Id, Group__c FROM Course_Prerequisites__r ORDER BY Group__c DESC) 
            FROM Course__c
            WHERE ID IN :courseIds
            WITH SECURITY_ENFORCED
        ]) {
            if (course.Course_Prerequisites__r.isEmpty()) {
                continue;
            }
            String highestPrerequisiteGroup;
            for (Course_Prerequisite__c preReq :course.Course_Prerequisites__r) {
                if (preReq.Group__c != null) {
                    if (highestPrerequisiteGroup < preReq.Group__c) {
                        highestPrerequisiteGroup = preReq.Group__c;
                    }
                }
            }
            if (
                highestPrerequisiteGroup != null && 
                highestPrerequisiteGroup != course.Highest_Prerequisite_Group__c
            ) {
                course.Highest_Prerequisite_Group__c = highestPrerequisiteGroup;
                coursesToUpdate.add(course);
            }
        }
        if (!coursesToUpdate.isEmpty() && Schema.sObjectType.Course__c.isUpdateable()) {
            List<Database.SaveResult> results = Database.update(coursesToUpdate);
            /* if (!results.isSuccess()) {
                //handle errors
            } */
        }
    }
}