unpackaged/main/default/objects/Student_File__mdt/Student_File__mdt.object-meta.xml
<CustomObject>
    <description>Metadata for determining which files should reside on the Account for the Student.</description>
    <label>Student File</label>
    <pluralLabel>Student Files</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Student_File__mdt/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <description>The API name of the field. Used for mapping which form should update which field on the records.</description>
    <label>Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Student_File__mdt/fields/Submission_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Submission_Field_API_Name__c</fullName>
    <label>Submission Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/MetadataUtils.cls
public with sharing class MetadataUtils {
    public MetadataUtils() {

    }

    public static Map<String, Student_File__mdt> getActiveStudentFileMetadata() {
        Map<String, Student_File__mdt> studentFiles = new Map<String, Student_File__mdt>();
        for(Student_File__mdt setting :[SELECT MasterLabel, Field_API_Name__c, Submission_Field_API_Name__c 
                                        FROM Student_File__mdt 
                                        WHERE isActive__c = true
                                        ORDER BY MasterLabel]
        ){
            studentFiles.put(setting.MasterLabel, setting);
        }
        return studentFiles;
    }

    public static String getActiveStudentFileQueryFields() {
        Set<String> fields = new Set<String>();
        
        for(Student_File__mdt setting :getActiveStudentFileMetadata().values()) {
            fields.add(setting.Field_API_Name__c);
        }
        return String.join(new List<String>(fields), ',');
    }

}