unpackaged/main/default/objects/Academic_Provider_Mapping__c/Academic_Provider_Mapping__c.object-meta.xml
<CustomObject>
    <label>Academic Provider Mapping</label>
    <nameField>
        <label>Course Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academic Provider Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Academic_Provider_Mapping__c/fields/Corequisite_Description__c.field-meta.xml
<CustomField>
    <fullName>Corequisite_Description__c</fullName>
    <inlineHelpText>The message that will be displayed to the student regarding corequisites.</inlineHelpText>
    <label>Corequisite Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Academic_Provider_Mapping__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Academic Provider Mappings</relationshipLabel>
    <relationshipName>Academic_Provider_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Academic_Provider_Mapping__c/fields/Credit_Hours__c.field-meta.xml
<CustomField>
    <fullName>Credit_Hours__c</fullName>
    <label>Credit Hours</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Academic_Provider_Mapping__c/fields/Prerequisite_Description__c.field-meta.xml
<CustomField>
    <fullName>Prerequisite_Description__c</fullName>
    <inlineHelpText>The message that will be displayed to the student regarding prerequisites.</inlineHelpText>
    <label>Prerequisite Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Course__c/fields/Course_Prerequisites__c.field-meta.xml
<CustomField>
    <fullName>Course_Prerequisites__c</fullName>
    <label>Course Prerequisites</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rhetoric &amp; Research I</fullName>
            </value>
            <value>
                <fullName>Spanish I</fullName>
            </value>
            <value>
                <fullName>Spanish II</fullName>
            </value>
            <value>
                <fullName>Pre-Calculus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Course__c/fields/hasPrerequisites__c.field-meta.xml
<CustomField>
    <fullName>hasPrerequisites__c</fullName>
    <formula>Number_Of_Prerequisites__c != 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>hasPrerequisites</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/Course_Prerequisite__c.object-meta.xml
<CustomObject>
    <label>Course Prerequisite</label>
    <nameField>
        <displayFormat>PreReq-{0000000}</displayFormat>
        <label>Prerequisite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Prerequisites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Question__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Algebra II</fullName>
            </value>
            <value>
                <fullName>Geometry</fullName>
            </value>
            <value>
                <fullName>Trigonometry</fullName>
            </value>
            <value>
                <fullName>Pre-Calculus</fullName>
            </value>
            <value>
                <fullName>Calculus</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>One Year</fullName>
            </value>
            <value>
                <fullName>Two Years</fullName>
            </value>
            <value>
                <fullName>Three Years</fullName>
            </value>
            <value>
                <fullName>Four Years</fullName>
            </value>
            <value>
                <fullName>B- or Higher</fullName>
            </value>
            <value>
                <fullName>C+ or Lower</fullName>
            </value>
            <value>
                <fullName>Contemporary Math</fullName>
                <isActive>false</isActive>
                <label>Contemporary Math</label>
            </value>
            <value>
                <fullName>Pre-Calculus I</fullName>
                <isActive>false</isActive>
                <label>Pre-Calculus I</label>
            </value>
            <value>
                <fullName>Pre-Calculus II</fullName>
                <isActive>false</isActive>
                <label>Pre-Calculus II</label>
            </value>
            <value>
                <fullName>test</fullName>
                <isActive>false</isActive>
                <label>test</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Corequisite_Course__c.field-meta.xml
<CustomField>
    <fullName>Corequisite_Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corequisite Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Prerequisites (Corequisite Course)</relationshipLabel>
    <relationshipName>Course_Corequisites</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Prerequisites</relationshipLabel>
    <relationshipName>Course_Prerequisites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <inlineHelpText>Prerequisites of the same group are all required. Prerequisites of different groups are optional.</inlineHelpText>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>A</label>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Course_Subject</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prerequisite</fullName>
                <default>true</default>
                <label>Prerequisite</label>
            </value>
            <value>
                <fullName>Corequisite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Transcript_Evaluation__c/Transcript_Evaluation__c.object-meta.xml
<CustomObject>
    <label>Transcript Evaluation</label>
    <nameField>
        <displayFormat>TE-{00000000}</displayFormat>
        <label>Transcript Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transcript Evaluations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Transcript_Evaluation__c/fields/College_Credit_Received_For__c.field-meta.xml
<CustomField>
    <fullName>College_Credit_Received_For__c</fullName>
    <label>College Credit Received For:</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Transcript_Evaluation__c/fields/Eligible_Courses__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Courses__c</fullName>
    <label>Eligible Courses</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Transcript_Evaluation__c/fields/Junior_Year_English_Grade__c.field-meta.xml
<CustomField>
    <fullName>Junior_Year_English_Grade__c</fullName>
    <label>Junior Year English Grade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B- or Higher</fullName>
            </value>
            <value>
                <fullName>C+ or Lower</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Transcript_Evaluation__c/fields/Math_Completed__c.field-meta.xml
<CustomField>
    <fullName>Math_Completed__c</fullName>
    <label>Math Completed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Algebra II</fullName>
            </value>
            <value>
                <fullName>Pre-Calculus</fullName>
            </value>
            <value>
                <fullName>Calculus</fullName>
            </value>
            <value>
                <fullName>Contemporary Math</fullName>
                <isActive>false</isActive>
                <label>Contemporary Math</label>
            </value>
            <value>
                <fullName>Geometry</fullName>
                <isActive>false</isActive>
                <label>Geometry</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Pre-Calculus I</fullName>
                <isActive>false</isActive>
                <label>Pre-Calculus I</label>
            </value>
            <value>
                <fullName>Pre-Calculus II</fullName>
                <isActive>false</isActive>
                <label>Pre-Calculus II</label>
            </value>
            <value>
                <fullName>Trigonometry</fullName>
                <isActive>false</isActive>
                <label>Trigonometry</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Transcript_Evaluation__c/fields/Spanish_Completed__c.field-meta.xml
<CustomField>
    <fullName>Spanish_Completed__c</fullName>
    <label>Spanish Completed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One Year</fullName>
            </value>
            <value>
                <fullName>Two Years</fullName>
            </value>
            <value>
                <fullName>Three Years</fullName>
            </value>
            <value>
                <fullName>Four Years</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Transcript_Evaluation__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transcript Evaluations</relationshipLabel>
    <relationshipName>Transcript_Evaluations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/Course_Subject.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Anthropology</fullName>
    </customValue>
    <customValue>
        <fullName>Art</fullName>
    </customValue>
    <customValue>
        <fullName>Biology</fullName>
    </customValue>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <customValue>
        <fullName>Chemistry</fullName>
    </customValue>
    <customValue>
        <fullName>Communications</fullName>
    </customValue>
    <customValue>
        <fullName>Computer Science</fullName>
    </customValue>
    <customValue>
        <fullName>Economics</fullName>
    </customValue>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>Geography</fullName>
    </customValue>
    <customValue>
        <fullName>Government/Politics</fullName>
    </customValue>
    <customValue>
        <fullName>History</fullName>
    </customValue>
    <customValue>
        <fullName>Mathematics</fullName>
    </customValue>
    <customValue>
        <fullName>Music</fullName>
    </customValue>
    <customValue>
        <fullName>Philosophy</fullName>
    </customValue>
    <customValue>
        <fullName>Project Management</fullName>
    </customValue>
    <customValue>
        <fullName>Psychology</fullName>
    </customValue>
    <customValue>
        <fullName>Religion</fullName>
    </customValue>
    <customValue>
        <fullName>Science</fullName>
    </customValue>
    <customValue>
        <fullName>Sociology</fullName>
    </customValue>
    <customValue>
        <fullName>Spanish</fullName>
    </customValue>
    <customValue>
        <fullName>Theater</fullName>
    </customValue>
    <masterLabel>Course Subject</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CourseEligibilityTests.cls
@IsTest
public with sharing class CourseEligibilityTests {

    @TestSetup
    static void makeData(){
        TestDataFactory.insertMockCoursesWithPrerequisites();
        TriggerHandler.suppressHandler('AccountTriggerHandler');
        TriggerHandler.suppressHandler('TranscriptEvaluationTriggerHandler');
        Account sampleAccount = new Account(
            Name = 'Sample Account',
            First_Name__c = 'Sample',
            Last_Name__c = 'Account',
            Email__c = 'SampleAccount@Test.org',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Student Account').getRecordTypeId()
        );
        insert sampleAccount;
        insert new Transcript_Evaluation__c(
            Student__c = sampleAccount.Id,
            College_Credit_Received_For__c = null,
            Eligible_Courses__c = null,
            GPA__c = 3.5,
            Math_Completed__c = 'Algebra II',
            Junior_Year_English_Grade__c = 'B- or Higher',
            Spanish_Completed__c = 'One Year'
        );
        TriggerHandler.clearSuppressedHandlers();
    }

    @IsTest
    static void testDefaultConstructor() {
        Test.startTest();
        CourseEligibility eligibility = new CourseEligibility();
        Test.stopTest();
        System.assertNotEquals(
            null,
            eligibility.prerequisiteGroupsSatisfied,
            'Expected prerequisiteGroupsSatisfied property to be initialized to a new collection.'
        );
        System.assertEquals(
            new List<String>(),
            eligibility.prerequisiteGroupsSatisfied,
            'Expected prerequisiteGroupsSatisfied property to be initialized to a new collection.'
        );
    }

    @IsTest
    static void testSetCourse() {
        Test.startTest();
        CourseEligibility eligibility = new CourseEligibility().setCourse(getCourseObjectByName('Sample Course'));
        Test.stopTest();
        System.assertNotEquals(
            null,
            eligibility.course,
            'Expected course property to be initialized as a new course object.'
        );
        System.assertNotEquals(
            null, 
            eligibility.course.id, 
            'Expected the course\'s id property to be initialized.'
        );
    }

    @IsTest
    static void testSetIsEligible() {
        Test.startTest();
        CourseEligibility eligible = new CourseEligibility().setIsEligible(true);
        CourseEligibility ineligible = new CourseEligibility().setIsEligible(false);
        Test.stopTest();
        System.assertEquals(
            true,
            eligible.isEligible,
            'Expected isEligible to be true for the Eligible object.'
        );
        System.assertEquals(
            false,
            ineligible.isEligible,
            'Expected isEligible to be false for the Ineligible object.'
        );
    }

    @IsTest
    static void testEvaluateEligibilityWithoutCourseSet() {
        Boolean exceptionThrown = false;
        Transcript_Evaluation__c evaluation = [
            SELECT Id, College_Credit_Received_For__c, Eligible_Courses__c,
            GPA__c, Math_Completed__c, Junior_Year_English_Grade__c,
            Spanish_Completed__c
            FROM Transcript_Evaluation__c
            LIMIT 1
        ];
        Test.startTest();
        try {
            CourseEligibility eligibility = new CourseEligibility().evaluateEligibility(evaluation);
        } catch (CourseEligibility.CourseEligibilityException ex) {
            exceptionThrown = true;
        }
        Test.stopTest();
        System.assertEquals(
            true,
            exceptionThrown,
            'Expected exceptionThrown to be set as true after catching the custom exception.'
        );
    }

    @IsTest
    static void testEvaluateEligibility() {
        Boolean exceptionThrown = false;
        Transcript_Evaluation__c evaluation = [
            SELECT Id, College_Credit_Received_For__c, Eligible_Courses__c,
            GPA__c, Math_Completed__c, Junior_Year_English_Grade__c,
            Spanish_Completed__c
            FROM Transcript_Evaluation__c
            LIMIT 1
        ];
        Test.startTest();
        try {
            CourseEligibility eligibility = new CourseEligibility()
                                                .setCourse(getCourseObjectByName('Sample Course'))
                                                .evaluateEligibility(evaluation);
        } catch (CourseEligibility.CourseEligibilityException ex) {
            exceptionThrown = true;
        }
        Test.stopTest();
        System.assertEquals(
            false,
            exceptionThrown,
            'Expected exceptionThrown to be set as true after catching the custom exception.'
        );
    }

    private static Course getCourseObjectByName(String name) {
        return new Course([
            SELECT Id, Name, Subject__c, Description__c, hasPrerequisites__c,
            (SELECT Credit_Hours__c, Prerequisite_Description__c, Corequisite_Description__c FROM Academic_Provider_Mappings__r),
            (SELECT Course__c, Type__c, Group__c, Condition__c, Corequisite_Course__c, Corequisite_Course__r.Name FROM Course_Prerequisites__r)
            FROM Course__c
            WHERE Name = :name
        ]);
    }
}