unpackaged/main/default/objects/Academic_Provider_Mapping__c/Academic_Provider_Mapping__c.object-meta.xml
<CustomObject>
    <label>Academic Provider Mapping</label>
    <nameField>
        <label>Course Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academic Provider Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Academic_Provider_Mapping__c/fields/Academic_Provider__c.field-meta.xml
<CustomField>
    <fullName>Academic_Provider__c</fullName>
    <label>Academic Provider</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only a School of Record may be used.</errorMessage>
        <filterItems>
            <field>Account.School_of_Record__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Academic Provider Mappings</relationshipLabel>
    <relationshipName>School_of_Record_Mappings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/Academic_Provider_Mapping__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Academic Provider Mappings</relationshipLabel>
    <relationshipName>Academic_Provider_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Academic_Provider_Mapping__c/fields/Credit_Hours__c.field-meta.xml
<CustomField>
    <fullName>Credit_Hours__c</fullName>
    <label>Credit Hours</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/School_of_Record__c.field-meta.xml
<CustomField>
    <fullName>School_of_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <label>School of Record</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>x_First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <label>Student</label>
</RecordType>

unpackaged/main/default/objects/Course_Interest__c/Course_Interest__c.object-meta.xml
<CustomObject>
    <label>Course Interest</label>
    <nameField>
        <displayFormat>Interest-{00000000}</displayFormat>
        <label>Course Interest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Interests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Course_Interest__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Interests</relationshipLabel>
    <relationshipName>Course_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Course_Interest__c/fields/Enrollment_Record__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Record__c</fullName>
    <label>Enrollment Record</label>
    <referenceTo>Enrollment_Record__c</referenceTo>
    <relationshipLabel>Course Interests</relationshipLabel>
    <relationshipName>Course_Interests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Course_Interest__c/fields/Preference_Rank__c.field-meta.xml
<CustomField>
    <fullName>Preference_Rank__c</fullName>
    <description>The preference of choice for this course by the student. Lower numbers indicate a higher preference.</description>
    <inlineHelpText>The preference of choice for this course by the student. Lower numbers indicate a higher preference.</inlineHelpText>
    <label>Preference Rank</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Course_Interest__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Alternative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Course_Offering__c/Course_Offering__c.object-meta.xml
<CustomObject>
    <label>Course Offering</label>
    <nameField>
        <displayFormat>Course Offering - {000000}</displayFormat>
        <label>Course Offering Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Course_Offering__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Course_Offering__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/Enrollment_Record__c.object-meta.xml
<CustomObject>
    <label>Enrollment Record</label>
    <nameField>
        <displayFormat>EN-{00000000}</displayFormat>
        <label>Enrollment Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Enrollment_Record__c/fields/GPA__c.field-meta.xml
<CustomField>
    <fullName>GPA__c</fullName>
    <label>GPA</label>
    <precision>7</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Program__c.Location__r.Id</field>
            <operation>notEqual</operation>
            <value>a1G3h000000i2EQ</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Enrollment Records</relationshipLabel>
    <relationshipName>Enrollment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/School_of_Record__c.field-meta.xml
<CustomField>
    <fullName>School_of_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School of Record</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.School_of_Record__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>School of Record Enrolled Students</relationshipLabel>
    <relationshipName>Enrollment_Records1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Student_Account__c.field-meta.xml
<CustomField>
    <fullName>Student_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enrollment Records</relationshipLabel>
    <relationshipName>Enrollment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Program__c/fields/Academic_Provider__c.field-meta.xml
<CustomField>
    <fullName>Academic_Provider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Academic Provider</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Academic Provider Account does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>University</value>
        </filterItems>
        <filterItems>
            <field>Account.School_of_Record__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Program__c/fields/Semester__c.field-meta.xml
<CustomField>
    <fullName>Semester__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Semester</label>
    <referenceTo>Semester__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Transcript_Evaluation__c/Transcript_Evaluation__c.object-meta.xml
<CustomObject>
    <label>Transcript Evaluation</label>
    <nameField>
        <displayFormat>TE-{00000000}</displayFormat>
        <label>Transcript Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transcript Evaluations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Transcript_Evaluation__c/fields/College_Credit_Received_For__c.field-meta.xml
<CustomField>
    <fullName>College_Credit_Received_For__c</fullName>
    <label>College Credit Received For:</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Transcript_Evaluation__c/fields/Eligible_Courses__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Courses__c</fullName>
    <label>Eligible Courses</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Transcript_Evaluation__c/fields/Enrollment_Record__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrollment Record</label>
    <referenceTo>Enrollment_Record__c</referenceTo>
    <relationshipLabel>Transcript Evaluations</relationshipLabel>
    <relationshipName>Transcript_Evaluations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Transcript_Evaluation__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transcript Evaluations</relationshipLabel>
    <relationshipName>Transcript_Evaluations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/CourseInterestControllerTests.cls
@IsTest
public with sharing class CourseInterestControllerTests {

    @TestSetup
    static void makeData(){
        TriggerHandler.suppressHandler('AccountTriggerHandler');
        TriggerHandler.suppressHandler('OpportunityTriggerHandler');
        TriggerHandler.suppressHandler('EnrollmentRecordTriggerHandler');
        TestDataFactory.insertMockCommunityUser();
        TestDataFactory.insertMockPrograms();
        TestDataFactory.insertMockCoursesWithPrerequisites();
        TestDataFactory.insertOpportunityAndEnrollmentForAccount([SELECT Id, Name FROM Account WHERE Name = 'Community User' LIMIT 1]);
        Account sampleAcademicProvider = new Account(
            Name = 'Sample Academic Provider',
            First_Name__c = 'Sample',
            Last_Name__c = 'Academic Provider',
            School_of_Record__c = true,
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Student Account').getRecordTypeId()
        );
        insert sampleAcademicProvider;
        update new Enrollment_Record__c (
            Id = [SELECT Id FROM Enrollment_Record__c LIMIT 1].Id,
            School_of_Record__c = sampleAcademicProvider.Id,
            Program__c = [SELECT Id FROM Program__c WHERE Semester__r.Name LIKE '%Fall 2022' LIMIT 1].Id
        );
        TriggerHandler.clearSuppressedHandlers();
    }

    @IsTest
    static void testGetEligibleCoursesWithoutAcademicProviderMappings() {
        Boolean caughtException = false;
        List<CourseEligibility> eligibilityForOfferedCourses;
        User contextUser = [SELECT Id, Contact.AccountId FROM User WHERE Username = 'CommunityUser@Test.org' LIMIT 1];
        Id programId = [SELECT Program__c FROM Enrollment_Record__c LIMIT 1].Program__c;
        List<SObject> programOfferings = new List<SObject>();
        Transcript_Evaluation__c evaluation = getMockTranscriptEvaluation();
        evaluation.Student__c = contextUser.Contact.AccountId;
        insert evaluation;
        for (Course__c course :[SELECT Id FROM Course__c]) {
            programOfferings.add(new Course_Offering__c(
                Program__c = programId,
                Course__c = course.Id
            ));
        }
        if (!programOfferings.isEmpty()) {
            insert programOfferings;
        }
        Test.startTest();
        try {
            System.runAs(contextuser){
                eligibilityForOfferedCourses = CourseInterestController.getEligibleCourses();
            }
        } catch (AuraHandledException ex) {
            caughtException = true;
        }
        Test.stopTest();
        System.assertEquals(
            null,
            eligibilityForOfferedCourses,
            'Expected eligibility to be empty due to no academic provider mappings.'
        );
    }

    @IsTest
    static void testGetEligibleCoursesWithoutCourseOfferings() {
        Boolean caughtException = false;
        List<CourseEligibility> eligibilityForOfferedCourses;
        User contextUser = [SELECT Id, Contact.AccountId FROM User WHERE Username = 'CommunityUser@Test.org' LIMIT 1];
        Id academicProviderId = [SELECT Id FROM Account WHERE School_of_Record__c = true LIMIT 1].Id;
        List<SObject> programOfferings = new List<SObject>();
        Transcript_Evaluation__c evaluation = getMockTranscriptEvaluation();
        evaluation.Student__c = contextUser.Contact.AccountId;
        insert evaluation;
        for (Course__c course :[SELECT Id FROM Course__c]) {
            programOfferings.add(new Academic_Provider_Mapping__c(
                Academic_Provider__c = academicProviderId,
                Course__c = course.Id
            ));
        }
        if (!programOfferings.isEmpty()) {
            insert programOfferings;
        }
        Test.startTest();
        try {
            System.runAs(contextuser){
                eligibilityForOfferedCourses = CourseInterestController.getEligibleCourses();
            }
        } catch (AuraHandledException ex) {
            caughtException = true;
        }
        Test.stopTest();
        System.assertEquals(
            null,
            eligibilityForOfferedCourses,
            'Expected eligibility to be empty due to no course offerings.'
        );
    }

    @IsTest
    static void testGetEligibleCoursesWithCoursesFullyMapped() {
        List<CourseEligibility> eligibilityForOfferedCourses;
        User contextUser = [SELECT Id, Contact.AccountId FROM User WHERE Username = 'CommunityUser@Test.org' LIMIT 1];
        Id programId = [SELECT Program__c FROM Enrollment_Record__c LIMIT 1].Program__c;
        Id academicProviderId = [SELECT Id FROM Account WHERE School_of_Record__c = true LIMIT 1].Id;
        List<SObject> programOfferings = new List<SObject>();
        Transcript_Evaluation__c evaluation = getMockTranscriptEvaluation();
        evaluation.Student__c = contextUser.Contact.AccountId;
        insert evaluation;
        for (Course__c course :[SELECT Id FROM Course__c]) {
            programOfferings.add(new Course_Offering__c(
                Program__c = programId,
                Course__c = course.Id
            ));
            programOfferings.add(new Academic_Provider_Mapping__c(
                Academic_Provider__c = academicProviderId,
                Course__c = course.Id
            ));
        }
        if (!programOfferings.isEmpty()) {
            insert programOfferings;
        }
        Test.startTest();
        System.runAs(contextuser){
            eligibilityForOfferedCourses = CourseInterestController.getEligibleCourses();
        }
        Test.stopTest();
        System.assertNotEquals(
            null,
            eligibilityForOfferedCourses,
            'Expected eligibility to not be empty.'
        );
    }

    @IsTest
    static void testSaveCourseSelection() {
        User contextUser = [SELECT Id, Contact.AccountId FROM User WHERE Username = 'CommunityUser@Test.org' LIMIT 1];
        Course sampleCourse = new Course();
        System.debug([SELECT Id FROM Course__c]);
        sampleCourse.Id = [SELECT Id FROM Course__c WHERE Name = 'Sample Course' LIMIT 1].Id;
        sampleCourse.creditHours = 3;
        Course sampleCorequisiteCourse = new Course();
        sampleCorequisiteCourse.Id = [SELECT Id FROM Course__c WHERE Name = 'Sample Corequisite Course' LIMIT 1].Id;
        sampleCorequisiteCourse.creditHours = 3;
        Test.startTest();
        System.runAs(contextUser) {
            CourseInterestController.saveCourseSelection(
                new List<Course>{sampleCourse}, 
                new List<Course>{sampleCorequisiteCourse}
            );
        }
        Test.stopTest();
        List<Course_Interest__c> courseInterests = [
            SELECT Id, Course__c, Enrollment_Record__c, Credit_Hours__c, Preference_Rank__c, Type__c 
            FROM Course_Interest__c
            WHERE Enrollment_Record__r.Student_Account__c = :contextUser.Contact.AccountId
        ];
        System.assertEquals(
            2,
            courseInterests.size(),
            'Expected 2 Course Interests to be created.'
        );
    }

    private static Transcript_Evaluation__c getMockTranscriptEvaluation() {
        return new Transcript_Evaluation__c(
            College_Credit_Received_For__c = null,
            Eligible_Courses__c = null,
            GPA__c = 3.5,
            Math_Completed__c = 'Algebra II',
            Junior_Year_English_Grade__c = 'B- or Higher',
            Spanish_Completed__c = 'One Year'
        );
    }
}