unpackaged/main/default/objects/Academic_Provider_Mapping__c/Academic_Provider_Mapping__c.object-meta.xml
<CustomObject>
    <label>Academic Provider Mapping</label>
    <nameField>
        <label>Course Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academic Provider Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Academic_Provider_Mapping__c/fields/Academic_Provider__c.field-meta.xml
<CustomField>
    <fullName>Academic_Provider__c</fullName>
    <label>Academic Provider</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only a School of Record may be used.</errorMessage>
        <filterItems>
            <field>Account.School_of_Record__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Academic Provider Mappings</relationshipLabel>
    <relationshipName>School_of_Record_Mappings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/Academic_Provider_Mapping__c/fields/Corequisite_Description__c.field-meta.xml
<CustomField>
    <fullName>Corequisite_Description__c</fullName>
    <inlineHelpText>The message that will be displayed to the student regarding corequisites.</inlineHelpText>
    <label>Corequisite Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Academic_Provider_Mapping__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Academic Provider Mappings</relationshipLabel>
    <relationshipName>Academic_Provider_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Academic_Provider_Mapping__c/fields/Credit_Hours__c.field-meta.xml
<CustomField>
    <fullName>Credit_Hours__c</fullName>
    <label>Credit Hours</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Academic_Provider_Mapping__c/fields/Prerequisite_Description__c.field-meta.xml
<CustomField>
    <fullName>Prerequisite_Description__c</fullName>
    <inlineHelpText>The message that will be displayed to the student regarding prerequisites.</inlineHelpText>
    <label>Prerequisite Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Course__c/fields/Course_Prerequisites__c.field-meta.xml
<CustomField>
    <fullName>Course_Prerequisites__c</fullName>
    <label>Course Prerequisites</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rhetoric &amp; Research I</fullName>
            </value>
            <value>
                <fullName>Spanish I</fullName>
            </value>
            <value>
                <fullName>Spanish II</fullName>
            </value>
            <value>
                <fullName>Pre-Calculus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Course__c/fields/hasPrerequisites__c.field-meta.xml
<CustomField>
    <fullName>hasPrerequisites__c</fullName>
    <formula>Number_Of_Prerequisites__c != 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>hasPrerequisites</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Course__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Active_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Course_Interest__c/Course_Interest__c.object-meta.xml
<CustomObject>
    <label>Course Interest</label>
    <nameField>
        <displayFormat>Interest-{00000000}</displayFormat>
        <label>Course Interest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Interests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Course_Interest__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Interests</relationshipLabel>
    <relationshipName>Course_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Course_Interest__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Alternative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Course_Offering__c/Course_Offering__c.object-meta.xml
<CustomObject>
    <label>Course Offering</label>
    <nameField>
        <displayFormat>Course Offering - {000000}</displayFormat>
        <label>Course Offering Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Course_Offering__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/Course_Prerequisite__c.object-meta.xml
<CustomObject>
    <label>Course Prerequisite</label>
    <nameField>
        <displayFormat>PreReq-{0000000}</displayFormat>
        <label>Prerequisite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Prerequisites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Question__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Algebra II</fullName>
            </value>
            <value>
                <fullName>Geometry</fullName>
            </value>
            <value>
                <fullName>Trigonometry</fullName>
            </value>
            <value>
                <fullName>Pre-Calculus</fullName>
            </value>
            <value>
                <fullName>Calculus</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>One Year</fullName>
            </value>
            <value>
                <fullName>Two Years</fullName>
            </value>
            <value>
                <fullName>Three Years</fullName>
            </value>
            <value>
                <fullName>Four Years</fullName>
            </value>
            <value>
                <fullName>B- or Higher</fullName>
            </value>
            <value>
                <fullName>C+ or Lower</fullName>
            </value>
            <value>
                <fullName>Contemporary Math</fullName>
                <isActive>false</isActive>
                <label>Contemporary Math</label>
            </value>
            <value>
                <fullName>Pre-Calculus I</fullName>
                <isActive>false</isActive>
                <label>Pre-Calculus I</label>
            </value>
            <value>
                <fullName>Pre-Calculus II</fullName>
                <isActive>false</isActive>
                <label>Pre-Calculus II</label>
            </value>
            <value>
                <fullName>test</fullName>
                <isActive>false</isActive>
                <label>test</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Corequisite_Course__c.field-meta.xml
<CustomField>
    <fullName>Corequisite_Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corequisite Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Prerequisites (Corequisite Course)</relationshipLabel>
    <relationshipName>Course_Corequisites</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Prerequisites</relationshipLabel>
    <relationshipName>Course_Prerequisites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <inlineHelpText>Prerequisites of the same group are all required. Prerequisites of different groups are optional.</inlineHelpText>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>A</label>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Course_Subject</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Course_Prerequisite__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prerequisite</fullName>
                <default>true</default>
                <label>Prerequisite</label>
            </value>
            <value>
                <fullName>Corequisite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Enrollment_Record__c/Enrollment_Record__c.object-meta.xml
<CustomObject>
    <label>Enrollment Record</label>
    <nameField>
        <displayFormat>EN-{00000000}</displayFormat>
        <label>Enrollment Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Course_Registration_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Course_Registration_Close_Date__c</fullName>
    <inlineHelpText>The last day the student can register for courses. Usually determined by when an evaluation was completed or the program&#39;s registration open date.</inlineHelpText>
    <label>Course Registration Close Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Program__c/fields/Academic_Provider__c.field-meta.xml
<CustomField>
    <fullName>Academic_Provider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Academic Provider</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Academic Provider Account does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>University</value>
        </filterItems>
        <filterItems>
            <field>Account.School_of_Record__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Enrolling</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Active_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <description>The status of whether this record is active, inactive, or other.</description>
    <masterLabel>Active Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Course_Subject.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Anthropology</fullName>
    </customValue>
    <customValue>
        <fullName>Art</fullName>
    </customValue>
    <customValue>
        <fullName>Biology</fullName>
    </customValue>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <customValue>
        <fullName>Chemistry</fullName>
    </customValue>
    <customValue>
        <fullName>Communications</fullName>
    </customValue>
    <customValue>
        <fullName>Computer Science</fullName>
    </customValue>
    <customValue>
        <fullName>Economics</fullName>
    </customValue>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>Geography</fullName>
    </customValue>
    <customValue>
        <fullName>Government/Politics</fullName>
    </customValue>
    <customValue>
        <fullName>History</fullName>
    </customValue>
    <customValue>
        <fullName>Mathematics</fullName>
    </customValue>
    <customValue>
        <fullName>Music</fullName>
    </customValue>
    <customValue>
        <fullName>Philosophy</fullName>
    </customValue>
    <customValue>
        <fullName>Project Management</fullName>
    </customValue>
    <customValue>
        <fullName>Psychology</fullName>
    </customValue>
    <customValue>
        <fullName>Religion</fullName>
    </customValue>
    <customValue>
        <fullName>Science</fullName>
    </customValue>
    <customValue>
        <fullName>Sociology</fullName>
    </customValue>
    <customValue>
        <fullName>Spanish</fullName>
    </customValue>
    <customValue>
        <fullName>Theater</fullName>
    </customValue>
    <masterLabel>Course Subject</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CourseInterestController.cls
public without sharing class CourseInterestController {


    @AuraEnabled(cacheable=true)
    public static List<CourseEligibility> getEligibleCourses() {
        //Query courses being offered at the program for the student's academic provider
        StudentInformation studentInfo = StudentInformation.getStudentInfosForRunningUser();
        if (studentInfo.enrollment?.Course_Registration_Close_Date__c < System.today()) {
            throw new AuraHandledException('Course Registration Closed for Participant.');
        }
        if (studentInfo.academicProviderId == null) {
            throw new AuraHandledException('Academic Provider not set.');
        }
        List<Course> coursesAvailableAtProgram = new List<Course>();
        for(Course__c course :[
                SELECT Id, Name, Subject__c, Description__c, hasPrerequisites__c,
                (SELECT Credit_Hours__c, Prerequisite_Description__c, Corequisite_Description__c FROM Academic_Provider_Mappings__r WHERE Academic_Provider__c = :studentInfo.academicProviderId),
                (SELECT Course__c, Type__c, Group__c, Condition__c, Corequisite_Course__c, Corequisite_Course__r.Name FROM Course_Prerequisites__r)
                FROM Course__c
                WHERE Status__c = 'Active'
                AND Id IN (SELECT Course__c FROM Course_Offering__c WHERE Program__c = :studentInfo.currentProgramId)
                AND Id IN (SELECT Course__c FROM Academic_Provider_Mapping__c WHERE Academic_Provider__c = :studentInfo.academicProviderId)
                ORDER BY Name ASC
        ]) {
            Course courseObject = new Course(course);
            courseObject.creditHours = (Integer) course.Academic_Provider_Mappings__r[0]?.Credit_Hours__c;
            coursesAvailableAtProgram.add(courseObject);
        }
        if (coursesAvailableAtProgram.isEmpty()) {
            throw new AuraHandledException('No courses available at program for Academic Provider.');
        }
        List<Transcript_Evaluation__c> evaluations = [
            SELECT Id, College_Credit_Received_For__c, Prerequisites_Satisfied_For__c,
            Math_Completed__c, Spanish_Completed__c, Junior_Year_English_Grade__c, GPA__c,
            Transcript_Type__c, Comments__c 
            FROM Transcript_Evaluation__c 
            WHERE Student__c = :studentInfo.accountId
            ORDER BY CreatedDate DESC
            LIMIT 1
        ];
        if(evaluations.isEmpty()) {
            throw new AuraHandledException('No Transcript Evaluation on file.');
        }
        if (!coursesAvailableAtProgram.isEmpty()) {
            return TranscriptEvaluation.getCourseEligibilityForSelectCourses(
                evaluations[0],
                coursesAvailableAtProgram
            );
        } else {
            return null;
        }
    }

    @AuraEnabled
    public static void saveCourseSelection(
        List<Course> primaryChoices,
        List<Course> altChoices
    ) {
        try {
            StudentInformation studentInfo = StudentInformation.getStudentInfosForRunningUser();
            List<Course_Interest__c> courseInterests = new List<Course_Interest__c>();
            for (Integer i = 0; i < primaryChoices.size(); i++) {
                courseInterests.add(new Course_Interest__c(
                    Enrollment_Record__c = studentInfo.enrollment.Id,
                    Course__c = primaryChoices[i].id,
                    Credit_Hours__c = primaryChoices[i].creditHours,
                    Preference_Rank__c = String.valueOf(i + 1),
                    Type__c = 'Primary'
                ));
            }
            for (Integer i = 0; i < altChoices.size(); i++) {
                courseInterests.add(new Course_Interest__c(
                    Enrollment_Record__c = studentInfo.enrollment.Id,
                    Course__c = altChoices[i].id,
                    Credit_Hours__c = altChoices[i].creditHours,
                    Preference_Rank__c = String.valueOf(i + 1),
                    Type__c = 'Alternative'
                ));
            }
            if (!courseInterests.isEmpty()) {
                delete [SELECT Id FROM Course_Interest__c WHERE Enrollment_Record__c = :studentInfo.enrollment.Id];
                insert courseInterests;
            }
            update new Enrollment_Record__c(
                Id = studentInfo.enrollment.Id,
                Course_Interest_Submitted__c = true
            );
        } catch (Exception e) {
            System.debug(e.getMessage());
            throw new AuraHandledException(e.getMessage());
            //create unhandled Exception record.
        }
    }

    /* private Boolean evaluateIfAllCoursesEligible(List<CourseEligibility> courseEligibility) {
        //for each item do the following:
        //check if each course eligibility is marked as true
        //check if the corequisite requirements are met
    } */

    /* private void evaluateForCorequisiteRequirement(List<CourseEligibility> courseEligibility) {
        //put each item into a map of name + object for quicker lookup validations later
        //for each course that's evaluated, check to see if a corequisite is required
        //if false, continue to next course
        //if true, search the other items in the collection (map keySet) to see if the corequisite is included
        //=> then if it is within the collection, continue to the next course
        //=> if not, throw an exception
        //=> => throw new AuraHandledException([coreqCourseName] + ' is a corequisite course of ' + [currentItemName] + ' and must be included.');
    } */
}