unpackaged/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Location__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Potential/Planning</fullName>
                <default>true</default>
                <label>Potential/Planning</label>
            </value>
            <value>
                <fullName>Actively Enrolling</fullName>
            </value>
            <value>
                <fullName>Not Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Current_Program__c.field-meta.xml
<CustomField>
    <fullName>Current_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Represents what program the student is currently in. After closed won, this field can only be edited via automation when the corresponding field is updated on the enrollment record.</description>
    <label>Current Program</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Program__c.Location__r.Name</field>
            <operation>notEqual</operation>
            <value>UNDECIDED</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Opportunities (Current Program)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Tuition_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Tuition_Due_Date__c</fullName>
    <label>Tuition Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Program__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Program__c/fields/Program_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Program_End_Date__c</fullName>
    <description>Semester end date handled at the program level. Typically handled by Akilah or a Salesforce Admin.</description>
    <label>Program End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Program__c/fields/Program_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Program_Start_Date__c</fullName>
    <description>Semester start date, but handled per program. This is typically maintained by Akilah or another Salesforce Admin.</description>
    <label>Program Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Program__c/fields/Semester__c.field-meta.xml
<CustomField>
    <fullName>Semester__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Semester</label>
    <referenceTo>Semester__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Enrolling</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Semester__c/Semester__c.object-meta.xml
<CustomObject>
    <label>Semester</label>
    <nameField>
        <label>Semester Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Semesters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Semester__c/fields/Deposit_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Due_Date__c</fullName>
    <label>Deposit Due Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Semester__c/fields/Semester_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Semester_End_Date__c</fullName>
    <label>Semester End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Semester__c/fields/Semester_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Semester_Start_Date__c</fullName>
    <label>Semester Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Semester__c/fields/Tuition_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Tuition_Due_Date__c</fullName>
    <label>Tuition Due Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/OpportunityTriggerHandlerTests.cls
@IsTest
public with sharing class OpportunityTriggerHandlerTests {

    @TestSetup
    static void makeData(){
        insert new Location__c(
            Name = 'Example Location',
            Status__c = 'Actively Enrolling'
        );
        insert new Semester__c(
            Name = 'Sample Semester ' + String.valueOf(System.today().year()),
            Delivery_Method__c = 'Abroad',
            Semester_Start_Date__c = System.today().addDays(10),
            Semester_End_Date__c = System.today().addDays(10).addMonths(3),
            Deposit_Due_Date__c = System.today().addDays(10).addMonths(3),
            Tuition_Due_Date__c = System.today().addDays(-10).addMonths(3)
        );
        insert new Program__c(
            Name = 'Sample Program',
            Program_Start_Date__c = System.today().addDays(10),
            Program_End_Date__c = System.today().addDays(10).addMonths(3),
            Semester__c = [SELECT Id FROM Semester__c LIMIT 1].Id,
            Location__c = [SELECT Id FROM Location__c LIMIT 1].Id
        );
        User limitsUser = new User(
            FirstName = 'Limit',
            LastName = 'User',
            Alias = 'LUser',
            Email = 'LimitUser@Test.org',
            UserName = 'LimitUser@Test.org',
            EmailEncodingKey = 'UTF-8',
            isActive = true,
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1].Id,
            TimeZoneSidKey = 'America/Los_Angeles'
        );
        insert limitsUser;
        System.runAs(limitsUser) {
            insert new PermissionSetAssignment(
                AssigneeId = limitsUser.Id,
                PermissionSetGroupId = [SELECT Id FROM PermissionSetGroup WHERE MasterLabel = 'Digital Product Team' LIMIT 1].Id
            );
        }
    }
    
    @IsTest
    static void testAfterInsert() {
        
        Test.startTest();
        insert getSampleOpportunity();
        Test.stopTest();
        System.assertEquals(
            1,
            [SELECT Id FROM Opportunity].size(),
            'Expected one successful opportunity inserted.'
        );
    }

    @IsTest
    static void testBulkAfterInsert() {
        Test.startTest();
        List<Opportunity> oppsToInsert = new List<Opportunity>();
        for(Integer i = 0; i < 100; i++) {
            oppsToInsert.add(getSampleOpportunity());
        }
        insert oppsToInsert;
        Test.stopTest();
        System.assertEquals(
            100,
            [SELECT Id FROM Opportunity].size(),
            'Expected 200 successful opportunities inserted.'
        );
    }

    @IsTest
    static void testBeforeUpdate() {
        Opportunity sampleOpp = getSampleOpportunity();
        insert sampleOpp;
        Test.startTest();
        sampleOpp.Current_Program__c = [SELECT Id FROM Program__c LIMIT 1].Id;
        update sampleOpp;
        Test.stopTest();
        System.assertEquals(
            0,
            [SELECT Id FROM Opportunity WHERE Current_Program__c = null].size(),
            'Expected all opportunities to have been updated with a Current Program value.'
        );
    }

    @IsTest
    static void testBulkBeforeUpdate() {
        User contextUser = [SELECT Id FROM User WHERE Username = 'LimitUser@Test.Org' LIMIT 1];
        System.runAs(contextUser) {
            List<Opportunity> oppsToInsert = new List<Opportunity>();
            //currently limiting to 100 records to update, due to CPU limit being hit from process builder.
            for(Integer i = 0; i < 100; i++) {
                oppsToInsert.add(getSampleOpportunity());
            }
            insert oppsToInsert;
        }
        Test.startTest();
        List<Opportunity> oppsToUpdate = [SELECT Id, Current_Program__c FROM Opportunity LIMIT 100];
        Id programId = [SELECT Id FROM Program__c LIMIT 1].Id;
        for(Opportunity each :oppsToUpdate) {
            each.Current_Program__c = programId;
        }
        update oppsToUpdate;
        Test.stopTest();
        System.assertEquals(
            0,
            [SELECT Id FROM Opportunity WHERE Current_Program__c = null].size(),
            'Expected all opportunities to have been updated with a Current Program value.'
        );
    }

    private static Opportunity getSampleOpportunity() {
        return new Opportunity(
            Name = 'Sample Oppportunity',
            StageName = 'Qualified',
            CloseDate = System.today(),
            RecordTypeId = Schema.sObjectType.Opportunity.getRecordTypeInfosByName().get('Traditional Enrollment').getRecordTypeId()
        );
    }
}