unpackaged/main/default/objects/Contact/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <label>Student</label>
</RecordType>

unpackaged/main/default/objects/Enrollment_Record__c/Enrollment_Record__c.object-meta.xml
<CustomObject>
    <label>Enrollment Record</label>
    <nameField>
        <displayFormat>EN-{00000000}</displayFormat>
        <label>Enrollment Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Enrollment_Record__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Program__c.Location__r.Id</field>
            <operation>notEqual</operation>
            <value>a1G3h000000i2EQ</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Enrollment Records</relationshipLabel>
    <relationshipName>Enrollment_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/StudentInformationTests.cls
@IsTest
public with sharing class StudentInformationTests {

    @TestSetup
    static void makeData(){
        TriggerHandler.suppressHandler('AccountTriggerHandler');
        TriggerHandler.suppressHandler('OpportunityTriggerHandler');
        TriggerHandler.suppressHandler('EnrollmentRecordTriggerHandler');
        TestDataFactory.insertMockCommunityUser();
        TestDataFactory.insertMockPrograms();
        TestDataFactory.insertOpportunityAndEnrollmentForAccount([SELECT Id, Name FROM Account WHERE RecordType.Name = 'Student Account' LIMIT 1]);
        update new Enrollment_Record__c(
            Id = [SELECT Id FROM Enrollment_Record__c LIMIT 1].Id,
            Program__c = [SELECT Id FROM Program__c WHERE Name LIKE '%Fall 2022' LIMIT 1].Id
        );
        TriggerHandler.clearSuppressedHandlers();
    }

    @IsTest
    static void testGetStudentInformation() {
        StudentInformation studentInfo;
        User contextUser = [SELECT Id, Contact.AccountId FROM User WHERE Username = 'CommunityUser@Test.org' LIMIT 1];
        Test.startTest();
        System.runAs(contextuser){
            studentInfo = StudentInformation.getStudentInfosForRunningUser();
        }
        Test.stopTest();
        System.assertEquals(
            contextUser.Contact.AccountId,
            studentInfo.accountId,
            'Expected StudentInformation accountId property to match the Account Id of the running user.'
        );
        System.assertNotEquals(
            null,
            studentInfo.enrollment,
            'Expected enrollment record to be set.'
        );
    }

    @IsTest
    static void testgetAllStudentInfosByAccountIdNoEnrollment() {
        StudentInformation studentInfo;
        delete [SELECT Id FROM Enrollment_Record__c];
        User contextUser = [SELECT Id, Contact.AccountId FROM User WHERE Username = 'CommunityUser@Test.org' LIMIT 1];
        Test.startTest();
        System.runAs(contextuser){
            studentInfo = StudentInformation.getStudentInfosForRunningUser();
        }
        Test.stopTest();
        System.assertNotEquals(
            null,
            studentInfo.accountId,
            'Expected StudentInformation accountId to not be null.'
        );
        System.assertEquals(
            contextUser.Contact.AccountId,
            studentInfo.accountId,
            'Expected StudentInformation accountId property to match the Account Id of the running user.'
        );
        System.assertEquals(
            null,
            studentInfo.enrollment,
            'Expected no enrollment record to be set.'
        );
    }

    @IsTest
    static void testGetAllStudentInfosByAccountId() {
        Id studentAccountId = [SELECT Id FROM Account WHERE Name = 'Community User' LIMIT 1].Id;
        Test.startTest();
        StudentInformation studentInfos = new StudentInformation().getAllStudentInfosByAccountId(studentAccountId);
        Test.stopTest();
        System.assertEquals(
            studentAccountId,
            studentInfos.accountId,
            'Expected accountId queried to match the object\'s accountId property value.'
        );
        System.assertEquals(
            [SELECT Name FROM Program__c LIMIT 1].Name,
            studentInfos.currentProgramName,
            'Expected the Program\'s name from the setup to match the object\'s currentProgramName property value.'
        );
    }
}