unpackaged/main/default/objects/Campaign/recordTypes/Five9.recordType-meta.xml
<RecordType>
    <fullName>Five9</fullName>
    <active>true</active>
    <description>The default record type for Five9 contact center campaigns</description>
    <label>Five9</label>
</RecordType>

unpackaged/main/default/objects/Lead/fields/Most_Recent_Call_Date__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Call_Date__c</fullName>
    <description>The date of the last logged call</description>
    <inlineHelpText>The date of the last logged call</inlineHelpText>
    <label>Most Recent Call Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <defaultValue>&quot;US High School Student&quot;</defaultValue>
    <label>Persona</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>US High School Student</fullName>
            </value>
            <value>
                <fullName>International High School Student</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>High School Guidance Counselor</fullName>
            </value>
            <value>
                <fullName>Independent Educational Consultant</fullName>
            </value>
            <value>
                <fullName>Prospective Student</fullName>
            </value>
            <value>
                <fullName>Prospective Parent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/LeadTriggerHandlerTests.cls
@IsTest
public with sharing class LeadTriggerHandlerTests {

    @TestSetup
    static void makeData(){
        insert new Campaign(
            Name = 'Leads Five9 List',
            RecordTypeId = Schema.sObjectType.Campaign.getRecordTypeInfosByName().get('Five9').getRecordTypeId()
        );
    }

    @IsTest
    static void testAfterInsert() {
        
        Test.startTest();
        insert getSampleLead();
        Test.stopTest();
        System.assertEquals(
            1,
            [SELECT Id FROM Lead].size(),
            'Expected one successful lead inserted.'
        );
    }

    @IsTest
    static void testBulkAfterInsert() {
        Test.startTest();
        List<Lead> leadsToInsert = new List<Lead>();
        for(Integer i = 0; i < 50; i++) {
            leadsToInsert.add(getSampleLead());
        }
        insert leadsToInsert;
        Test.stopTest();
        System.assertEquals(
            50,
            [SELECT Id FROM Lead].size(),
            'Expected 200 successful leads inserted.'
        );
    }

    @IsTest
    static void testBeforeUpdate() {
        Test.startTest();
        Lead sampleLead = getSampleLead();
        insert sampleLead;
        sampleLead.Most_Recent_Call_Date__c = System.today();
        update sampleLead;
        Test.stopTest();
        sampleLead = [SELECT Id, CreatedDate, LastModifiedDate FROM Lead WHERE ID = :sampleLead.Id];
        System.assertEquals(
            0,
            [SELECT Id FROM Lead WHERE Most_Recent_Call_Date__c = null].size(),
            'Expected all leads to have a Most Recent Call Date.'
        );
    }

    @IsTest
    static void testBulkBeforeUpdate() {
        List<Lead> leadsToInsert = new List<Lead>();
        for(Integer i = 0; i < 50; i++) {
            leadsToInsert.add(getSampleLead());
        }
        insert leadsToInsert;
        Test.startTest();
        List<Lead> leadsToUpdate = [SELECT Id, Most_Recent_Call_Date__c FROM Lead LIMIT 200];
        for(Lead each :leadsToUpdate) {
            each.Most_Recent_Call_Date__c = System.today();
        }
        update leadsToUpdate;
        Test.stopTest();
        System.assertEquals(
            0,
            [SELECT Id FROM Lead WHERE Most_Recent_Call_Date__c = null].size(),
            'Expected all leads to have a Most Recent Call Date.'
        );
    }

    private static Lead getSampleLead() {
        return new Lead(
            FirstName = 'Sample',
            LastName = 'Lead',
            Company = 'Sample Company',
            Email = 'SampleLead@Test.org',
            Persona__c = 'US High School Student',
            Status = 'Open',
            Phone = '888-888-8888',
            RecordTypeId = Schema.sObjectType.Lead.getRecordTypeInfosByName().get('Traditional Enrollment').getRecordTypeId()
        );
    }
}