unpackaged/main/default/objects/Campaign/recordTypes/Five9.recordType-meta.xml
<RecordType>
    <fullName>Five9</fullName>
    <active>true</active>
    <description>The default record type for Five9 contact center campaigns</description>
    <label>Five9</label>
</RecordType>

unpackaged/main/default/objects/Inquiry__c/Inquiry__c.object-meta.xml
<CustomObject>
    <label>Inquiry</label>
    <nameField>
        <displayFormat>Inquiry-{0000000000}</displayFormat>
        <label>Inquiry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inquiry__c/fields/Parent_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_First_Name__c</fullName>
    <label>Parent First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inquiry__c/fields/Parent_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Last_Name__c</fullName>
    <label>Parent Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inquiry__c/fields/Parent_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Parent_Phone_Number__c</fullName>
    <label>Parent Phone Number</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Inquiry__c/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <label>Persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospective Student</fullName>
            </value>
            <value>
                <fullName>Prospective Parent</fullName>
            </value>
            <value>
                <fullName>High School Counselor</fullName>
            </value>
            <value>
                <fullName>Independent Educational Consultant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inquiry__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Parent Engaged</fullName>
            </value>
            <value>
                <fullName>Student Applied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inquiry__c/fields/Year_of_Graduation__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Graduation__c</fullName>
    <label>Year of High School Graduation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year_of_High_School_Graduation</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inquiry__c/recordTypes/Parent.recordType-meta.xml
<RecordType>
    <fullName>Parent</fullName>
    <active>true</active>
    <label>Parent</label>
</RecordType>

unpackaged/main/default/globalValueSets/Year_of_High_School_Graduation.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1965</fullName>
    </customValue>
    <customValue>
        <fullName>1969</fullName>
    </customValue>
    <customValue>
        <fullName>1973</fullName>
    </customValue>
    <customValue>
        <fullName>1974</fullName>
    </customValue>
    <customValue>
        <fullName>1975</fullName>
    </customValue>
    <customValue>
        <fullName>1977</fullName>
    </customValue>
    <customValue>
        <fullName>1979</fullName>
    </customValue>
    <customValue>
        <fullName>1980</fullName>
    </customValue>
    <customValue>
        <fullName>1981</fullName>
    </customValue>
    <customValue>
        <fullName>1982</fullName>
    </customValue>
    <customValue>
        <fullName>1983</fullName>
    </customValue>
    <customValue>
        <fullName>1984</fullName>
    </customValue>
    <customValue>
        <fullName>1985</fullName>
    </customValue>
    <customValue>
        <fullName>1986</fullName>
    </customValue>
    <customValue>
        <fullName>1987</fullName>
    </customValue>
    <customValue>
        <fullName>1988</fullName>
    </customValue>
    <customValue>
        <fullName>1989</fullName>
    </customValue>
    <customValue>
        <fullName>1990</fullName>
    </customValue>
    <customValue>
        <fullName>1991</fullName>
    </customValue>
    <customValue>
        <fullName>1992</fullName>
    </customValue>
    <customValue>
        <fullName>1993</fullName>
    </customValue>
    <customValue>
        <fullName>1994</fullName>
    </customValue>
    <customValue>
        <fullName>1995</fullName>
    </customValue>
    <customValue>
        <fullName>1996</fullName>
    </customValue>
    <customValue>
        <fullName>1997</fullName>
    </customValue>
    <customValue>
        <fullName>1998</fullName>
    </customValue>
    <customValue>
        <fullName>1999</fullName>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
    </customValue>
    <customValue>
        <fullName>2001</fullName>
    </customValue>
    <customValue>
        <fullName>2002</fullName>
    </customValue>
    <masterLabel>Year of High School Graduation</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/InquiryTriggerHandlerTests.cls
@IsTest
public with sharing class InquiryTriggerHandlerTests {
    
    @IsTest
    static void testAfterInsert() {
        
        Test.startTest();
        insert new Campaign(
            Name = 'Leads Five9 List',
            RecordTypeId = Schema.sObjectType.Campaign.getRecordTypeInfosByName().get('Five9').getRecordTypeId()
        );
        insert getSampleStudentInquiry();
        insert getSampleParentInquiry();
        Test.stopTest();
        System.assertEquals(
            1,
            [SELECT Id FROM Inquiry__c WHERE Persona__c = 'Prospective Student'].size(),
            'Expected one successful inquiry inserted.'
        );
        System.assertEquals(
            1,
            [SELECT Id FROM Inquiry__c WHERE Persona__c = 'Prospective Parent'].size(),
            'Expected one successful inquiry inserted.'
        );
    }

    @IsTest
    static void testBulkAfterInsert() {
        insert new Campaign(
            Name = 'Leads Five9 List',
            RecordTypeId = Schema.sObjectType.Campaign.getRecordTypeInfosByName().get('Five9').getRecordTypeId()
        );
        List<Inquiry__c> inquiriesToInsert = new List<Inquiry__c>();
        for (Integer i = 0; i < 50; i++) {
            Inquiry__c sampleInquiry = getSampleStudentInquiry();
            sampleInquiry.Email__c += String.valueOf(i);
            inquiriesToInsert.add(sampleInquiry);
        }
        TriggerHandler.suppressHandler('LeadTriggerHandler');
        Test.startTest();
        insert inquiriesToInsert;
        TriggerHandler.clearSuppressedHandlers();
        System.assertEquals(
            50,
            [SELECT Id FROM Inquiry__c WHERE Persona__c = 'Prospective Student'].size(),
            'Expected 200 successful inquiries inserted.'
        );
    }

    private static Inquiry__c getSampleStudentInquiry() {
        return new Inquiry__c(
            Persona__c = 'Prospective Student',
            First_Name__c = 'Sample',
            Last_Name__c = 'Student',
            Email__c = 'SampleStudent@Test.org',
            Phone__c = '888-888-8888',
            Zip_Postal_Code__c = '11111',
            Country__c = 'United States',
            Stage__c = 'Open',
            Year_of_Graduation__c = String.valueOf(System.today().year())
        );
    }
    private static Inquiry__c getSampleParentInquiry() {
        return new Inquiry__c(
            Persona__c = 'Prospective Parent',
            Parent_First_Name__c = 'Sample',
            Parent_Last_Name__c = 'Parent',
            Parent_Email__c = 'SampleParent@Test.org',
            Parent_Phone_Number__c = '888-888-8888',
            First_Name__c = 'Sample',
            Last_Name__c = 'Student',
            Year_of_Graduation__c = String.valueOf(System.today().year()),
            RecordTypeId = Schema.sObjectType.Inquiry__c.getRecordTypeInfosByName().get('Parent').getRecordTypeId()
        );
    }
}